### ISSUE TITLE
/login endpoint

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/dashboard#1107]
Prepare `/login` HTTP endpoint for getting the ID token and setting the Refresh token. The endpoint should implement  `Authorization Code` flow. The ID token should be stored in memory in a global variable. The Refresh token should be stored in a secure cookie with `httpOnly`, `secure`, `SameSite` and `path` flags. Additionally The ID token should be valid for 10 minutes and the Refresh token for 30 days.

See https://app.zenhub.com/workspaces/all-kubermatic-58863654794153994b62af76/issues/kubermatic/dashboard-v2/1105 for details

**Comment by cschieder** [comment]
@kubermatic/ui-team this issue is over a year old, is it still relevant?
