### ISSUE TITLE
/refresh endpoint

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/dashboard#1108]
Prepare /refresh HTTP endpoint for getting a new ID token. The endpoint reads the Refresh token from the cookie and generates a new token which is then returned in the response body to the caller. The ID token should be valid for 10 minutes.

See https://app.zenhub.com/workspaces/all-kubermatic-58863654794153994b62af76/issues/kubermatic/dashboard-v2/1105 for details

**Comment by cschieder** [comment]
@kubermatic/ui-team this issue is over a year old, is it still relevant?
