### ISSUE TITLE
Machine Networks Redesign

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#1435]
To do:
- [x] Add checkbox to activate machine deployments when linux selected
- [x] If checkbox active add Machine Networks to steps
- [x] change design of Machine networks to redesign
- [x] change design of "add machine network" to redesign
- [x] change MN view on Cluster to a table 

https://www.figma.com/file/FU4VUDKuHUwkxhKtxTiig0LE/Loodse-UI?node-id=1998%3A9
![Cluster_Create_4_DigitalOcean_Extendedv1](https://user-images.githubusercontent.com/49145827/62198204-8250d780-b381-11e9-9d44-51c414330657.png)

![Cluster_Create_MN1](https://user-images.githubusercontent.com/49145827/62198582-305c8180-b382-11e9-8482-7700b303704f.png)

![Cluster_Create_MN](https://user-images.githubusercontent.com/49145827/62198205-8250d780-b381-11e9-8ebb-6cbfba5ed34e.png)

![Clusters_Overview-MN](https://user-images.githubusercontent.com/49145827/62218395-a70e7480-b3ac-11e9-894a-12f113080703.png)

**Comment by maciaszczykm** [comment]
>  Add checkbox to activate machine deployments when linux selected
 If checkbox active add Machine Networks to steps

In the new wizard "Machine Network" step appears only when Container Linux is selected for VMware provider. To activate the machine networks it is needed to add at least one of them.
