### ISSUE TITLE
Optimize Add SSH key dialog

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#1508]
Too many modals popping up on top of each other, unclear UX

**Comment by cschieder** [comment]
Plus idea, change ssh key select to multiselect (like admission plugins) because for consistent UX dialog closes when adding SSH Key

![Clusters_Overview-Manage SSH Keys](https://user-images.githubusercontent.com/49145827/95316905-b896ba80-0894-11eb-9545-35338eb02ec6.png)
![Clusters_Overview-Manage SSH Keys2](https://user-images.githubusercontent.com/49145827/95316908-b9c7e780-0894-11eb-9366-3b6f7972a723.png)

**Comment by floreks** [comment]
What should `Add SSH Key` link actually do? Redirect user to the SSH Keys view?
