### ISSUE TITLE
Make node names contain human-readable cluster name

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#1838]
### Todo
Change node names to contain the human-readable cluster name by default e. g. cluster-name-xxx-xxx  

Was generally thumbs upped when proposed in slack, comes from here  kubermatic/customer-projects#33

### Question
Does this adjust when you rename the cluster? Or do we carry around names from the whole lifecycle of the cluster on old nodes?

**Comment by maciaszczykm** [comment]
> @maciaszczykm Isn't it problematic when the user updates the cluster name and every ND, node etc. still contains the old name?

If we change all names, including the machine deployment, machines and nodes, we will impact the whole cluster and that might be unexpected for the user and his setup. There is no option to change machine deployment names even manually at the moment but users can still recreate their nodes and then the new names will be used. Besides that all machine deployments are listed in the cluster details and it is pretty easy to connect the dots from here:

![Cluster-new-name-in-Project-default-](https://user-images.githubusercontent.com/2823399/90614195-a55b5d00-e20a-11ea-8eaa-971d07777664.png)

@kdomanski @cschieder In my opinion there is no big issue here and if you have nothing against it I'd close the issue.
