### ISSUE TITLE
Design Kubernetes Dashboard Integration

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#1901]
**For what do you want a design draft?**:
Kubernetes Dashboard

**Requirements how it should look like / what should be in**:
It should have a similar look/branding as Kubermatic Dashboard to make it feel like 1 product.

Our dev instance of Kubernetes Dashboard can be found at:
https://dashboard.dev.kubermatic.io

**Comment by maciaszczykm** [comment]
I'll close this issue and create a new one that will be about creating custom theme for k8s/dashboard.
