### ISSUE TITLE
Add application selection functionality to wizard

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#1904]
Add the addon functionality to the wizard. Right now it is only possible to add a addon after cluster creation.

**Comment by maciaszczykm** [comment]
Let's wait for the new wizard.

**Comment by cschieder** [comment]
Thanks for linking it @kgroschoff :) please look at this version https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=3143%3A3786 because the one you linked is kind of legacy because an updated functionality of figma pushed my designs around a while ago, my link is the reversed "fixed" version, while the one you linked has been broken a bit by said update

**Comment by maciaszczykm** [comment]
It's blocked by the backend at the moment as the implementation is missing.

**Comment by maciaszczykm** [comment]
Also linking the issue: https://github.com/kubermatic/kubermatic/issues/2928#issuecomment-676147024

**Comment by maciaszczykm** [comment]
Removing it from the milestone as this is no longer possible.

@shaase-ctrl Please add it to correct milestone.

**Comment by SimonTheLeg** [comment]
The functionality described in this ticket will be added with the new Applications mechanism. Currently we do not plan to extend the current AddOn mechanism with this functionality. As a result I have moved the ticket to the Applications Epic and renamed the title.

Subsequently here are some of my thoughts regarding possible changes to the Mockup with the applications. There are no immediate changes required, just listing them here so they do not get lost (cc: @kubermatic/sig-ui). These are food for thought only of course:
1. Applications introduce the idea of cluster compatibility. What this means is that the list of available applications for a cluster depends on what the user has selected for this cluster. So for example some applications are incompatible with certain k8s versions or selected cloud providers. The list of available applications will be generated on the fly when you call the endpoint in the BE with the parameters. However for the wizard this might become more complicated: We basically need to make sure it is easy for a user to understand that you first have to enter all the cluster information and only once that is complete you can select the applications
2. The custom form that can be configured with addons (also known as `formSpec`) , will become yaml and as a result nestable. Consequently I think we might need a different way of displaying this unless we want to nest form fields indefinitely. One idea could be, to have a simple editor as shown in the current mockup under the "constraint template" and then just have the user type in yaml.
So just my two cents for now :)

**Comment by SimonTheLeg** [comment]
@Waseem826 I think the functionality described in this ticket is done, or? I think this ticket is an older leftover.

From my side we can close it.

**Comment by Waseem826** [comment]
This is about addons and we don't have addons in wizard. I'm not sure if we need it or not.

**Comment by SimonTheLeg** [comment]
I think this ticket got repurposed multiple times and changed from Addons to Applications. Because at the current time, we do not want to display addon selection in the wizard. Let's put this ticket to rest.
