### ISSUE TITLE
Add logs for cluster control plane elements

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#1905]
Add logs (exec?) for debugging reasons for cluster control plane elements (api server, machine controller, etcd,....)
--> might need additional issue for backend
--> also might need some input from @cschieder regarding design. tbd.

**Comment by thetechnick** [comment]
Hey @kgroschoff!
Could you add a few more details on this feature and whats the rationale behind it?

As Kamil already pointed out, Kubermatic Admins can already view those logs via Kibana (probably way better than we could sensibly build into our UI) and I would argue that end-users can not do anything with those logs, even if they have access to view them.

**Comment by kgroschoff** [comment]
@thetechnick unfortunately I don't really have a lot of details here... 
I only know that this was requested some time ago, but I'm not sure if this is still needed.

But we have some really really really old mocks, maybe this helps?

Here you can see the `View Logs` link next to all control plane elements:
![aaaaa](https://user-images.githubusercontent.com/19547196/93854826-b9d1c000-fcb6-11ea-95cb-102cc15ab3d0.PNG)

![aaaa](https://user-images.githubusercontent.com/19547196/93854825-b9392980-fcb6-11ea-821d-843f9d5133c1.PNG)

**Comment by cschieder** [comment]
Let's close legacy issues where the reasons why it's needed have been forgotten, if it's important it will come up again anyway
