### ISSUE TITLE
Help/Support Section

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#1934]
As a user, I want to know where I can find help immediately in the UI

- Link to Documentation
- Link to Ticket System
- Link to last available Changelog
- Make the links configurable
- Use the admin panel to configure the Help Section

![image.png](https://images.zenhubusercontent.com/5d00e804f425650e637ab800/c4ba4d26-9356-445f-ae4e-612064debed7)

**Comment by shaase-ctrl** [comment]
Needs refinement after cutting guided tour.
