### ISSUE TITLE
Required credentials in Edit Cluster Dialog

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#2051]
Currently the credential fields in the `Edit Cluster` Dialog get required only if they are touched.
There are three options how to handle it in the future
1. Let it as it is right now: Dynamically add the required validator.
2. Make them required by default.
3. Make them optional by default and don't add a required sign at all.

Current talk about this topic:

> **floreks** 
> Removing validator when fields are empty and adding it when they are not kind of kills the idea of having required validator. To have this asterisk added at the end simply add required to the field in the template.
> 
> Example
> 
> <input id="km-create-cluster-name-input"
>                  matInput
>                  [formControlName]="Controls.Name"
>                  type="text"
>                  title="name"
>                  autocomplete="off"
>                  required>
> This makes angular add it automatically. We shouldn't do it by hand.

---

> **kgroschoff** 
> Agree.
> But This is in the edit cluster dialog. There it is also possible to just change the cluster name. I'm wondering, if it might confuse users to see the required indicator for those fields. In case they just want to change the name, the credentials are not required. (does this sentence make sense?) 🤔 Any opinion?
> 
> (Apart from that I've found some bug, because currently it is not possible to "only" change the name, because backend complaints that there are no valid credentials, which should not happen :trollface: But that's not ui's fault -> Will take a look)

---

> **floreks**
> IMHO fields should be required or not required at all times. This part should not be conditional and change once you open a view/dialog. Even if it's an edit action and name is already filled out it is fine to show that this field is required and requires some value.
> 

---

> **kgroschoff**
> Ok, sounds good 👍
> Just to involve the whole team: @maciaszczykm do you agree?

---

> **maciaszczykm**
> In general, I agree with not changing if the field is required or not. I think in that case credentials should always stay optional (not required) and we should make sure that patch will overwrite only the fields that have changed.

---

cc @maciaszczykm @floreks 
@cschieder Maybe you want to add something from UX view?

**Comment by floreks** [comment]
WDYT about moving provider credentials to a separate `Edit Cluster Credentials` dialog and then making all those required fields actually required at all times?

**Comment by kgroschoff** [comment]
That was the case before. I think there were some complaints that you have seperate dialogs for it... 
However I personally also prefer to have credentials somehow seperated, as I personally have the impression that it is "too easy" to change them...

**Comment by floreks** [comment]
@cschieder could you share your thoughts here?

**Comment by maciaszczykm** [comment]
@cschieder can you take a look on it?

**Comment by cschieder** [comment]
Okay first of all, I agree that putting the Credentials into another dialogue seems like the easiest and simplest option but some questions popped up:

- What about using presets in cluster edit should we/can we add that?
- I checked with an AWS cluster and it had like 7 fields on the cluster create page on the settings step, but it only has 2 fields on the edit dialogue, whats up with that? Do we not show all fields there and if so why? Also should we show advanced fields there or no?

Small note: pod security warning text is different on cluster create than it is on cluster edit, please use the cluster create version in both places, thanks

**Comment by floreks** [comment]
> What about using presets in cluster edit should we/can we add that?

Good point. To be honest I am not sure why credentials can be changed and preset not. I am actually wondering what will happen if we create a cluster based on preset and then edit the cluster and set credentials. @zreigz any idea?

I guess it should be also possible to select a different preset if needed and not only update raw credentials.

> I checked with an AWS cluster and it had like 7 fields on the cluster create page on the settings step, but it only has 2 fields on the edit dialogue, whats up with that? Do we not show all fields there and if so why? Also should we show advanced fields there or no?

I guess it's because this part is only about updating the credentials, not the configuration itself. Only those 2 fields are required to update the credentials. We'd need to extend this feature to offer a complete configuration update, not only a credentials update.

We can think about redesigning it and offering more features, though it would be a new epic. As for this issue goes. Can we provide a temporary solution by i.e. using a simple different dialog or should we create a new epic to redesign this feature and offer more configuration options?

> Small note: pod security warning text is different on cluster create than it is on cluster edit, please use the cluster create version in both places, thanks

Created an issue otherwise, we'd definitely forget about this: https://github.com/kubermatic/dashboard/issues/3032

**Comment by zreigz** [comment]
The cluster credentials are stored in the special secret assigned to the cluster. During creation, they are taken from preset or directly from the user. During the update, it doesn't matter if the credentials are different than in preset. The point is to have valid credentials.

**Comment by zreigz** [comment]
I am not sure if the backend supports changing credentials from the preset

**Comment by floreks** [comment]
@cschieder PTAL

**Comment by cschieder** [comment]
As far as this issue specifically goes I agree with @kgroschoff - we can put the credentials in a separate dialogue 

I don't know how important extending the settings is and how often a user would want to do that. From a non-technical perspective it seems to me that if we offer to edit the cluster credentials we should make all fields available for changes. If the ratio of effort to benefit is unfortunate, it might be too much work for too little improvement, though.

**Comment by floreks** [comment]
Great. I'll open two separate issues and then close this one.

1. Split credential management from edit cluster.
2. Add more provider fields to the new dialog.

**Comment by floreks** [comment]
Closing in favor of #3090 and #3089
