### ISSUE TITLE
GCE  Provider - Network UI selection is incorrect

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#2093]
**User Story**
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/d7cb7bfe-4d6e-43c3-8a23-178254975419)
After a custom network e.g. `k1` is selected, the user cluster don't get provisioned correctly
```
 Normal   NodeDeploymentCreationStart  13m                 kubermatic-api               Started creation of initial node deployment  otto-k8c-az-a
  Warning  ReconcilingError             11m (x19 over 13m)  kubermatic_cloud_controller  failed cloud provider init: failed to create firewall rule firewall-wc4lpgjh6n-self: googleapi: Error 400: Invalid value for field 'resource.network': 'k1'. The URL is malformed.
More details:
Reason: invalid, Message: Invalid value for field 'resource.network': 'k1'. The URL is malformed.
Reason: invalid, Message: Invalid value for field 'resource.network': 'k1'. The URL is malformed.
```
Instead of `rerouce.network: k1` we would need the correct network path in this case `rerouce.network: global/networks/k1`

Here you find the current network setup at the GCP cloud. Also the subnet selection is not working - here the `k1-subnet` is not shown.
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/a2cc4127-18e3-4cb7-b126-ea080beb81d2)

**Acceptance criteria**
- [ ] GCE cluster provisioning with custom VPC and subnet is working from the UI selection

**Comment by toschneck** [comment]
@kgroschoff sorry for the long delay

I tested it right now: the network itself is now shown correctly, but the subnet selection is not showing something and is broken in my opinion (even default network don't show something):
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/78142b36-bb93-4c62-b424-6873402d2089)
this will den reflected in the cluster CRD, what leads to an error on the machine deployment:
```
    gcp:
      credentialsReference:
        name: credential-gcp-dfqw9cm5kk
        namespace: kubermatic
      network: global/networks/k1
      subnetwork: ""
```
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/28d6dd24-9701-49d4-a12c-6b83f1e064dd)
```
An error of type = InvalidConfiguration, with message = Failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0]': '{ "network": "global/networks/k1", "accessConfig": [{ "type": "ONE_TO_ONE_NAT", "name": "Ext...'. Subnetwork should be specified for custom subnetmode network, invalid occurred
```
If I adapt in the cluster resource the subnet, by hand by `kubectl edit cluster`, the provisioning works:
```
      network: global/networks/k1
      subnetwork: projects/test-00-wipro/regions/europe-west3/subnetworks/k1-subnet-europe-west3
```

If you create a service account with the following rights (according to our docs):
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/4ae57bce-f2c6-428d-a030-64e2c0dd3da4)
you should be able to reproduce it.

The network:
```
{
  "gatewayAddress": "10.230.0.1",
  "id": "3680089978964607859",
  "ipCidrRange": "10.230.0.0/24",
  "name": "k1-subnet-europe-west3",
  "networkUrl": "projects/test-00-wipro/global/networks/k1",
  "regionUrl": "projects/test-00-wipro/regions/europe-west3",
  "selfLink": "projects/test-00-wipro/regions/europe-west3/subnetworks/k1-subnet-europe-west3"
}
```
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/e3a272ee-87d5-4ee9-b499-3c0e9f0ce2d7)

**Comment by kgroschoff** [comment]
Okay, thanks. I'll have a look :)

**Comment by kgroschoff** [comment]
@toschneck Indeed there was a problem with subnetworks in general. Fixed the related part in the backend, so it should work now :)

**Comment by toschneck** [comment]
@kgroschoff  Can't confirm, can now select the subnet, but the created MachineDeployment fails again:
![image](https://user-images.githubusercontent.com/4659261/87293881-3a2fb400-c503-11ea-8cf3-c75bd57f320f.png)
`An error of type = InvalidConfiguration, with message = Failed to insert instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].subnetwork': 'k1-subnet-europe-west3'. The URL is malformed., invalid occurred`

**Comment by kgroschoff** [comment]
looks like we also need to use the whole path instead just the name. should be fixed fairly quick

**Comment by toschneck** [comment]
ok thanks for it
