### ISSUE TITLE
Design editor

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#2367]
**For what do you want a design draft?**: Text editor that will be added in the https://github.com/kubermatic/dashboard/pull/2353. If the pull request is already merged it can be seed during creation/edit of dynamic datacenters. It would be good to establish some styling so we can reuse it i.e. in the object YAML editor.

**Requirements how it should look like / what should be in**: We are using the https://microsoft.github.io/monaco-editor/.

**Comment by maciaszczykm** [comment]
<img width="805" alt="Zrzut ekranu 2020-06-19 o 09 17 23" src="https://user-images.githubusercontent.com/2823399/85107119-b50bf480-b20d-11ea-8030-f4ad35c12617.png">
<img width="791" alt="Zrzut ekranu 2020-06-19 o 09 17 01" src="https://user-images.githubusercontent.com/2823399/85107129-b806e500-b20d-11ea-9322-3b1548291593.png">

This is the current version.

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/90729770-5aebe600-e2c7-11ea-9333-2ec3c2cee2f9.png)

font: Inconsolata, size 14
