### ISSUE TITLE
check-licenses makes it hard to commit changes for windows user

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#2378]
With the `check-licenses` check, it is not possible to commit new changes to the repo as a windows user (at least not simply by using git commit), because of the following:

```
> kubermatic-dashboard@2.14.0-rc.2 check:licenses C:\{local_path}\dashboard
> ./hack/check-licenses.sh

Der Befehl "." ist entweder falsch geschrieben oder konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubermatic-dashboard@2.14.0-rc.2 check:licenses: `./hack/.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubermatic-dashboard@2.14.0-rc.2 check:licenses script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

btw `Der Befehl "." ist entweder falsch geschrieben oder konnte nicht gefunden werden.` means `The command "." is eather misspelled or could not be found.`

**I** still can work with this atm, but _probably_ in the _near future_ it might cause "problems"
cc @floreks @maciaszczykm 🤷 😆

**Comment by maciaszczykm** [comment]
For now https://gitforwindows.org/ should be a way to go for Windows users. Let's reopen it in the future if we want further improvements.
