### ISSUE TITLE
GCP Provider: Define Sane Default for Machine Type

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#2464]
**User Story**
Currently as default selection in the UI a very expensive `e2-highcpu-16` machine type get used. It would be much better to use a standard machine type like, e.g. : `n1-standard-2`

![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/a247bbbb-cce5-455a-8564-26c36f0da199)

**Acceptance criteria**
- UI shows a sane default machine for GCP

**Comment by floreks** [comment]
This is not only limited to GCP. We should check all providers and try to set cheapest possible settings as defaults. IIRC Alibaba by default uses some huge 64 core instances.

**Comment by floreks** [comment]
Fixed by https://github.com/kubermatic/dashboard/pull/2541

/close
