### ISSUE TITLE
Provide a warning when clusters are running EOL version of K8S

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/dashboard#2497]
**What would you like to be added? / User Story**:
Many users will set up their cluster once and then neglect the need to upgrade its version. This results in running clusters which are at an EOL version containing vulnerabilities - a strong case for immediate upgrade. However we cannot always just automatically upgrade the clusters, because sometimes manual migrations of loads are required, e.g. due to API versions deprecated in v1.16. For that purpose we'd like to visually highlight clusters running EOL versions in the UI.

**Acceptance criteria*:
- [ ] clusters running versions `<1.16.0` are highlighted in the UI with a warning
  - [ ] in their respective detail views
  - [ ] on a project's cluster list
  - [ ] ~~in the project list, projects containing EOL clusters are highlighted similarly~~
- [ ] the warning is of a higher severity (e.g. in red) so that in the future we can use a lower severity visual warning to show clusters which are not yet EOL, but will soon be
- [ ] the specific version value `<1.16.0` is relatively easy to change in the future

**Comment by floreks** [comment]
@kdomanski shouldn't a list of EOL versions and near EOL versions be provided by the API? This way we could make it configurable. If we hardcode it in the frontend then it will always require a new build.

**Comment by kdomanski** [comment]
@floreks yes, agreed. Shall we create a backend issue or will you just work it off this ticket?

**Comment by floreks** [comment]
@kdomanski Actually I've used UI config to manage that. Should be enough I guess.

https://github.com/kubermatic/dashboard/pull/2520/files#diff-7c7e1bc2f9cd45e5fc198ee49bb21707R6-R9
