### ISSUE TITLE
GCP: Upgrade cluster dialog broken

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#2505]
**What happened?**:
After I created a new GCP cluster, I wanted to upgrade the cluster, then I get the following error:
`Error 400: invalid cluster: invalid cloud spec: serviceAccount cannot be empty`
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/a1170126-c263-4e2d-a78b-dd1537354676)
**What should happen?**:
account is stored in cluster config and upgrade should get started

**How to reproduce?**:
1. create cluster GCP
2. upgrade cluster

**Environment**
- UI Version: `quay.io/kubermatic/dashboard-ee:weekly-2020-29`
- API Version:`quay.io/kubermatic/kubermatic-ee:weekly-2020-29`
- Domain:
  - [ ] run
  - [ ] run-2
  - [ ] dev
  - [ ] locally
- Others: training test of https://github.com/kubermatic/customer-projects/pull/316

**Comment by floreks** [comment]
The API has changed recently and we are still adjusting frontend.

**Comment by toschneck** [comment]
ok, wasn't aware of it, could ping me when it is fixed.
Due to the fact that we use the GCP provider for training it would be good to know :)

**Comment by floreks** [comment]
Will be fixed by https://github.com/kubermatic/kubermatic/pull/5690

/close
