### ISSUE TITLE
Wizard Follow Up

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#2519]
On every step
- [x] Spacing (lets try 45 and we can still change this number some if we think it needs more space) ![image](https://user-images.githubusercontent.com/49145827/88630928-a688e680-d0b1-11ea-867a-1c053942a45b.png)

### 1) Step Provider
- [x] Logo sizes max width all -> 95 px
aws, azue, packet, vmware -> min-height 24px

- [x] left align datacenter inside of box

### 2) Step Cluster
- [x] Specification -> Version isn't in line with the rest
- [x] Text Change on Pod Security Policy Warning

> Activating Pod Security Policy will mean that a lot of Pod specifications, Operators and Helm charts will not work out of the box. Make sure that you know the consequences of activating this feature.

 -> `An active Pod Security Policy entails that a lot of Pod specifications, Operators and Helm charts will not work out of the box. `

### 3) Step Settings
Note: I don't like the Basics/Advanced Styling quite yet, I have written a task for myself to check it out if I come around to it I will add it in a comment otherwise we will do it another time 

- [x] On Digital Ocean for example it's confusing upon coming to this page because there are no advanced settings, could we hide the headline when only having basic options like with Digital Ocean?

- [x] Change Preset to be called Provider Preset

- [x] Text Change Provider Preset Preset hint to

-> `Using Provider Presets will disable other provider-related fields.`

- [ ] Remove space between asterics and field title on required fields, I don't think the space is in common use

### 4) Step Initial Nodes
Question: Are we removing Container Linux from Cluster Create anytime soon?

- [x] RHEL add a greyscale logo variant? it looks kinda broken when using the filter (ping me to recieve svg)

- [x] Upgrade system on first boot the circle that appears when you click it is cut off, please fix

### 5) Step Summary
- [x] circle wrong size should be 24px (like in the stepper) lets use the button color as the border color and change text color of the number to the usual grey, number is text-size 14px

- [x] Numbers not correctly aligned inside circle, may be fixed if point above this one is done

**Comment by floreks** [comment]
> Remove space between asterics and field title on required fields, I don't think the space is in common use

This seems to be another discrepancy between the angular material framework and material design. We can change that.

**Comment by floreks** [comment]
I'll take this one

**Comment by floreks** [comment]
> left align datacenter inside of box

Do you mean text or everything inside the box? If everything then there is padding on both sides of the box, so we would have to decrease or remove it from the left side.

**Comment by floreks** [comment]
@cschieder

**Comment by cschieder** [comment]
> Do you mean text or everything inside the box? If everything then there is padding on both sides of the box, so we would have to decrease or remove it from the left side.

if I remove the width 100% in inspector it does exactly what I want, the padding stays and the content becomes left-aligned, instead of the flags starting at different distances from the left side, imo it looks tidier

> This one unfortunately we can't easily fix. Space is not added with the css. This is a regular space (&nbsp) added directly as part of the placeholder text. It is added programmatically and it would be hard to manipulate that.

Okay, unfortunate but not something critical, thanks for checking

> To fix this we have to either move it slightly to the right (10-12px) or disable ripple effect.

I take it there's no option to keep the ripple and not cut it off? 

> Should spacing between the bottom buttons and step content be const? Right now it differs between steps?

Yea should be consistent :)

**Comment by floreks** [comment]
> I take it there's no option to keep the ripple and not cut it off?

I'll check 1 more thing, but it seems that this effect is a bit buggy when content is left aligned inside the box and ripple is on the edge.

> Yea should be consistent :)

How big? 30px?

**Comment by cschieder** [comment]
> How big? 30px?

from content to button its 30px, from stepper to content its like 45/50px (the same as the spacing above any headline in the wizard), hope that answers it?
