### ISSUE TITLE
Make it possible to toggle the `ensure` label on addons

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/dashboard#2540]
depends on kubermatic/kubermatic#5672

After the corresponding API endpoint has been created, the addons UI needs to be extended with a control to toggle the label.

Likely needs design from @cschieder

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/90631766-97fe9c80-e223-11ea-969a-2a08d3c12f65.png)
on info icon
> With this flag enabled the addon cannot be deleted or modified outside of the UI after installation
