### ISSUE TITLE
UI/UX Fixes & Discuss

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#2564]
**Fixes**
- [x] Creating new project, big delay until project shows up in table/as a card 
- [ ] User with viewer role sees ssh key management as not greyed out in ui 

**To Discuss**
- Delete Project name copy function missing, argubly a hurdle for users that we might want to keep
- Evaluate keyboard usability, enter on modals to confirm dialogue

**Comment by floreks** [comment]
> Misstyping vcenter credentials and then moving focus away from the credential inputs totally breaks the ui, it will then repeatedly try to use these credentials to fetch data (eg available networks etc), spam error toasts, ramp the browser cpu usage up

I can't reproduce that. After providing invalid credentials it shows an error, but everything still works. I can remove old credentials and provide the new one and everything works. Do you have better steps to reproduce?

**Comment by cschieder** [comment]
@erdii received this feedback from customer, can you give us more info, Joshi?

**Comment by floreks** [comment]
Anything related to the wizard that comes from customer is invalid for us as we are using a new wizard now and they are still using the old one.

**Comment by cschieder** [comment]
Ok I'm deleting it

**Comment by erdii** [comment]
> Anything related to the wizard that comes from customer is invalid for us as we are using a new wizard now and they are still using the old one. It would have to be checked and fixed separately for v2.14.

@floreks can customers already try the new wizard? we just had the credential problem multiple times in a row

**Comment by maciaszczykm** [comment]
@erdii The new wizard was introduced in https://github.com/kubermatic/dashboard/pull/2481 as the default one on master. It should be fully functional at the moment.

**Comment by floreks** [comment]
It is available on dev, but not for the clients. It will be a part of v2.15 release.
