### ISSUE TITLE
Extend Admin settings for the restrictProjectCreation

### ISSUE THREAD

**Issue by zreigz** [kubermatic/dashboard#2603]
**User Story**
The Kubermatic settings have:
```
RestrictProjectCreation bool           `json:"restrictProjectCreation"`
```
It's not supported in the UI for the Admin Panel

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/92493007-4fb81600-f1f4-11ea-8c62-5371a10e0f98.png)
