### ISSUE TITLE
Display deletion state of accessible addons

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#2650]
**What is the problem, where is it and why is it an issue?**
When we currently deleting an addon the deletion is commited as an event in the UI, but the user don't get feedback that may the deletion is still in progress. For some addons (e.g. if a Service Type LoadBalancer is in the Addon Manifest) the deletion can take minutes and the user wouldn't see that the deletion is still in Progress.

Version: `quay.io/kubermatic/dashboard-ee:weekly-2020-38`

**Suggest how to fix it, if possible**

An UI indicator that a change is still in progress for the addon would help from the usability point of view. Due to the `addon` object, we should have the information:
`k get addon ingress-nginx -o yaml -n cluster-wchcmmgwn8`
```
apiVersion: kubermatic.k8s.io/v1
kind: Addon
metadata:
  creationTimestamp: "2020-09-22T17:34:11Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2020-09-22T17:51:30Z"
  finalizers:
  - cleanup-manifests
  generation: 3
  managedFields:
  - apiVersion: kubermatic.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences: {}
      f:spec:
        .: {}
        f:cluster:
          .: {}
          f:kind: {}
          f:name: {}
          f:uid: {}
        f:name: {}
        f:variables:
          .: {}
          f:replicas: {}
      f:status: {}
    manager: kubermatic-api
    operation: Update
    time: "2020-09-22T17:34:11Z"
  - apiVersion: kubermatic.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers: {}
      f:status:
        f:conditions: {}
    manager: seed-controller-manager
    operation: Update
    time: "2020-09-22T17:34:13Z"
  name: ingress-nginx
  namespace: cluster-wchcmmgwn8
  ownerReferences:
  - apiVersion: kubermatic.k8s.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: wchcmmgwn8
    uid: eebcda1d-7089-41ef-9097-8004eca82670
  resourceVersion: "171395627"
  selfLink: /apis/kubermatic.k8s.io/v1/namespaces/cluster-wchcmmgwn8/addons/ingress-nginx
  uid: 2d7f62aa-d8f3-4f37-bdbb-9b65c15876e0
spec:
  cluster:
    kind: Cluster
    name: wchcmmgwn8
    uid: eebcda1d-7089-41ef-9097-8004eca82670
  name: ingress-nginx
  variables:
    replicas: "1"
status:
  conditions:
  - lastHeartbeatTime: "2020-09-22T17:34:13Z"
    lastTransitionTime: "2020-09-22T17:34:13Z"
    status: "True"
    type: AddonResourcesCreatedSuccessfully
```

**Comment by maciaszczykm** [comment]
@cschieder can you prepare some mock how we should display it?

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/94137954-90a46180-fe67-11ea-9406-474a10273e56.png)
I'm thinking one of the right options, maybe with tooltip "addon is being deleted" 

Do we have the reverse of this problem, too? i. e. when creating an addon it only pops in with a delay?

**Comment by maciaszczykm** [comment]
We could think about something based on the addon status field. As you can see the one above has `AddonResourcesCreatedSuccessfully` indicator. However, this is not determined yet, so at the moment we don't need any design I think.
