### ISSUE TITLE
Selecting Pod Security Policy admission plugin not taken into account

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/dashboard#2653]
**What happened?**:
When creating a user cluster through the UI it is possible to select the `Pod Security Policy` admission plugin, but apparently it is not taken into account.

**What should happen?**:
The Cluster should be created with the `usePodSecurityPolicyAdmissionPlugin` flag set to `true`, but it's not.

**How to reproduce?**:
Create a cluster using the creation wizard, activating `Pod Security Policy` checkbox in the Admission Plugins. 

**Environment**
- UI Version: quay.io/kubermatic/dashboard-ee:c8cac4fee72108a8cbc2ebd9bd5e279777322c21
- API Version:
- Domain:
  - [ ] run
  - [ ] run-2
  - [X] dev
  - [ ] locally
- Others:

**Comment by maciaszczykm** [comment]
Please also put the fix to v2.15.
