### ISSUE TITLE
Prepare a list of supported browsers

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#2660]
**What would you like to be added? / User Story**: I think we should prepare a list of browsers that we support. We can use https://www.npmjs.com/package/browserslist for that. 

Candidates (to verify):
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [x] Safari

**Comment by maciaszczykm** [comment]
@kgroschoff Can you test the Edge browser as you seem to be the only one with Windows here?

**Comment by kgroschoff** [comment]
I cannot find anything that isn't working properly or is looking different in Edge (compared to Chrome). 
So thumbs up from my side.

**Comment by maciaszczykm** [comment]
Thanks, I will verify the Firefox and add the list of the supported browsers.
