### ISSUE TITLE
Presets selection blocks undefinable UI selection/input fields 

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#2699]
**What happened?**:
If a preset is selected on any cloud provider, more fields as presets contains get blocked for selection / input. This could be some problem, if you have e.g. two networks in your cloud account. You can't define the network parameter in the presets and also you can't modify them in the UI.

**What should happen?**:
Two options are possible:
1. The presets contains every blocked input value (also the network etc, what could be somehow cause problem if credentials <> network are settings are not matching)
2. The currently blocked input values, get freed up and  user can select/enter the input fields.

Nevertheless we should have 1:1 matching between definable fields  and blocked UI input fields.

**How to reproduce?**:
Create a preset, then create a cluster and try to select a different parameter e.g. network

**Examples:**
*Azure*
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/5b478abf-9a0e-4e0b-886e-c5d3f267fb68)
Azure Preset Spec,see https://docs.kubermatic.com/kubermatic/master/advanced/presets/:
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/4e0f8d4c-bae1-480d-900d-6f1dcbdf90bc)
*vSphere*
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/55f3a498-9bf4-493c-9a46-660bb171db17)
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/4d37c4fb-4f6f-4cc7-af7d-cf686b34c3af)

**Environment**
- UI Version: v.2.15.rc-3
- API Version: v.2.15.rc-3
- Domain:
  - [ ] run
  - [ ] run-2
  - [ ] dev
  - [ ] locally
- Others:

**Comment by floreks** [comment]
Even though it might not be seen in the sample you have provided, it is possible to provide an advanced section in the preset configuration. We block all information that can be a part of a preset as preset is a set of provider information and are all part of a single structure. We can either fill out and provide a structure or use a preset. There is no way to mix those options.

https://github.com/kubermatic/kubermatic/blob/db886781b3c2a1492352984e398084869a7c3a51/pkg/crd/kubermatic/v1/preset.go#L79

**Comment by toschneck** [comment]
Ow understand! But then the documentation is out of sync.  I don't think any user of KKP will looking for this.
 @floreks can we fix the docs? The best way in my opinion would be if it get automatically upgraded when a modifications on the preset definition will be done.

**Comment by toschneck** [comment]
@zreigz  for vSphere the CCM credentials can't get set in the preset object, so I open for this topic a separate issue: https://github.com/kubermatic/kubermatic/issues/6447
