### ISSUE TITLE
Cluster search filter: Add message if no item fits

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#2722]
If you enter some "invalid" string into the search bar on the cluster list, you will get an error in the dev console, saying `ERROR TypeError: Cannot convert undefined or null to object`. The items in the table stay the same though. [e.g. you only have a cluster named `test-cluster` and you enter the string `goofy`]
As I usually have only a very limited number of clusters, this is easy to see, but thinking of a large amount of clusters it might be unexpected if you enter something in the search bar and nothing happens? WDYT? Maybe it would be good to display a message that no item was found or similar?

**Comment by maciaszczykm** [comment]
Good spot, I've missed one check for NPE. I'll add the zero state message too.
