### ISSUE TITLE
Cluster Page Implement Tabs

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#2780]
![image](https://user-images.githubusercontent.com/49145827/98645324-143fe200-2332-11eb-8b3f-665ad8f604fc.png)

https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=4594%3A27377

**Comment by floreks** [comment]
I really like the idea of merging less commonly used cards into tabs. It looks nice and usability is not impacted.
