### ISSUE TITLE
Assist Marketing with Kubernetes Dashboard Blog

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/dashboard#2797]
Marcin and or Sebastian shall assist with some bulletpoints on Kubernetes Dashboard for the official Kubernetes Blog.

**Comment by floreks** [comment]
@kgroschoff could you please delete this issue. As an admin, you should be able to do it.

**Comment by kgroschoff** [comment]
No, unfortunately I can't. I don't have the permission to delete issues.
