### ISSUE TITLE
[UI] Presets Management in the Admin Panel

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#2798]
**What would you like to be added? / User Story**:
It should be possible to manage presets via the UI in the admin panel.

#### Limitations
For security reasons when editing a preset, it will not be possible to see existing preset information. It will only be possible to override it by providing a brand new set of information.

#### Note
The preset object contains a set of supported providers. It will not be possible to only create a preset without providing at least 1 provider information. It means that adding another provider to the preset only updates the preset object. It does not create a new preset.

#### Acceptance Criteria
- [x] List presets for all providers
  - [ ] ~Filter by enabled status~
- [x] List presets for selected provider
  - [x] Filter by datacenter
  - [ ] ~Filter by enabled status~
- [x] Create a preset for the provider
  - [x] Restrict preset to selected datacenter
  - [x] Mark created preset as enabled/disabled
- [x] Update (override) existing provider preset information
  - [x] Enable/disable preset
  - [x] Update/remove datacenter restriction

**Comment by cschieder** [comment]
Design: https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=4665%3A1
