### ISSUE TITLE
Remove external dependency on fonts.googleapis.com

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2800]
**What would you like to be added? / User Story**:
The dashboard loads CSS/fonts directly from Google (`<link href="https://fonts.googleapis.com/icon?family=Material+Icons">`). This does not work in my offline setup and is also leaking user information to Google.

Can we investigate if/how we can deliver these assets locally? I'm not sure that the Google license allows redistribution.

**Comment by maciaszczykm** [comment]
There is a way to save the icons into the repository provided by Google if I remember correctly. However, some time ago we have changed a lot of the icons to our own. I think we should check if it would be possible to replace them with our own. Doing quick search for `<mat-icon` returns only 13 results and 7 of them are close icon.

**Comment by kgroschoff** [comment]
We already have a `km-icon-close` so it should be very easy to get rid of the mat icons ;)
