### ISSUE TITLE
Improve ServiceAccount Token creation

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2801]
**What is the problem, where is it and why is it an issue?**
When creating a new token for a Service Account, I get a popup that asks me for a name, with no indication that the actual token is created automatically at a later step:

![screenshot-2020-11-25-152851](https://user-images.githubusercontent.com/127499/100241227-c4693980-2f33-11eb-9fee-76de1b427fe5.png)

**Suggest how to fix it, if possible**
It would be nice if the popup indicates that another step is following (Windows back in the day used an ellipsis on UI elements to indicate "after clicking here, another thing comes"). A very simple approach could be to change the button from "Add" to "Next..." or "Continue" or "Generate Token".

Similarily, maybe give the download button on the following popup a label. There is more than enough room in the popup to show a "Download" label next to the icon:

![screenshot-2020-11-25-153640](https://user-images.githubusercontent.com/127499/100241509-0eeab600-2f34-11eb-9729-bbc0f1928eae.png)

**Comment by kgroschoff** [comment]
@cschieder wants to have a look first if the whole dialog could be improved

**Comment by cschieder** [comment]
Design concept with mini wizard
![Service Accounts1](https://user-images.githubusercontent.com/49145827/105500615-6bafe600-5cc3-11eb-94f4-808ca146cc59.png)
![Service Accounts2](https://user-images.githubusercontent.com/49145827/105500619-6c487c80-5cc3-11eb-9f18-87d32bc017f2.png)
