### ISSUE TITLE
Cannot meaningfully delete Tokens

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2802]
**What is the problem, where is it and why is it an issue?**
A token in itself is just a character blob. The token's _name_ is not included. Now suppose I want to revoke this token. The KKP Dashboard only gives me a list of names. But I don't know which token has what name.

![screenshot-2020-11-25-154654](https://user-images.githubusercontent.com/127499/100243331-072c1100-2f36-11eb-93e4-7dce9f479061.png)

**Suggest how to fix it, if possible**
Maybe it would be good if the dashboard shows the last N characters from the token (the _first_ N characters are all the same for all tokens, as they begin with a common prefix). This is IMHO still pretty secure, but makes managing tokens much easier.

**Comment by floreks** [comment]
This is basically the best practice not to reveal any part of the token once it is created. It is up to the user to give a meaningful name here. From the top of my mind, I remember that GitHub and Digitalocean are doing the exact same thing here. Github only allows seeing SHA256 calculated based on the token. I don't think however that it changes anything in this case.

**Comment by xrstf** [comment]
> It is up to the user to give a meaningful name here. 

Okay, please then revoke this token: `32u49823hfroqwjue0i23zt9q8dhq89br298rhwefcbhqüp09r48z23g7otbvwq9d08zh2q1tr5zbvqwdcp98qh7gt08243w7bfgh23ui5z238r7tz3q9r8z72rth9wqdug287t723` - I gave it a super good name in the dashboard. Please revoke this token now and tell me how you did it without using kubectl to find the token in the cluster and get its name ;-)

Giving it a name only helps in one direction, if someone tells you "please revoke token X". But not if you just find a token someone in your infrastructure config files and want to revoke it.

> Github only allows seeing SHA256 calculated based on the token.

That is already a start and better than not giving any hint as to the token's content.

**Comment by floreks** [comment]
I am not sure what is your use case here actually. Can you describe it?

My understanding is that it looks something like that:
1. User creates a token with name X
2. User copies the token and directly uses it somewhere
3. After some time user wants to i.e. revoke the token but does not remember the given name
