### ISSUE TITLE
Clarify/Remove liveness indicator for Service Account tokens

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2804]
**What is the problem, where is it and why is it an issue?**
![screenshot-2020-11-25-165930](https://user-images.githubusercontent.com/127499/100251959-a4d80e00-2f3f-11eb-9e72-26d4163e2dcd.png)
The dashboard does not explain what it means for a Service Account to be "active" (the green dots in the screenshot). I also cannot make it _not_ be active. SSH keys do not have an activity indicator, so I guess it would be possible to not have it for Service Accounts as well?

**Suggest how to fix it, if possible**
Just remove the indicator alltogether.

**Comment by cschieder** [comment]
Agreed, if this indicator does not actually indicate anything it should be removed.
