### ISSUE TITLE
Service account groups are not displayed

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#2827]
**What happened?**:
<img width="803" alt="Zrzut ekranu 2020-12-4 o 13 24 33" src="https://user-images.githubusercontent.com/2823399/101163605-21e83f00-3634-11eb-8880-12e2f65f7932.png">

After changing display to raw value locally:
<img width="604" alt="Zrzut ekranu 2020-12-4 o 13 26 17" src="https://user-images.githubusercontent.com/2823399/101163731-4e9c5680-3634-11eb-9441-5f6258ab5c94.png">

**What should happen?**:
Groups like editors and viewers should be listed.

**How to reproduce?**:
Go to service account view and add new service account.

**Environment**
- UI Version:
- API Version:
- Domain:
  - [ ] run
  - [ ] run-2
  - [x] dev
  - [x] locally
- Others:

**Comment by kgroschoff** [comment]
Copy of https://github.com/kubermatic/dashboard/issues/2803 (or vice versa)

**Comment by floreks** [comment]
Yep, we can close as a duplicate.

/close
