### ISSUE TITLE
Improve event handling after user input

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/dashboard#2837]
As a user, I want prominently displayed events when I did not achieve my goal, so that adapting to the situation becomes effortless.

**What is the problem, where is it and why is it an issue?**
Create a cluster on hetzner cloud with limited quota available. Different event logs where shown, but I had to scroll down and extend the events in order to see what happened. 

The information displayed was helpful and correct.

**Suggest how to fix it, if possible**
If events occur, events should be displayed prominently within in users view so that he does not need to scroll / search for the information. This is especially important if he just initiated some action.

**Comment by cschieder** [comment]
Fixed by #2780 as the tabs reduce scrolling & visual overlad and show events by default
