### ISSUE TITLE
Notification popups fail to escape HTML

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2871]
**What happened?**:
I created an SSH key named `<u>test</u>`. The popup notification I got about its successful creation showed that the HTML was not escaped properly.

![2020-12-11 13_39_35-](https://user-images.githubusercontent.com/127499/101904605-6042a880-3bb6-11eb-8e41-ffec63b1d9c9.png)

**What should happen?**:
HTML should have been escaped.

**How to reproduce?**:
See above.

**Environment**
- UI Version: latest
- API Version: latest
- Domain: other
- Others: none

**Comment by maciaszczykm** [comment]
The designs do not include bold fonts etc. I'll remove the possibility to use HTML inside at all.
