### ISSUE TITLE
Allow keyboard navigation in forms

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2879]
**What is the problem, where is it and why is it an issue?**
When I try to create a new project, I intuitively enter the name into the popup:

![screenshot-2020-12-15-180741](https://user-images.githubusercontent.com/127499/102247703-9195de00-3f00-11eb-9f03-fc3c27cb83a6.png)

... and then i press **[ENTER]** on my keyboard and _nothing happens_. :-(

**Suggest how to fix it, if possible**
Some oldschool bois like me are used to web forms treating [ENTER] as "submit the form now". Would be cool if KKP dashboard could treat it the same.

**Comment by floreks** [comment]
Mostly done I guess in the related PR. If there will be a place found without such support we should open a dedicated issue.

/close
