### ISSUE TITLE
Design autocompletion data loading

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#2933]
**What do you want a draft of?** Design of an input field that has autocompletion data that is loaded async. User is able to use it without data, but with data he can choose from multiple options. See: https://github.com/kubermatic/dashboard/pull/2909

<img width="1007" alt="Zrzut ekranu 2021-01-13 o 14 46 12" src="https://user-images.githubusercontent.com/2823399/104460247-20545400-55ae-11eb-9114-46ca1bbf24b7.png">

**Technical outline, functionality** Any kind of progress bar, spinner would be good here. Contact me for more information.

**Comment by kgroschoff** [comment]
That would actually have been my comment in the pr 👍

**Comment by maciaszczykm** [comment]
Let's also add some indicator that there is no data available (see: https://github.com/kubermatic/dashboard/pull/2936#pullrequestreview-571011679).

**Comment by maciaszczykm** [comment]
We could display some spinner in the panel after clicking input. After the data will be loaded we can switch this to options or to text that no data is available.

The second idea is to put it in the right part of the input as a smaller spinner that will disappear once the data will be loaded. If there is no data there would be no additional behavior needed I think.

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/107947102-3466e900-6f92-11eb-9733-e59004402847.png)


I like the middle options the most, wdyt?

**Comment by maciaszczykm** [comment]
I like the middle ones too.

**Comment by maciaszczykm** [comment]
I'll take over and implement it.

/assign
