### ISSUE TITLE
Pre-fill Openstack image textbox with latest available image for the selected OS

### ISSUE THREAD

**Issue by multi-io** [kubermatic/dashboard#3024]
**What would you like to be added? / User Story**:

This is a feature that we have in our fork and would like to bring upstream.

For the Openstack image field in the cluster creation wizard and the node deployment editor, the user has to look up and enter the desired image name manually. What we want to do instead is fill this field with the latest image matching the selected OS version.

![image](https://user-images.githubusercontent.com/283179/106230187-39d0df00-61ef-11eb-966c-201e0c28118c.png)

For an existing node deployment we also notify the user when a newer image is available for the selected OS:

![image](https://user-images.githubusercontent.com/283179/106230411-b663bd80-61ef-11eb-88c7-80c0d21aad62.png)

The way this works is that we provide a simple additional API endpoint (actually two, one with and one without credentials) for getting the list of all Openstack images, and then the dashboard looks at (string-valued) [image properties](https://docs.openstack.org/glance/latest/admin/useful-image-properties.html) to determine which OS an image belongs to, and the image creation time to see which one is the newest. If no image is found for the selected OS, we fall back to the images from the node datacenter spec (`dc.spec.openstack.images`). There's also a regexp that we match against the image name the user set (this is still a normal text field, so the user can still manually enter any image name) so that if they uploaded a custom image named something like "my image" and are using that, we just disable the whole update check functionality. We also disable it if Flatcar was selected and automatic updates enabled.

To bring this upstream, I'd propose we extend the UI configuration file a little so that you can specify the above values -- the image name regexp, and possibly the Openstack image property name and values to check to see what OS an image belongs to (or do we actually want these settings in the node datacenter spec instead?). There should also be a boolean flag to just disable the whole feature altogether.

**Comment by csengerszabo** [comment]
Internal reference: 9092

**Comment by dakraus** [comment]
Just a quick note: The issue describes more functionality than actually requested in 9092. It would be sufficient if it were possible to:
* Fetch all project-specific Openstack images
* Include the Openstack image defined in the Seed data center
* Display the list of images as drop-down

**Comment by KhizerRehan** [comment]
[Internal: Slack Ref](https://kubermatic.slack.com/archives/C08PNJ0R8F3/p1782126749463049)
