### ISSUE TITLE
Increase speed of tab animation

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3061]
On cluster page when switching between e. g. Events and RBAC the line moves a bit slow, please speed it up a bit

**Comment by floreks** [comment]
Check available options at [stackblitz](https://stackblitz.com/edit/angular-tazct8?file=src%2Fstyles.scss).

**Comment by cschieder** [comment]
Thanks. Is "Faster ink bar animation" with no animation on the content possible? If not then no animation at all imo

**Comment by floreks** [comment]
Sure. We can do that.
