### ISSUE TITLE
Cluster name restrictions differ depending on the view

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#3066]
**What happened?**:
I tried to rename a cluster into `conformance-1.17`, which was previously given a random name. To my surprise, the dashboard rejected the new name:

![screenshot-2021-02-11-130617](https://user-images.githubusercontent.com/127499/107634578-0a4bb900-6c6a-11eb-980c-0766d2b15f2f.png)

Even though during creation, dots are happily accepted:

![screenshot-2021-02-11-130541](https://user-images.githubusercontent.com/127499/107634599-120b5d80-6c6a-11eb-91e4-3fd7ed537e34.png)

**What should happen?**:
I should have been able to rename the cluster.

**How to reproduce?**:
1. Create a cluster named "foo"
2. In the cluster view, try to edit it and rename it to "foo.bar".

**Environment**
- UI Version: v2.17.0-dev-g18ad06c4
- API Version: v2.17.0-dev-g18ad06c4
- Domain: dev
- Others: Firefox on Ubuntu

**Comment by kgroschoff** [comment]
mentioned PR solved the issue
