### ISSUE TITLE
Integrate custom UI

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/dashboard#3116]
Professionel Services ask us to help out integrate a customer's Corporate Identity into their KKP environment. 

https://drive.google.com/drive/folders/10VQMhzbEEggdLk_7SrRDz83hIp-nJD9b

**Comment by maciaszczykm** [comment]
What should we do in that matter? Prepare a branch with customized UI?

Is the logo the only change?

**Comment by maciaszczykm** [comment]
Closing it. We should consider https://github.com/kubermatic/dashboard/issues/3172 as an improvement in case of similar work to be done in the future.
