### ISSUE TITLE
Support CCM/CSI migration in Kubermatic Dashboard

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/dashboard#3159]
**What would you like to be added? / User Story**:

In order to provide KKP end users the possibility of migrating their clusters from in-tree cloud provider to external CCM/CSI we need to add this feature to the dashboard.

**Comment by maciaszczykm** [comment]
Linking last API changes for convenience: https://github.com/kubermatic/kubermatic/pull/7353
