### ISSUE TITLE
Prepare workflow and pipeline for handling private code changes

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#3172]
**What would you like to be added? / User Story**: Sometimes we prepare code changes that should be kept private. It would be good to be able to store them in branches to have version history and be able to work on them together. Second important thing is being able to prepare containers with code changes included. We should consider a private fork of this repo as an solution.

**Comment by lsviben** [comment]
Needs discussion and research

**Comment by zreigz** [comment]
cc @shaase-ctrl we need some input from you 
It can be a good topic for the sig-chairs meeting.
