### ISSUE TITLE
Card-View sometimes broken in KKP-ee v2.15

### ISSUE THREAD

**Issue by cedi** [kubermatic/dashboard#3271]
**What happened?**:
Sometimes the card-view shows some UI glitches like this one:
![2021-04-22-123542_701x248_scrot](https://user-images.githubusercontent.com/1952599/115701044-a3ccd080-a367-11eb-8e42-e16648d08460.png)

**What should happen?**:
Carda are either resized or the cluster name is truncated so it does not line-break anymore

**Environment**
- UI Version: 2.15.11

**Comment by maciaszczykm** [comment]
We have to fix the method that is handling longer project names. It's causing the issue. I'd like to avoid resizing cards because all of them should have the same size.
