### ISSUE TITLE
Reduce length of imports

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#3301]
In a lot of places we're already using a shorter form for imports, but there are a lot of files left, that are following the whole tree.
Use e.g. `@core/services/cluster/service` to import the cluster service instead of e.g. `../../../core/services/cluster/service` wherever possible.

**Comment by maciaszczykm** [comment]
It would be also cool if there would be a check for that if that is possible.

**Comment by floreks** [comment]
I am not sure if there is such a check available. Those imports are configured inside `tsconfig.json` so this is quite a high-level configuration.

**Comment by maciaszczykm** [comment]
Yep, anyways, shortening imports is a good idea.
