### ISSUE TITLE
Changelog Design Update

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3310]
Continuation of discussion of #3291 fyi @floreks 
Thanks for giving me the full list :) I don't like the idea of the user feeling danger when they look at our changelog so I tried to tone down the warning colors while still grabbing attention, additionally I would prefer exclusively using red for errors, or things that need immediate attention before they explode.

(above: current state, below: my suggested colors. I can write you the hexcodes or link you to figma if you agree to those colors)
![image](https://user-images.githubusercontent.com/49145827/116410926-856a4780-a835-11eb-8c3d-d08ac0398232.png)

Actually, to ensure the attention without the red, we can work more with the order of the points, maybe like this?

1. Action Required
2. Security
3. Fixed
4. Added
5. Changed
6. Deprecated
7. Removed

For the spinner, would it be possible (and not too much effort) to make it push the full changelog button to the side with a mini animation? That way we could have them both grouped to the right side. My reasoning for wanting it on the right side is that we usually keep "negative" actions to the left side, i. e. deleting or going back, and "positive" actions that lead you further on the right side, so I would like to continue that pattern.

And last but not least, we don't have an x to close the dialogue, I think we should add one, behavior should either be the same as clicking "got it" or just close the dialoge, but make it come back the next times until the user clicks "got it"

**Comment by maciaszczykm** [comment]
+1 for the new colors. I think "fixed" is mostly green in many places and "removed" gray, so it makes sense to change IMO.

**Comment by maciaszczykm** [comment]
> For the spinner, would it be possible (and not too much effort) to make it push the full changelog button to the side with a mini animation?
Should be doable. It's hard to estimate the effort without taking a closer look though. I'd say we will do if it will not take too much time.

**Comment by floreks** [comment]
@cschieder could you give us color codes or link to figma for the new design?
