### ISSUE TITLE
Update supported OS for GCP provider

### ISSUE THREAD

**Issue by zreigz** [kubermatic/dashboard#3323]
According to the source code: https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/gce/config.go#L46
the GCP supports only Ubuntu OS. The Centos and Redhat must be removed from the the UI.

**Comment by moadqassem** [comment]
@zreigz But RHEL is supported in GCE

**Comment by maciaszczykm** [comment]
@moadqassem Thanks for verifying that. I'll remove just CentOS.
