### ISSUE TITLE
Integrate REGO playground with KKP Constraint Templates

### ISSUE THREAD

**Issue by lsviben** [kubermatic/dashboard#3343]
A client has asked for REGO autoformatting and highlighting in KKP. 
This is something that IDE`s usually provide: https://www.openpolicyagent.org/docs/latest/editor-and-ide-support/ .

From the browser side, the closest we can do is to somehow integrate the OPA playground(https://play.openpolicyagent.org/) with out UI. 

We need to think what we can do from our side, maybe just a button which opens the OPA playground page with the current REGO that is in the constraint Template? TBD

**Comment by ahmedwaleedmalik** [comment]
We are not going to invest more effort in OPA/REGO.
