### ISSUE TITLE
Redesign service account group picker

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#3376]
**What do you want a draft of?**
<img width="679" alt="Zrzut ekranu 2021-05-24 o 10 57 06" src="https://user-images.githubusercontent.com/2823399/119323289-d0ce1500-bc7e-11eb-9926-920380fbf48b.png">

<img width="674" alt="Zrzut ekranu 2021-05-24 o 10 49 05" src="https://user-images.githubusercontent.com/2823399/119323031-8cdb1000-bc7e-11eb-833b-9bff057e92c9.png">

I think we should make service account dialogs look similar to the member dialogs.

We can copy viewer and editor description but the new one will be needed for project manager.

@zreigz How would you describe it?

**Comment by zreigz** [comment]
Manage projects, members, and service accounts. Can't access clusters

**Comment by zreigz** [comment]
Projects, members, and service accounts management. Not allowed to interact with clusters.
