### ISSUE TITLE
OPA Default Constraints UI 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3379]
Issue based on:
https://github.com/kubermatic/kubermatic/issues/6808#issue-848187785

### Design Draft
![image](https://user-images.githubusercontent.com/49145827/119470776-f3c4fb80-bd48-11eb-8cc2-a91ae2cbed04.png)
![image](https://user-images.githubusercontent.com/49145827/119471784-e5c3aa80-bd49-11eb-93da-5ec19dd1e376.png)
Do you need any other design for this from me?

On/Off info icon:
> Turning off a default constraint disables and hides the constraint for all the user clusters it is applied to.

### Discussion Points
- Does `Applies to` make sense? Do some constraints also apply to everything?  
- How severe is the turning off of a constraint? Do we need a warning modal?
- Is the term `Default Constraints` clear? Would something like `Global Constraints` or `Admin Constraints` be preferable? Other ideas?

**Comment by lsviben** [comment]
> 1. Does Applies to make sense? Do some constraints also apply to everything?

Applied to makes sense. Constraints with no selector apply to everything, we can use either `*` or `All` for those. 

> 2. How severe is the turning off of a constraint? Do we need a warning modal?

I think we should add a warning modal, turning off constraints could remove some security policies, so better to be sure.

> 3. Is the term Default Constraints clear? Would something like Global Constraints or Admin Constraints be preferable? Other ideas?

For now lets stick with Default Constraints unless somebody has a better idea. Global is also ok.
