### ISSUE TITLE
openstack: instanceReadyCheckPeriod and instanceReadyCheckTimeout are not defaulted in existing cluster

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/dashboard#3382]
**What happened?**:
#2781 introduced `instanceReadyCheckPeriod` and `instanceReadyCheckTimeout` defaults to openstack clusters. 
Unfortunately the defaulting only work in new cluster wizard. In existing cluster if one click on "Add Machine Deployment" the values equals to 0 and that prevents button "Add Machine Deployment" to be active (since 0 violated validation min=1).
 
![image](https://user-images.githubusercontent.com/30984/119657629-d2413e00-be34-11eb-97c7-7a79e91716b8.png)

**What should happen?**:
Defaults `instanceReadyCheckPeriod` and `instanceReadyCheckTimeout` should also affect "Add Machine Deployment" wizard in the existing clusters.

**How to reproduce?**:
In the existing openstack cluster try to "add machine deployment"

**Environment**
- UI Version: v2.17.0-dev-gfdcad12d Enterprise Edition
- API Version: `¯\_(ツ)_/¯`
- Domain: https://dev.kubermatic.io/

**Comment by maciaszczykm** [comment]
We should also verify if the validators are correct (`min=1`).
