### ISSUE TITLE
Refresh of tabs component

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#3391]
With the mla implementation I noticed, that the tabs component isn't refreshing correctly. 

Currently we use `*ngIf` on nearly every tab, to decide wheather it should be displayed or not. E.g. in Cluster Details the `OPA Constraints` + `OPA Gatekeeper Config` should only be displayed if OPA is enabled. This works, but once you edit the cluster via the edit cluster dialog and you enable OPA, you manually need to refresh the page to get the tabs. 
For MLA this doesn't even work, because for MLA there is an additional request to the seed dc, which needs some seconds. In this few seconds the tab component already has been rendered - without the `MLA Gatekeeper Config` tab, as it also only should be displayed when MLA is enabled on seed level + enabled MLA Options.

To make MLA work right now, there is a small workaround: 
`<km-tab-card [ngClass]="{'hideMLA': !isMLAEnabled()}">` (in cluster details component)
with following styling in the tab component `.hide-mla .mat-tab-label:last-child {  display: none;}`

This - in theory - could be added for all other tabs too, but it isn't looking good and it would be better to have a more generic way.

**Comment by maciaszczykm** [comment]
Fixed by https://github.com/kubermatic/dashboard/pull/3293/commits/31bff46519f7cbd05a0c52214cd6925e5231daca.
