### ISSUE TITLE
Add buttons + icon placement is broken 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3430]
![image](https://user-images.githubusercontent.com/49145827/121656436-c34ac480-ca9f-11eb-8504-bdb597cd8a88.png)
![image](https://user-images.githubusercontent.com/49145827/121656473-cd6cc300-ca9f-11eb-9336-79e4cfdab995.png)

**Comment by cschieder** [comment]
Sadly it's wrong in the other direction now
![image](https://user-images.githubusercontent.com/49145827/122071119-c4108d00-cdf6-11eb-97f9-773d6e86f942.png)
![image](https://user-images.githubusercontent.com/49145827/122071105-c1ae3300-cdf6-11eb-9202-4749d9e8c3da.png)

btw, would it be better to use a separate plus icon rather than rotating an X icon?

**Comment by maciaszczykm** [comment]
Separate plus icon could help a bit.
