### ISSUE TITLE
Redesign Admin Panel

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#3434]
Based on @cschieder design

https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=5163%3A319

![image](https://user-images.githubusercontent.com/2285385/121881058-06f73580-cd0f-11eb-9f43-49a6e1264e5f.png)

**Comment by cschieder** [comment]
please add 15 px to the sidebar item width with this issue, so that `OPA Constraint Templates` fits
