### ISSUE TITLE
Icons for custom links are not displayed

### ISSUE THREAD

**Issue by michalvanco** [kubermatic/dashboard#3435]
**What happened?**:
When using an "Icon" field for the custom link in the Admin panel (use Sidebar), the icon is not displayed. (Using the remote address of ".png" or ".svg" files).

<img width="247" alt="Screenshot 2021-06-14 at 14 56 51" src="https://user-images.githubusercontent.com/1215131/121897647-e507ae00-cd22-11eb-9b33-507b501e0ffb.png">

<img width="241" alt="Screenshot 2021-06-14 at 14 57 02" src="https://user-images.githubusercontent.com/1215131/121897676-e89b3500-cd22-11eb-95ad-c74b50693c3e.png">

**What should happen?**:
The icon should be rendered for the link. So that other than predefined icons can be used (https://github.com/kubermatic/dashboard/blob/master/src/app/shared/entity/settings.ts#L100)

**How to reproduce?**:
Grab any image URL and create a custom link - go back to the KKP dashboard and check the link (icon is not present)

**Environment**
- KKP 2.17.0

Thank you for the investigation!

**Comment by maciaszczykm** [comment]
It works when using footer as a location. Sidenav seems to be broken. It's probably some styling issues (icon color).
