### ISSUE TITLE
Project page improvements

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3443]
Can we make the search work on the owners as well? 

Also I think it might be nice to be able to sort by the cluster column, like how the Name or ID column sorts. Same with owner column. Actually would anything speak against making every column sortable? Might be better to have the option even if it's rarely used because it should be pretty little effort to implement and doesn't clutter the design. 

When going to a different page the column locations jump around a lot, my idea to fix it would be using percentages for each column. Ideally we make both the indicator and the edit icons a fixed width and then distribute the remaining percentages kind of like this: 

name	20
labels	20
id		15
clusters	10
role		15
owners	20

**Comment by maciaszczykm** [comment]
@cschieder Sort of the fields that are not saved in the structure (like clusters or owners) requires implementing custom sort method. That's why we do not implement it if it is not requested.

**Comment by maciaszczykm** [comment]
I can add sorting by number of clusters but I'll avoid adding it for owners and labels. These two are both arrays and using them as a sorting key seems wrong to me.
