### ISSUE TITLE
Redesign kubeadm instructions block

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#3449]
**What do you want a draft of?**
<img width="1597" alt="Zrzut ekranu 2021-06-18 o 11 04 41" src="https://user-images.githubusercontent.com/2823399/122536617-028b8f00-d025-11eb-8b2a-651087061746.png">

**Technical outline, functionality** Currently it looks messy. We should avoid using code block and use nicer design for that.

**Comment by cschieder** [comment]
Wdyt?
![Clusters_Overview-No-MachineDeployments](https://user-images.githubusercontent.com/49145827/124149826-40f76400-da91-11eb-9d5e-345a1500b154.png)
https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=5335%3A39061

**Comment by maciaszczykm** [comment]
Looks much better. Thanks.
