### ISSUE TITLE
Backup Destination management

### ISSUE THREAD

**Issue by lsviben** [kubermatic/dashboard#3549]
Currently we support only S3 client compatible backups, and we would like to extend this and allow users to choose and configure through the UI where the backups should go.

Needs research and proposal

**Comment by cschieder** [comment]
Please provide parameters (e. g. needed inputs, data we can show) for the design @lsviben

**Comment by kgroschoff** [comment]
## 1. Backup Buckets in Admin Settings
New: 
- seed can have multiple destinations (visualised by a "dropdown" table)
- destination has a name and exactly one bucket, endpoint + credentials
- bucket, endpoint + credentials still editable
- additional info in the table, if credentials are created or not
- destination name should **not** be editable
- destination can be deleted, but needs hint, that it might infect configured clusters 

**!Attention!** 
It needs to be possible to maintain currently configured buckets. They don't use the new structure with destinations.
A hint is needed, that it is depricated and will be removed in the future.

old structure
```go
// SeedBackupRestoreConfiguration are s3 settings used for backups and restores of user cluster etcds.
type SeedBackupRestoreConfiguration struct {
	// S3Endpoint is the S3 API endpoint to use for backup and restore. Defaults to s3.amazonaws.com.
	S3Endpoint string `json:"s3Endpoint,omitempty"`
	// S3BucketName is the S3 bucket name to use for backup and restore.
	S3BucketName string `json:"s3BucketName,omitempty"`
}
```

new structure
```go
// SeedBackupRestoreConfiguration are s3 settings used for backups and restores of user cluster etcds.
type SeedBackupRestoreConfiguration struct {
This conversation was marked as resolved by moadqassem
	// S3Endpoint is the S3 API endpoint to use for backup and restore. Defaults to s3.amazonaws.com.
	// Deprecated: - use the BackupDestinations for configuring backup destination
	S3Endpoint string `json:"s3Endpoint,omitempty"`
	// S3BucketName is the S3 bucket name to use for backup and restore. 
	// Deprecated: - use the BackupDestinations for configuring backup destination
	S3BucketName string `json:"s3BucketName,omitempty"`
	
	// BackupDestinations contains possible etcd backup destinations for this Seed 
	BackupDestinations map[string]*BackupDestination `json:"backupDestinations,omitempty"`
}
// BackupDestination holds the bucket and endpoint info for an etcd backup destination
type BackupDestinations struct {
	// BucketName is the name of the bucket in which the etcd backups will be stored
	BucketName string `json:"bucketName,omitempty"`
	// Endpoint is the endpoint through which to communicate with the storage provider
	Endpoint string `json:"endpoint,omitempty"`
}
```

## 2. etcd Backups in Project 
- dialogs need new dropdown field to choose a destination for a backup
- display seed (not editable), to avoid confusion
- display hint, if there are no destinations configured
