### ISSUE TITLE
User cluster monitoring/logging checkboxes issue

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#3556]
**What happened?**:
![bug](https://user-images.githubusercontent.com/2285385/127107568-0c675ce0-401e-431d-8a22-cb329372908b.gif)

**Comment by maciaszczykm** [comment]
At the moment the seed settings are loaded without putting mouse over the random or other button. It takes a second to load the data but it can be done only after datacenter is picked. I think it can be closed right now but I'd like to ask you @floreks for confirmation. Can you still reproduce it?

**Comment by maciaszczykm** [comment]
Confirmed.

/close
