### ISSUE TITLE
Change Container Linux to Flatcar

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/dashboard#3560]
**What is the problem, where is it and why is it an issue?**
From the OS selection we should change "Container Linux" to "Flatcar" or "Flatcar Container Linux".
We dropped support for CoreOS so if anybody will choose it then MC will throw errors and nodes won't come up.

**Suggest how to fix it, if possible**
Change Container Linux to Flatcar or Flatcar Container Linux.

**Comment by maciaszczykm** [comment]
> We dropped support for CoreOS so if anybody will choose it then MC will throw errors and nodes won't come up.

CoreOS was removed in https://github.com/kubermatic/dashboard/pull/3027.

**Comment by maciaszczykm** [comment]
CoreOS support was removed in #3027.
