### ISSUE TITLE
Integrate metering into KKP dashboard

### ISSUE THREAD

**Issue by simon-wessel** [kubermatic/dashboard#3564]
The information provided by the [metering](https://github.com/kubermatic/metering) tool should be accessible from the dashboard.

The metering tool collects data about the usage of user clusters (CPU, RAM, ...). This data shall be provided in the form of CSV file downloads. A list of reports (daily, weekly and/or monthly reports) should be shown to the user, who can choose to download them individually.

**Comment by maciaszczykm** [comment]
>The information provided by the metering tool should be accessible from the dashboard.

Is there any API for that?

**Comment by floreks** [comment]
Is it already integrated with our API?

**Comment by WeirdMachine** [comment]
The api is not done yet, but there will be 2 endpoints. One that lists reports and another one that creates a download link for a specific report. 

Any suggestion where i could add a flag about if this feature is enabled at all? Is there a specific endpoint already you use for this?

Something else we are missing?

**Comment by maciaszczykm** [comment]
> Any suggestion where i could add a flag about if this feature is enabled at all? Is there a specific endpoint already you use for this?

Will it be available globally or per-cluster?

**Comment by maciaszczykm** [comment]
> One that lists reports and another one that creates a download link for a specific report.

If generation is not too complex perhaps it can be put into one endpoint?

**Comment by cschieder** [comment]
Isn't this the same as #3589? should we close it?
