### ISSUE TITLE
Admin Settings OPA design follow up

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3583]
- [x] I think OPA should be under Presets in the sidebar
- [x] Distribute table content like this
 ![image](https://user-images.githubusercontent.com/49145827/127640093-b23fb2dd-65cc-4369-b618-3b55e4dbef8d.png)
20%, 20%, 14%, 26%, 10%, 10%

- [x] Bring tabs in the same line as button like this
 ![image](https://user-images.githubusercontent.com/49145827/127640632-ecf63925-2f9d-4e3a-bbad-2fc4d13ae3a8.png)
- [x] make active tab text medium weight
- [x] make grey line below tabs darker
- [x] left-align content of `Applies To` column
- [x] Remove headline in card (redundant)
- [ ] Truncate `applies to` column, add uncollapse/unfold functionality 
![image](https://user-images.githubusercontent.com/49145827/128006044-30360307-7238-4adb-b856-2e75c1926b26.png)

Question
- Is it better to write `All` instead of `*` ?
- Maybe we should have Default Constraints as the first tab rather than Templates? Opinions?

**Comment by kgroschoff** [comment]
>Is it better to write All instead of * ?
No strong opinion from my side :)

>Maybe we should have Default Constraints as the first tab rather than Templates? Opinions?
Since we need Constraint Templates for the creation of Constraints I think it is legit to place the Constraint Template tab before Default Constraints. 
On the other hand I'm not sure which tab users might use more often on a regular basis 🤔
