### ISSUE TITLE
Create a UI scheme for metering

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/dashboard#3589]
**User Story** 
As a user I would like to enable the metering tool in all seed cluster in the UI, so I don't have to enable it using the command line. 

**Acceptance Criteria**
- The admin panel has a new side bar option which would take the user to configure metering tool.
- The metering tool is disabled by default.
- There should be two types of input fields, the credentials and the configurations.
- The credentials are: bucket, accessKey, secretKey, endpoint all of type string 
- The configurations are: enabled(boolean), storageClassName(string), storageClassName(string).

For the API Calls, I will update the ticket once another PR will be merged.

**Comment by floreks** [comment]
Possibly should be EE only feature.

**Comment by shaase-ctrl** [comment]
We discussed this and it should be an EE feature.

**Comment by cschieder** [comment]
### Notes
- accessible by new data icon top right
- default sorting is by date/created with the most recent on top
- with this we will add a separator line + page name to header (in this case `Metering` or another name that's better for this, open for ideas - for the other pages `Admin Settings` and `Projects`) for the in-project level header we already have the projectname in that location, there we will only add the separator line 


### Ideas/to be added later maybe
- delete function
- maybe expiration 
- we could also add a column for file size? if this is in any way relevant? 



![Metering](https://user-images.githubusercontent.com/49145827/128710379-fd0dacb6-41db-4600-a639-7a84256734af.png)

**Comment by cschieder** [comment]
After some discussion in the sig/ui channel we will go forward with a new sidebar menu entry and a simple table in the admin panel
icon: https://drive.google.com/file/d/1bXsZPNsoSv9TO582LnQvoyl4zdIsrjVy/view?usp=sharing

**Comment by WeirdMachine** [comment]
@cschieder we want to implement the configuration of the metering tool in the UI as well. So we need a second page for this. I will provide some Options ASAP.

**Comment by cschieder** [comment]
If it's just another field we can simply add it to the dialog in the implementation, so it should be ready @floreks (iirc it was agreed that you take on this issue correct me if I'm wrong)

**Comment by floreks** [comment]
Unfortunately, I am still occupied with the backups UI. @kgroschoff would you be able to pick this up?

**Comment by kgroschoff** [comment]
Definitely not today, maybe tomorrow. Though not sure if that is enough time to finish, as I need to take a look into the topic first. 
Are the endpoints prepared for it?

**Comment by floreks** [comment]
There is one last API PR waiting to be merged: https://github.com/kubermatic/kubermatic/pull/7601

I might be able to pick it up tomorrow or the day after that also.

**Comment by kgroschoff** [comment]
I see. Then lets decide tomorrow who can pick it up and/or if we can split it up a bit, so we both can work on it and hopefully get it done until friday.
