### ISSUE TITLE
Rethink e2e Tests

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#3603]
**What would you like to cleanup?**:
Currently during the e2e tests, we create a usercluster for each provider. However we do not create a MachineDeployment, as we deemed that too expensive (in terms of runtime) and too flaky.

Without the MachineDeployments, the userclusters are pretty much identical, as stuff like the AWS credentials do not really influence for example the apiserver Deployment, or the machine-controller Deployment. So re-creating the "same" usercluster N times is wasteful and makes the tests more flaky than they need to be.

We could think about for example

* mock the API away entirely
* introduce a test-only "dry-run" flag at the end where the API doesn't actually create the cluster
* testing fewer things in CE if they were already tested in EE
* something else

**Comment by maciaszczykm** [comment]
We should investigate mock options that we have and pick something that's will be most convenient to use and to keep it up to date. Perhaps something that will work with swagger spec?

**Comment by maciaszczykm** [comment]
I've created an epic for E2E tests improvements: https://github.com/kubermatic/dashboard/issues/3711.

Feel free to open any issues for improvements that we can add. There is already a PR to turn off provider testing for CE version and WIP PR that will add mocks for the E2E. We will run full tests only in specific cases, not in every PR like now.
