### ISSUE TITLE
AWS spot instance max price should be float instead of integer  

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/dashboard#3613]
**User Story**
As a user I would like to assign a decimal number as the max price for my aws spot instance instead of providing only integers

**Acceptance Criteria**
- The field `Spot instance max price` should accept cents as well(float)

**Comment by floreks** [comment]
It is already supported.

### Initial Node step
![image](https://user-images.githubusercontent.com/2285385/129536140-d4099656-4642-40e2-bad9-fe54f23a644d.png)


### Summary
![image](https://user-images.githubusercontent.com/2285385/129536168-f57d1ea9-0317-4f8b-8658-ac1c6422d59b.png)


### Created MD edit
![image](https://user-images.githubusercontent.com/2285385/129536447-85189ecb-8acb-451f-a4b9-46bcf686476b.png)

/close

**Comment by moadqassem** [comment]
@floreks Yeah but then we have another issue which is having values which is less than zero

![Screenshot 2021-08-16 at 11 24 26](https://user-images.githubusercontent.com/4427629/129541739-df13aa63-4262-461f-b54c-9132f7a60e13.png)

**Comment by maciaszczykm** [comment]
@moadqassem I think it may be related to the separator. You have used `.` and @floreks used `,`.
