### ISSUE TITLE
NodeLocal DNS Cache configuration option

### ISSUE THREAD

**Issue by mlavacca** [kubermatic/dashboard#3681]
**What would you like to be added? / User Story**:
During the KKP v2.18 pre-release tests (https://github.com/kubermatic/kubermatic/issues/7730), the feature about the Local-DNS cache configuration has been tested. The API part to enable or disable has already been implemented, but the UI part, not yet. It should be possible to enable/disable such a feature via UI.

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 implemented this in https://github.com/kubermatic/dashboard/pull/4604
