### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#3692]
**What happened?**:

### Addons
Some icons look bad when inverted.
![install-addon](https://user-images.githubusercontent.com/2285385/133235607-2d82d134-9d2b-4e55-af6b-edf3eef4d85c.png)

Should the autoscaler addon have an icon?

### Swagger
Some fonts and other details are hard to read on the dark theme.
![swagger](https://user-images.githubusercontent.com/2285385/133236446-068539c0-e85d-47c2-87f0-c6b907467e0e.png)

![swagger #2](https://user-images.githubusercontent.com/2285385/133236451-9365ffaa-8140-4f66-9ed5-548960bc50a5.png)

**How to reproduce?**:
### Addons (dark theme)
1. Go to cluster details of a cluster with addons support
2. Open `Install Addons` dialog

### Swagger (dark theme)
1. Open Help Panel on the top bar
2. Click on `API Documentation`

**Environment**
- UI Version: master
- API Version: master
- Domain: `dev.kubermatic.io`
- Others: OS - Ubuntu 20.04

**Comment by cschieder** [comment]
Discussed logos of addons - we don't know which, if any, of them we ship out with KKP, we need to check

**Comment by maciaszczykm** [comment]
At the moment it is not done. We should go back to it once https://github.com/kubermatic/kubermatic/issues/5499 will be implemented.

**Comment by maciaszczykm** [comment]
Reopening for fixing Swagger visual issues.
