### ISSUE TITLE
Seed Bucket settings misinformation about default bucket endpoint

### ISSUE THREAD

**Issue by lsviben** [kubermatic/dashboard#3703]
When configuring Seed Bucket Configuration, the Endpoint field has the following info:
`If not specified default endpoint `s3.amazonaws.com` will be used.`

But this is not true, and if not set, the endpoint will be empty.

**Comment by floreks** [comment]
Few notes:
1. This is about the metering credentials settings
2. Currently endpoint is required by design and cannot be left empty, therefore there is no misinformation here
3. I am marking this as an enhancement since it was the design choice
