### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by Berndinox** [kubermatic/dashboard#3718]
Well, its absolutely great that there is an Dashboard.
However, ive started using kubermatic (KubeOne) today and i cant find any docs on how to use/install the Dashboard.

**Comment by maciaszczykm** [comment]
Hello @Berndinox, Kubermatic Dashboard can be only used with Kubermatic Kubernetes Platform as our [README](https://github.com/kubermatic/dashboard#readme) says. You can find more docs [here](https://docs.kubermatic.com/). You can use [Kubernetes Dashboard](https://github.com/kubernetes/dashboard) with KubeOne.

**Comment by maciaszczykm** [comment]
I'll close the issue. Let us know if there is still something that we can help you with.

**Comment by Berndinox** [comment]
Thanks for clarification! BR Bernd
