### ISSUE TITLE
Error message block the Next button during user cluster creation in Azure 

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/dashboard#3756]
**What happened?**:
I wanted to create a user cluster in azure without using the presets and use my own credentials. An error message kept showing up regarding RouteTableClient is not found that blocked the next button and the back button so I can't proceed with the cluster creation.

**What should happen?**:
The error message shouldn't appear since the there is no real error.

**How to reproduce?**:
- Create an azure user cluster in KKP 
- In the credentials step don't use the presets and enter the credentials manually 
- Choose a resource group
- The error message will keep showing up blocking you from pressing Next or Back

**Environment**
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by moadqassem** [comment]
![Screenshot 2021-10-07 at 10.36.48.png](https://images.zenhubusercontent.com/5d1b48338871121fe293f1ee/e1cc9f83-de56-4d9c-bfc5-388e5024915b)

**Comment by maciaszczykm** [comment]
The problem is that when autocomplete is used and user partly provides the value (i.e. "tes" when searching for "test") then the UI sends the request to the API with invalid value ("tes"). This can be improved by adding debounce time or making sure that requests will be done after focus is out of the input/clicking enter key.

**Comment by floreks** [comment]
@moadqassem can you provide more details about how to reproduce this?

I've been trying with the vault credentials and checked available resource groups and couldn't get this error. When I have provided an invalid resource group then the error notification appeared, but only once and for 5s. After that, there were no errors.
