### ISSUE TITLE
Sidebar/scrollbar issues

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#3850]
**What happened?**:
<img width="1201" alt="Zrzut ekranu 2021-11-12 o 11 23 30" src="https://user-images.githubusercontent.com/2823399/141451979-88f599ef-812c-4f7f-a582-e4c7fe36f4a3.png">

**What should happen?**:
Elements should be aligned.  Whole scrollbar should be visible.

**Comment by floreks** [comment]
@cschieder what do you think about having the footer always visible as a fixed position on the bottom of the screen?

![image](https://user-images.githubusercontent.com/2285385/142851677-67f0f91f-21e7-4199-9aae-247e81bd28bb.png)

![image](https://user-images.githubusercontent.com/2285385/142851713-183396cf-bf6c-4296-b558-8ff020092c04.png)

### Current dev
![image](https://user-images.githubusercontent.com/2285385/142852511-e9b5e482-8960-47bf-89d3-929a096d1103.png)

**Comment by cschieder** [comment]
@floreks I believe the information in the footer is not really of interest to the user and it brings no benefit to make it always visible - I would not make the footer fixed

**Comment by floreks** [comment]
A hacky workaround it is then :slightly_smiling_face: I will update it to keep it only a part of the content.
