### ISSUE TITLE
Sidebar collapses/expanded randomly all the time

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#3900]
**What happened?**:
I try to use the KKP Dashboard. But the sidebar is constantly moving without any indication _why_.

https://user-images.githubusercontent.com/127499/143466111-61deef5f-754c-4f3b-81b2-3cc154d1beaf.mp4

**What should happen?**:
The sidebar should stay collapsed until I either hover over it or click on it.

**How to reproduce?**:
I have no idea.

**Environment**
- UI Version: dev
- API Version: dev
- Domain: dev
- Others: Firefox

**Comment by xrstf** [comment]
Also, my brain is trained that the little arrow on the bottom left corner is the universal sign for "collapse sidebar" and not a navigation thing. I get super confused everytime I click and am suddenly on a different page. ^^

**Comment by xrstf** [comment]
Can reproduce in Chrome without any plugins. Behaviour is not as bad as in Firefox, but still there. Zoom factor is 100%, but window is not maximized in this case.

https://user-images.githubusercontent.com/127499/143556699-cb5aa96f-7b69-4716-87b9-5a4c6468c994.mp4

**Comment by floreks** [comment]
This is a bit different then. It happens when you click directly on the collapse/un-collapse icon now. Not randomly.

**Comment by xrstf** [comment]
But it immediately collapses again when I click the button. It's true that it's different behaviour than in Firefox, but still not consistent.

**Comment by xrstf** [comment]
This is Firefox on another device with *all addons disabled*. Zoom level is 100%, window is maximized on a 1440p resolution.

https://user-images.githubusercontent.com/127499/143567181-eefb8fa2-12ee-46b5-8022-e6e2e1cd4df5.mp4

**Comment by floreks** [comment]
@xrstf when it happens randomly could you check the `me` endpoint data? I am especially interested in the user object id/email. I am assuming that it might be receiving information from "2" users where the email is the same but the id is different.

**Comment by xrstf** [comment]
https://user-images.githubusercontent.com/127499/143583537-62d6d62e-bf41-4c6c-a024-b09d82864218.mp4

**Comment by floreks** [comment]
Any idea why there are 2 users with the same email but 2 completely different IDs? Is it different for every OIDC provider? The API here needs fixing first.

**Comment by xrstf** [comment]
Not my area of expertise, no idea how the API/UI/OIDC/Dex stores users ^^

**Comment by xrstf** [comment]
But also, why is this related to the websockets? Isn't the state of the sidebar completely client-side? What is stored on the server? I can't see an option for "always collapse" or so in my user settings.

**Comment by floreks** [comment]
I am not sure why and when it was added but the `sidenavCollapsed` entry is being stored as part of the user settings 😕. When you click on the icon sends the request with the new values and updates the user CRD. Since both PATCH and GET (websocket) use only email as a unique source of truth to distinguish users we have this weird situation 🙂. There are possibly more issues due to this, one being both user/admin settings do not always properly save the information. UI still shows the old value and you have to retry multiple times to actually change something.

This issue on the surface seems simple but will require quite some changes in the API to solve.

**Comment by xrstf** [comment]
Do we know why my Github user has 2 Users in KKP? That seems to be the underlying issue and can cause all sorts of problems, I guess. Is it just that our dev system is ... ancient and has accumulated cruft?

**Comment by floreks** [comment]
It is possible that it is just our dev env being super messy, however, I think that the underlying issue still exists. If we can't guarantee that there is only a single user CRD with the same email at all times, we'll end up having some issues.
