### ISSUE TITLE
No version number on dev

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#3902]
**What happened?**:
At some point, the Makefiles or something else here got broken, because now on dev it says just "g58f783c3" instead of "v2.19.0-dev+...".

**What should happen?**:
It should be a proper readable version.

**How to reproduce?**:
Open the dev dashboard. Look at the footer.

**Environment**
- UI Version: dev
- API Version: dev
- Domain: dev
- Others: N/A

**Comment by floreks** [comment]
It was actually done this way on purpose. 

Ref: https://github.com/kubermatic/dashboard/pull/3856

**Comment by cschieder** [comment]
I agree with @xrstf that these numbers mean nothing to those not in the know

**Comment by floreks** [comment]
@cschieder Keep in mind that this is only on our dev. Official releases will normally show the released version number.

**Comment by cschieder** [comment]
Okay good :)

**Comment by floreks** [comment]
Can we close as it was explained why is it this way on dev?
