### ISSUE TITLE
Support for customizing AllowedIPRange of NodePorts for the supporting cloud providers

### ISSUE THREAD

**Issue by mlavacca** [kubermatic/dashboard#3924]
**What would you like to be added? / User Story**:
https://github.com/kubermatic/kubermatic/pull/8327 Introduced the possibility to customize the IP addresses allowed to reach the open Nodeports. To do so, both the CRD and the API have been improved with a new field. Such a field should be customizable via UI, for the following providers:
* AWS
* GCP
* Azure
* Openstack

**Comment by floreks** [comment]
@mlavacca is there a reason why this is not defined directly on a provider node spec since it seems to be related to the nodes (machine deployments)?

**Comment by mlavacca** [comment]
@floreks The reason is that this option is cluster-wide, along with other cluster-wide options. Do you think it would suit better in the machine deployment resource?

**Comment by floreks** [comment]
@mlavacca is it then enforced upon all machine deployments that are part of the cluster?

**Comment by mlavacca** [comment]
> @mlavacca is it then enforced upon all machine deployments that are part of the cluster?

The option is related to cluster-wide traffic control resources (security groups, firewalls, etc.) not to nodes. For other fields, such as the security group itself, we used the same approach. Do you see any drawback in having it at a cluster level?

**Comment by floreks** [comment]
Would it make sense to keep it on the second step of the wizard then instead of the 3rd?

**Comment by mlavacca** [comment]
Yes, absolutely. I think it should be put on the 2nd step of the wizard, along with the cluster-wide settings.
