### ISSUE TITLE
Hide untouched (off) options in cluster create summary

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3927]
when creating a cluster the summary page tends to be very long, however the settings the user didn't touch are of little concern to him/her, hiding them would be an option - only showing the user stuff they actually entered/stuff that's active

Let me know what you think

**Comment by floreks** [comment]
I think that we could definitely do this and hide all boolean (false) properties.
![image](https://user-images.githubusercontent.com/2285385/145180586-daf55774-2796-4314-b72c-30d24b4ea019.png)

I'd however keep all the text/number properties as they provide important information about the created cluster even if the user did not directly touch them. Some of them are also autoselected (i.e. size).

**Comment by cschieder** [comment]
Sounds sensible to me, maybe we should still give the option to view this info (like the "show cluster template details" on the create clusters from template dialog)
