### ISSUE TITLE
Update KubeVirt creation wizard for UI

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/dashboard#3937]
We are in process of changing KubeVirt Settings to be more friendly and usable. 
A new diagram has been prepared that shows how a new form should look like:

![new UI.drawio.png](https://images.zenhubusercontent.com/5dc5412ea240680001cc35aa/17568a83-c360-4439-a481-d33ad5fc7b05)

Additionaly we prepared two new endpoints to list storage classes and virtual machine flavors from KubeVirt infrastructure clusters.
Those are:
* list virtual machine presets https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/v2/routes_v2.go#L3575-L3597 and https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/v2/routes_v2.go#L5168-L5188 (note that in the endpoint we don't use virtual machine preset name but virtual machine flavor, it's because we prepare for a new feature from KubeVirt)
* list storage classes https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/v2/routes_v2.go#L3599-L3621 and https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/v2/routes_v2.go#L5190-L5210

More details on the "Operating System" field, acceptable values are an http url or `namespace/name` format. For instance when user wants to clone a disk he should put a value `default/some-pvc-with-disk`, it always must be a pair of namespace with name.

**Comment by hdurand0710** [comment]
Additional needs for **VM affinity**
References: https://github.com/kubermatic/kubermatic/issues/8742


![VM affinity UI.drawio.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/fd275ee2-fafb-4e59-b5ed-4eeee6a83b39)
