### ISSUE TITLE
Display operating system logo in the machine deployment list?

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4031]
**What is the problem, where is it and why is it an issue?** It's not a problem but perhaps we should display operating system logo in the machine deployment list?

<img width="213" alt="Zrzut ekranu 2022-01-5 o 12 59 20" src="https://user-images.githubusercontent.com/2823399/148214348-1be55425-72da-420b-a238-1da9a9ff5b2d.png">

**Suggest how to fix it, if possible**

**Comment by cschieder** [comment]
I like it, I don't think anything speaks against it
