### ISSUE TITLE
Checked enabled/disabled checkboxes look identical

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#4039]
**What happened?**:
Text is slightly more gray'ish but otherwise, it is hard to say which one is enabled/disabled.

![enabled-checkbox](https://user-images.githubusercontent.com/2285385/148756560-fed57b4b-0ed5-4e5e-ae59-a04c31ae504c.png)

![disabled-checkbox](https://user-images.githubusercontent.com/2285385/148756572-0e733cc0-e136-4f92-ab44-29954c3495db.png)

**What should happen?**:
There should be a clear difference between enabled/disabled checkboxes.

PS. The issue does not apply to the unselected checkboxes.

**Environment**
- UI Version: DEV
- API Version: DEV
- Domain: DEV

**Comment by cschieder** [comment]
wdyt? 
![image](https://user-images.githubusercontent.com/49145827/149764926-2447786d-5e72-4389-ab54-3e2b2af6622a.png)

**Comment by maciaszczykm** [comment]
@cschieder What are the color values?

**Comment by cschieder** [comment]
`#CAD1D9` and `#7E868F` there's a good chance that we have both colors in use already but if we don't you can check if we use similar greys and use those instead
