### ISSUE TITLE
Project status colors

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4044]
**What is the problem, where is it and why is it an issue?** When we create project, it has "inactive" status which has red color. When we remove the project it has "terminating" status with orange color. This is a bit confusing, clusters in "deleting" state have red color.

**Suggest how to fix it, if possible** Rethink the status colors and align them globally.

**Comment by cschieder** [comment]
Hi, in general the colors from a design perspective should be like this
green - success/online
orange - attention/pending
red - warning/error
grey - inactive

**Comment by cschieder** [comment]
on this note we can do a pass to make these colors more colorblind friendly soon and make changes like the inactive being a circle/outline rather than a filled circle or the like
