### ISSUE TITLE
Install addon dialog looks strange

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#4050]
It is visible, especially when using the dark theme. Logos are not readable. Positioning is off. It could use some general redesign.

![image](https://user-images.githubusercontent.com/2285385/148938814-16b25040-dbd2-436c-a396-a1212621bd68.png)

![image](https://user-images.githubusercontent.com/2285385/148939077-21e47a3d-174b-4c9f-b8c9-a86836939ae7.png)

**Comment by cschieder** [comment]
I think we talked about the logos before in the dark theme issue #3692, and this was related kubermatic/kubermatic#5499, as for the rest it would look a lot better with more vertical spacing between textfields, we can also move the descriptions of the checkboxes to info icons

**Comment by cschieder** [comment]
covered by [Align Addon with new Application UI #4663](https://github.com/kubermatic/dashboard/issues/4663 )
