### ISSUE TITLE
Metering buttons labels

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#4056]
**What is the problem, where is it and why is it an issue?**
![screenshot-2022-01-12-143728](https://user-images.githubusercontent.com/127499/149150685-43ef2a49-40f1-41ef-b2ca-a9e93895f93e.png)

Maybe it's just me, but the label on the button makes me think "will another popup open? Where's the 'save' or 'OK' button?" The same happens for the "edit credentials" popup.

**Suggest how to fix it, if possible**
Rename those buttons to "Save changes" or similar. Ideally without the pencil icon.

**Comment by floreks** [comment]
I think this was intended and part of our design.

cc @cschieder

**Comment by cschieder** [comment]
Now that I look at it again I can definitely see the issue, is it only here? Maybe we can do `Save Metering Configuration` and `Save Credentials` ... Is it possible for us to change the `Configure Metering` Button (on the site, not the modal) to `Edit Metering Configuration` once there is already a config saved?

**Comment by maciaszczykm** [comment]
>Is it possible for us to change the Configure Metering Button (on the site, not the modal) to Edit Metering Configuration once there is already a config saved?

Yes, it would be possible.

However, what do you think about using single words in the dialog buttons? This seems to be clear already what will be saved when looking at the dialog.

**Comment by cschieder** [comment]
I think the redundancy doesn't harm us and it's more intuitive to read action+resource rather than just action especially considering we have so many different resources
