### ISSUE TITLE
Warning: The specified value "NaN" cannot be parsed, or is out of range

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#4058]
When opening the Admin Panel I immediately get a `The specified value "NaN" cannot be parsed, or is out of range` warning in the dev tools console. 
![nan](https://user-images.githubusercontent.com/19547196/149170943-ef7c9b24-911f-4bb5-9427-85496b5e1e27.PNG)

**Comment by floreks** [comment]
I thought I fixed this warning already. Well, maybe I didn't create a PR after all 😊. It comes from the number input component defaulting. I'll fix it.
