### ISSUE TITLE
Additional Cluster Info Improvements

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4061]
https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=6128%3A33408
![image](https://user-images.githubusercontent.com/49145827/149298344-ccaaf404-e541-4a07-9ede-9d4b12ece192.png)

Design approved, can be implemented, I don't think I have to describe it because we discussed it in the meeting.

Sascha sees SSH Key Agent more as a "Misc" thing, any opinions on that?

**Comment by floreks** [comment]
@cschieder @maciaszczykm what do we do about the `Container Runtime` and `External CCM` properties?

**Comment by cschieder** [comment]
@floreks we had decided to put them above the `additional details` cut off and we also thought we can maybe move the labels down

Now that I think on it again though I wonder if we should put `External CCM` to `Misc`? Afaik it's not something that's relevant most of the time... wdyt?
