### ISSUE TITLE
Possibility to hide os images

### ISSUE THREAD

**Issue by tplueer** [kubermatic/dashboard#4105]
As an kkp-admin it would like to have a possibility to hide certain os images from the selection menu so they cannot be used for machine deployments.

**Comment by csengerszabo** [comment]
@tplueer can you please give some more details about the use cases where this would help?

**Comment by tplueer** [comment]
We only provide support for Ubuntu images in our cloud. We have therefore only stored Ubuntu as a valid image in the seed configuration. Since a user cannot use other images like Redhat, CentOS or Flatcar Linux, I personally see no reason to display them during the provisioning process of a new cluster or when adding new machine deployments.

**Comment by SamuAlfageme** [comment]
This makes total sense to prevent users from being confused with options that enabled options that appear in UI but not really available to them.

I tried hacking the `{light, dark}.css` file append some to hide some styles that hide the OSs we don't support, but there's no **stable** selector to the toggle (it changes based on the previous choices of the user). Some fixed selectors for these could be a good compromise solution while something more reactive to the backend can be in place:

```css
mat-button-toggle#mat-button-toggle-centos, mat-button-toggle#mat-button-toggle-rhel {
    display: none !important;
}
```
