### ISSUE TITLE
Labels missing in Cluster Detail view?

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#4107]
**What is the problem, where is it and why is it an issue?**

On the cluster detail page, the provider and the SSH keys are not labelled, whereas everything else is. This looks ugly for people like me, who zoom in a bit, as the horizontal alignment gets disrupted by the seemingly out of place provider logo and the free floating, undescribed "No keys assigned".

![screenshot-2022-01-20-112154](https://user-images.githubusercontent.com/127499/150320374-862079ac-0c77-4e0b-8349-923ae6851a23.png)
![screenshot-2022-01-20-112206](https://user-images.githubusercontent.com/127499/150320378-6914ab98-4802-4bb4-a442-275a2057f9db.png)

**Suggest how to fix it, if possible**
Add labels to these 2 blocks like every other block (ID, Created, Seed, Region, ...).

I'm using Firefox on Ubuntu. Tested on dev.

**Comment by maciaszczykm** [comment]
@xrstf labels were moved to the additional cluster info section. See https://github.com/kubermatic/dashboard/issues/4061.

**Comment by floreks** [comment]
The only thing that is off is the not-aligned logo. It should be on the same level as ssh keys. Other parts were part of the design. @cschieder any remarks?

**Comment by floreks** [comment]
PS. Of course, it's the Firefox that has the display issues :slightly_smiling_face:. What's funny is that if you resize the browser and maximize it looks fine again...

**Comment by xrstf** [comment]
Why would there not be a label above the "No assigned keys"? Like what's the reason to say "put a label everywhere but NOT this one field!" ? ^^

**Comment by floreks** [comment]
> Why would there not be a label above the "No assigned keys"? Like what's the reason to say "put a label everywhere but NOT this one field!" ? ^^

I also prefer having even very obvious labels everywhere for consistency but it is what it is :man_shrugging:

**Comment by cschieder** [comment]
Reason was that we display both things differently from the rest, they also used to be the last items in the cluster details irrc, as such the lack of a label didn't stand out. For ssh keys we have a key icon that we also establish in the sidebar to represent ssh keys so writing shh key again felt a bit redundant. For providers we use their logo and I think that the logo is recognizable and stands alone and thus does not need a label. But I see the point for consistency. If you guys prefer it we can add the labels, please keep in mind that you would also need to check the cluster create summary as it doesn't have a label for SSH Keys either.
