### ISSUE TITLE
Cluster Event List - Improvements

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4116]
![image](https://user-images.githubusercontent.com/49145827/150487108-8df84692-5326-4b61-84cb-a1da48f19fd2.png)

Two points
1) when I last talked with @toschneck he told me how the grouping of the notifications is rather slow or sometimes doesn't seem to happen at all, then we have the same event in the list a few times
2) resource id and cluster should probably not have a line break

**Comment by floreks** [comment]
We do the additional grouping on the frontend side. IIRC Kubernetes does the grouping based on the count of the identical events and the timestamp (when they last occured). The grouping also happens only from time to time, it is not continuous.
