### ISSUE TITLE
Edit provider dialog informations are misplaced

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/dashboard#4159]
In the edit provider dialog the informations like provider icon and "hide upon creation" aren't aligned. Also the "Preset Name" field is no longer needed, as it is already in the description text.
Additionally the scrollbar isn't correctly placed.

![preset](https://user-images.githubusercontent.com/19547196/152953689-e8eb2f62-c491-47db-ae8c-87f6cafe603b.PNG)

**Comment by maciaszczykm** [comment]
Good point. I've fixed the preset name part in my Nutanix PR, but the rest needs adjustment too.
