### ISSUE TITLE
Add support for Nutanix categories

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4160]

**Comment by embik** [comment]
Important note: Nutanix categories have to exist before adding them to machines, it's not working exactly like tags. We should either have a little note on that in the UI or maybe even have autocompletion? Not sure.

**Comment by maciaszczykm** [comment]
If autocompletion is possible I think we should add it. Otherwise UX will not be great. Less hints we put in the UI the better. Will you take care of the API endpoint for that?

**Comment by embik** [comment]
I can, but IMHO it shouldn't be high priority to support additional categories. I'll raise a kubermatic/kubermatic issue for it though.
