### ISSUE TITLE
Backport Nutanix support to v2.19

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4184]
- [ ] https://github.com/kubermatic/dashboard/pull/4145 97fca05d95d5d0e0e8061ba18da2e5fae0ef93b3
- [ ] https://github.com/kubermatic/dashboard/pull/4179 610fb2e07bbafe457148d4afeede567864abb55e

**Comment by moadqassem** [comment]
Since the new KKP version is out soon(2.20) we can simply add support for nutanix in 2.20.
