### ISSUE TITLE
Block Enable OIDC Kubeconfig flag when FG not present

### ISSUE THREAD

**Issue by mlavacca** [kubermatic/dashboard#4193]
**What is the problem, where is it and why is it an issue?**
The `EnableOIDCKubeconfig` flag is settable in the UI at the following path: `admin panel > Interface > Enable OIDC Kubeconfig`; such a flag is stored in the `kubermaticSetting` CRD. When this option is enabled, and the user wants to download the kubeconfig for a specific cluster, the following path is used: "/api/v1/kubeconfig?cluster_id=xxx&project_id=yyy&user_id=zzz". To support such functionality, a Feature Gates must be set in the `kubermaticConfiguration` resource: `OIDCKubeCfgEndpoint`. If this Feature Gates isn't enabled, the path mentioned above isn't loaded in the router, leading to a 404 when trying to download the Kubeconfig.

**Suggest how to fix it, if possible**
The `admin panel > Interface > Enable OIDC Kubeconfig` flag shouldn't be settable if the FG `OIDCKubeCfgEndpoint`  isn't enabled .

**Comment by maciaszczykm** [comment]
This is not fixed yet @ahmedwaleedmalik.
