### ISSUE TITLE
Add Nutanix CSI Configuration during cluster creation

### ISSUE THREAD

**Issue by WeirdMachine** [kubermatic/dashboard#4213]
**What would you like to be added? / User Story**:
CSI configuration is required for new nutanix clusters and without a configured preset it is not possible to set those fields manually via the UI.

xref: https://github.com/kubermatic/kubermatic/pull/8865

csi configuration:
https://github.com/kubermatic/kubermatic/blob/master/pkg/apis/kubermatic/v1/cluster.go#L828

Acceptance criteria:

- Nutanix Cluster can be created without a preset

**Comment by maciaszczykm** [comment]
This needs to be added to the preset settings as well.

**Comment by maciaszczykm** [comment]
Can you explain the details of form a little bit more? 

```go
// NutanixCSIConfig contains credentials and the endpoint for the Nutanix Prism Element to which the CSI driver connects.
 type NutanixCSIConfig struct {
 	// Prism Element Username for csi driver
 	Username string `json:"username,omitempty"`

 	// Prism Element Password for csi driver
 	Password string `json:"password,omitempty"`

 	// Prism Element Endpoint to access Nutanix Prism Element for csi driver
 	Endpoint string `json:"endpoint"`

 	// Optional: Port to use when connecting to the Nutanix Prism Element endpoint (defaults to 9440)
 	// +optional
 	Port *int32 `json:"port,omitempty"`
 }
```

Considering the struct above there should be 4 additional fields. Should all of them be optional? How we should label them? Any other requirements?

**Comment by maciaszczykm** [comment]
@embik Not sure how we should handle this whole "Prism Element" part as it's optional but once you want to set it some of the fields are mandatory. Should we introduce some additional checkbox for that that will show/hide them?

cc @cschieder

**Comment by embik** [comment]
@maciaszczykm we don't really want it to be optional - it's kind of optional on the API layer to make sure we can still ship KKP 2.20 if the dashboard does not support it, but we want everyone using 2.20 and higher to set it up if possible. So the UI shouldnt treat it as optional, it will not be with 2.21 anyway.

**Comment by maciaszczykm** [comment]
Link: https://github.com/kubermatic/docs/pull/991
