### ISSUE TITLE
Unable to add provider tags using cluster creation wizard

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#4226]
**What happened?**:

Faced an error when trying to specify `provider tags` for a machine.

<img width="1800" alt="Screenshot 2022-02-28 at 10 01 30 AM" src="https://user-images.githubusercontent.com/18264334/155927028-186b0d1e-8c2a-4f22-bc5a-fbd22d416660.png">

**What should happen?**:

**How to reproduce?**:

- Select any cloud provider to create a cluster
- In the `initial nodes` step, try specifying `Provider tags`

**Comment by floreks** [comment]
Tags are only available for nutanix/gcp/digitalocean and it works for both nutanix and digitalocean. GCP tags array was not initialized properly.
