### ISSUE TITLE
Extend GKE UI

### ISSUE THREAD

**Issue by zreigz** [kubermatic/dashboard#4247]
The epic is to extend external cluster view for:
 - [x] display GKE details 
https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/v2/external_cluster/gke.go#L673
 - [x] create MD 
POST /api/v2/projects/{project_id}/kubernetes/clusters/{cluster_id}/machinedeployments
https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/v2/external_cluster/gke.go#L513
 - [x] delete MD
DELETE /api/v2/projects/{project_id}/kubernetes/clusters/{cluster_id}/machinedeployments/{machinedeployment_id}
 - [x] create GKE cluster
POST /api/v2/projects/{project_id}/kubernetes/clusters

**Comment by Waseem826** [comment]
@imharshita @KhizerRehan are any of these tasks already covered in external cluster work?

**Comment by imharshita** [comment]
> @imharshita @KhizerRehan are any of these tasks already covered in external cluster work?

yes, all of them are already finished
