### ISSUE TITLE
Spot instance max price should be a required field

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#4256]
- Spot instance max price should be a required field
- Currently, if we don't specify a value and leave the field blank. `undefined` is being propagated as the value

**Comment by floreks** [comment]
It was fixed some time ago already by https://github.com/kubermatic/dashboard/pull/4223 and is working on dev.

/close

**Comment by ahmedwaleedmalik** [comment]
Cool, the changes are not rolled out on our testing environment then :)

**Comment by ahmedwaleedmalik** [comment]
It's on test env because it wasn't cherry-picked, which is something I'd expect to already have happened. Anyways please ensure that everything that is supposed to go to 2.20 is in the release branch!

**Comment by floreks** [comment]
We do cherry-pick if there is a clear request, but since there is no list of which fixes should get into the release, we are kind of walking blindly here. If there will be anything missing just let us know.
