### ISSUE TITLE
Increase osDiskSize for Azure when using RHEL

### ISSUE THREAD

**Issue by mlavacca** [kubermatic/dashboard#4259]
In Azure, when creating machineDeployments with RHEL as OS, the creation fails because the osDiskSize is too small: we use 30 GB as default, but Azure for RHEL requires at least 64 GB, as displayed in the error message below.

<img width="1052" alt="Screenshot 2022-03-04 092158" src="https://user-images.githubusercontent.com/44228100/156749343-dc7091c0-30d1-4321-9b63-9d4b7bc209c2.png">

The default disk size in Azure when using RHEL should be increased to (at least) 64 GB.

**Comment by floreks** [comment]
@moadqassem @mlavacca should we then make it 50 or 64 by default when RHEL is selected?

**Comment by mlavacca** [comment]
Azure says it should be 64, hence I personally would go with 64 GB.
