### ISSUE TITLE
Misalignments on machine deployments view

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4280]
<img width="404" alt="Zrzut ekranu 2022-03-8 o 13 08 13" src="https://user-images.githubusercontent.com/2823399/157235503-4f03aace-6042-416f-932c-5e68a92144da.png">
Should there be more space @cschieder?

<img width="368" alt="Zrzut ekranu 2022-03-8 o 13 08 04" src="https://user-images.githubusercontent.com/2823399/157235507-c7a247af-22fc-4287-a41e-7115f0e041aa.png">
The status icon is misaligned.

**Comment by cschieder** [comment]
Between the labels and the separator line? yes more space would be good. And good catch with the status icon
