### ISSUE TITLE
Update vSphere logo

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4311]
I think vSphere logo was updated some time ago, see https://docs.vmware.com/. 

~~I am not able to find any official page with resource though.~~ It requires login to access https://www.vmware.com/brand.html?ref=/brand/portal/guidelines/logo.html.

<img width="184" alt="Zrzut ekranu 2022-03-14 o 11 51 07" src="https://user-images.githubusercontent.com/2823399/158157830-35566561-1fe6-47ca-ae33-f4e89b4f9fbf.png">

**Comment by cschieder** [comment]
Hi, we do not have access to their branding materials so we have to make do with this for now
![vSphere](https://user-images.githubusercontent.com/49145827/158352369-0955209f-dc18-4283-9114-4a2194582661.png)
