### ISSUE TITLE
token-list is not displayed when receiving validation error

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/dashboard#4331]
**What happened?**:

KKP Admin has rotated their serviceAccountKey. As a result all current KKP serviceAccount tokens become invalid, which is expected. Normally in this case, users would then just re-generate their tokens in the UI and everything is fine again. 
However currently when we get a tokenValidationError from the BE, the FE will not render the list of tokens und just display a centralized error message `failed to get some service account tokens, please examine details field for more info` and `unable to create a token for xxxxx due to square/go-jose: error in cryptographic primitive`

As a result there is also no "regenerate token" button, which leaves users without any chance to resolve the situation by themselves.

**What should happen?**:

I think the best option would be list all of the tokens, but for every token we received the "unable to create a token" error from backend a little warning indicator is displayed. Maybe we also display the full message when hovering over the warning indicator.

![image](https://user-images.githubusercontent.com/20774623/158624179-c0422038-f16f-407c-96b6-9202f7406dd5.png)
(note: this is just food for thought, not based on any design best practices or anything :D)

What I think would be really important is to keep the "regenerate token" button on the right side. Because in case of rotating the `serviceAccountKey` then a user could simply click on "regenerate token" to solve their issues.

**How to reproduce?**:
1. Create ServiceAccount with a token
2. Switch `spec.auth.serviceAccountKey` in KubermaticConfiguration and re-run the kubermatic-installer
3. Go back to your serviceAccount and try to list its tokens

**What we can change in the BE to enable this in FE**

Currently we only return a list of errors from the backend on a validation error, but no information about the tokens themself (see https://github.com/kubermatic/kubermatic/blob/7abb9fd99bac5c5dd01e15232e48f2eefa25adc0/pkg/handler/v1/serviceaccount/token.go#L174). What I think we can do in the BE is return both the list of tokens as well as the list of errors instead. In this case then the FE would have all the data to create the list of tokens and then simply go through the errorlist and attach every error to the corresponding token in the table. 
cc: @zreigz who has worked on this initially

**Environment**
- UI Version: all
- API Version: all
- Domain: n.a
- Others:

**Comment by zreigz** [comment]
It's generally the API part. I have to distinguish between internal and authentication errors. It's possible to extend the API token to indicate the exact problem and display a warning instead of the error. 
I will create an issue for the API and discuss it with @maciaszczykm and @floreks

**Comment by judge-red** [comment]
Just to add, in case it wasn't clear - this is not limited to the UI. We need to be able to list the tokens over the API, even if they're expired, so we can write a simple script fetching the list of tokens and triggering the regeneration.

**Comment by zreigz** [comment]
yes, it will be like this
The API token object will have a new field `Invalidated` to indicate the faulty token
```
type PublicServiceAccountToken struct {
	ObjectMeta
	// Expiry is a timestamp representing the time when this token will expire.
	// swagger:strfmt date-time
	Expiry Time `json:"expiry,omitempty"`
	// Invalidated indicates if the token must be regenerated
	Invalidated bool `json:"invalidated,omitempty"`
}
```

The API will return the whole list of the tokens.

**Comment by zreigz** [comment]
@judge-red I have created already an issue for the API. The UI also will be adjusted.
