### ISSUE TITLE
UI should show some indication if etcd launcher is enabled/disabled

### ISSUE THREAD

**Issue by PratikDeoghare** [kubermatic/dashboard#4366]
**What is the problem, where is it and why is it an issue?**

UI should show if etcd-launcher is enabled or not. This is useful in debugging issues like #9345. Etcd-launcher is required for proper working of snapshot restore functionality. 

Ref: https://github.com/kubermatic/kubermatic/issues/9345

**Comment by maciaszczykm** [comment]
Is there any API endpoint returning this info?

**Comment by PratikDeoghare** [comment]
The information is in the feature gates. Exposing one more feature gate from here might work? https://github.com/kubermatic/kubermatic/blob/e75f355030cddb7e8ea66995a54397303ffb2e5f/pkg/handler/v2/routes_v2.go#L108

**Comment by maciaszczykm** [comment]
Yes, it should work then.
