### ISSUE TITLE
Support for configuring update window for flatcar nodes

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#4378]
**What would you like to be added? / User Story**

As a user, I'd like the ability to configure the update window for flatcar-update-operator using the dashboard.

**Acceptance criteria**

- It's possible to configure the update window 
- There should be some validation for the `start` and `length` fields in UpdateWindow.

**References**

- https://github.com/kubermatic/kubermatic/blob/master/pkg/apis/kubermatic/v1/cluster.go#L288
- https://github.com/flatcar-linux/flatcar-linux-update-operator/blob/master/doc/reboot-windows.md

**Comment by floreks** [comment]
API ref: https://github.com/kubermatic/kubermatic/blob/master/pkg/api/v1/types.go#L815
