### ISSUE TITLE
Add preset field and changed/deleted marker

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4380]
![image](https://user-images.githubusercontent.com/49145827/161262082-3756030f-6848-4d73-99dd-8296b7296837.png)
![image](https://user-images.githubusercontent.com/49145827/161262179-c2ffbc84-0c5b-47b2-99ae-c05a6d455841.png)

**Comment by Waseem826** [comment]
I think we no longer display "Provider Preset" on cluster details page.

**Comment by cschieder** [comment]
this is related to managing clusters via a link to their respective templates, it needs to be shown if that feature is implemented but I'm not sure on the state of that whole topic
