### ISSUE TITLE
Project Summary 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4383]
https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=6446%3A49393
![Clusters](https://user-images.githubusercontent.com/49145827/163332427-284f7f76-8beb-4f4c-a6a8-ecd30dd0a88d.png)

**Comment by maciaszczykm** [comment]
https://github.com/kubermatic/kubermatic/issues/9639 is done.
