### ISSUE TITLE
Admin Panel Seed Configurations

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4397]
[Design Draft, Admin Panel "Seed Configuration"](https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=6457%3A47599 )
![Admin Settings-Seed1](https://user-images.githubusercontent.com/49145827/162896358-177a9154-e9bc-46a8-b6ab-847fb953f361.png)
![Admin Settings-Seed2](https://user-images.githubusercontent.com/49145827/162896360-62c5bec1-7d9e-4644-8d63-0fc2637d7a40.png)

**Comment by ahmadhamzh** [comment]
waiting for https://app.zenhub.com/workspaces/work-in-progress---the-a-team-5fa971db111c0d0018ce0008/issues/kubermatic/kubermatic/9834

**Comment by cschieder** [comment]
blocked by kubermatic/kubermatic#9834

**Comment by pkprzekwas** [comment]
@cschieder , I think there is a slip on the first screenshot. Location column should be probably removed. Location is a property of data center, not seed. (cc @KhizerRehan)
