### ISSUE TITLE
External Cluster Creation UI

### ISSUE THREAD

**Issue by zreigz** [kubermatic/dashboard#4398]
Implement external cluster creation according to the design: https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=6516%3A47838

**Comment by cschieder** [comment]
I'd say full plane because it's more easily expandable

**Comment by ahmadhamzh** [comment]
i think this epic is duplicated from this one https://github.com/kubermatic/dashboard/issues/4564
so maybe it should be closed ?
@csengerszabo

**Comment by csengerszabo** [comment]
This is only about the UI, whilst the other one collects AKS, GKE, EKS cluster creation features, and both are sub-issues of #6414, so let's keep them
