### ISSUE TITLE
Empty State Project Card View

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4415]
![image](https://user-images.githubusercontent.com/49145827/164732570-e69938ba-b860-4a0c-8115-ab0b96992235.png)

Opacity of tiles: 
100 - 80 - 50 - 30

Alternative: 
no additional tiles, only the first tile with the "no projects available" and button is shown
![Projects_cards2](https://user-images.githubusercontent.com/49145827/164732984-3308fea2-1156-4614-adb8-e2f7d4de3ec6.png)

Alternative Alternative:
same thing but no button, just the card that says "no projects available."

**Comment by Waseem826** [comment]
I think instead of adding a tile we should add some empty placeholder in the center of page with a project icon and "Add Project" below that.

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/187208888-cbb40765-59ef-471b-9a8c-d031026a2636.png)
like this?

**Comment by Waseem826** [comment]
@cschieder yes. And we hide Action buttons on top (toggle, view switcher and create project button). Wdyt?

**Comment by cschieder** [comment]
Works for me
