### ISSUE TITLE
Add IPv6 subnet and IPv6 subnet pool boxes to OpenStack cluster wizard

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/dashboard#4469]
In case that dual-stack is enabled for an user cluster, OpenStack cluster wizard should include two additional input boxes (both optional) on the Settings page:

 - IPv6 subnet ID (so there would be two subnet ID boxes - IPv4 & IPv6, only IPv4 subnets should be listed in the IPv4 box and IPv6 subnets in the IPv6 box)
 - IPv6 subnet pool (API endpoint for listing subnet pools to be done in https://github.com/kubermatic/kubermatic/pull/9809): `/api/v2/providers/openstack/subnetpools`

These options should be visible only when dual-stack is selected in the previous steps.

![Screenshot 2022-06-09 at 10 29 37](https://user-images.githubusercontent.com/15926980/172803622-6298e6fa-a60c-4a94-97aa-b985e1b26d6c.png)

**Comment by Waseem826** [comment]
I think we're missing `/api/v2/projects/{project_id}/clusters/{cluster_id}/providers/openstack/subnetpools` endpoint if we want to show these new fields in Edit Machine Deployment dialog (i.e. after cluster is created).

**Comment by rastislavs** [comment]
> I think we're missing `/api/v2/projects/{project_id}/clusters/{cluster_id}/providers/openstack/subnetpools` endpoint if we want to show these new fields in Edit Machine Deployment dialog (i.e. after cluster is created).

@hbernardo Could you please take a look?

**Comment by hbernardo** [comment]
> I think we're missing `/api/v2/projects/{project_id}/clusters/{cluster_id}/providers/openstack/subnetpools` endpoint if we want to show these new fields in Edit Machine Deployment dialog (i.e. after cluster is created).

@Waseem826 the openstack subnetpools listing is not cluster specific and its endpoint was implemented here: https://github.com/kubermatic/kubermatic/pull/9809 (endpoint `/api/v2/providers/openstack/subnetpools` with optional querystring param `ip_version` (4 or 6))
You can also check the original issue here: https://github.com/kubermatic/kubermatic/issues/9788

Let me know if I didn't understand what you meant.

**Comment by rastislavs** [comment]
I think that for IPv6 subnet pools specifically, it should be OK to have that available only at cluster creation (not sure what would be the outcome of editing it in runtime anyway).
For IPv6 subnet, that should be same as IPv4 subnet is ATM.

**Comment by Waseem826** [comment]
Okay. If that's the case then we don't need other endpoint I think.
