### ISSUE TITLE
Fails to save cluster template when invalid cluster template name is provided

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4477]
### What happened
While trying to save a cluster template it doesn't show error info that 
**"Name can only contain alphanumeric characters and dashes (a-z, 0-9 and -). Must not start/end with dash.".** 
Providing invalid name fails to "Save" cluster template.

### Expected behavior.
It should save a cluster template and should be visible on _**/projects/<project-id>/clustertemplates**_ route

### How to reproduce

- Create new cluster fill up complete info
- Navigate to last step before saving cluster
- Click on Save Cluster Template
- Provide invalid name to Cluster and try to save template

https://user-images.githubusercontent.com/17727069/168526412-4636a8ef-6a53-4471-bc15-652f27cde840.mp4

### Environment
- UI Version: [v2.20.1](https://github.com/kubermatic/dashboard/releases/tag/v2.20.1)

### Current workaround
- provide name in lower which satisfies this "(a-z, 0-9 and -)." condition

**Comment by maciaszczykm** [comment]
Simple regex validation on the frontend side should enhance the UX enough.
