### ISSUE TITLE
disable "Dynamic kubelet config" option for nodes for Kubernetes 1.24+

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#4480]
**What would you like to cleanup?**:
Kubernetes 1.24 and higher does not support dynamic kubelet configuration. Since 1.24 just landed on KKP master, it would be great if the "dynamic kubelet configuration" option in the "initial nodes" step (and potentially in other places? not sure) could be hidden if 1.24 or higher has been selected in the previous step.

**Comment by embik** [comment]
@ahmadhamzh I think we also need a change in the dashboard that validates upgrades to 1.24 and blocks them if dynamic kubelet config is still enabled. Could that be part of this PR or should I raise another ticket?

**Comment by ahmadhamzh** [comment]
you mean like if there is any node using dynamic kubelet config block the upgrades to 1.24,right ?
@embik

**Comment by embik** [comment]
Exactly. Thanks! A little notice should probably recommend disabling it before the upgrade or something. Maybe we should ask @cschieder what the best upgrade flow should be from an UX perspective.

**Comment by cschieder** [comment]
How about we disable the option in create and add the mouse-over `Kubernetes version 1.24 and higher do not support dynamic kubelet configuration.` That way users are not surprised that it's "gone" - we can fully hide it after a while? 

As for the warning, two options we can disable the "Change Version" button in the dialog and show the warning `Kubernetes version 1.24 and higher do not support dynamic kubelet configuration. Disable dynamic kubelet configuration before upgrading to 1.24. Machine deployments with dynamic kubelet configuration enabled: [MD-name1], [MD-name2]` 

Or we don't block it but show the warning anyway
`Kubernetes version 1.24 and higher do not support dynamic kubelet configuration. On upgrade, dynamic kubelet configuration is going to be disabled on the following machine deployments: [MD-name1], [MD-name2]`

The second is easier for the user, the first would potentially be a huge hassle if there's multiple MDs and the user has to manually disable them all before being able to upgrade.

**Comment by ahmadhamzh** [comment]
i also think the second is better but im not sure do we need to like change all the existing nodes data to have the value for dynamicConfig  to be false or leave it as it is wouldn't make problem 
and i also agree with disable the check box for the dynamicConfig instead of hide it

**Comment by embik** [comment]
We're blocking the dynamicConfig=true setting on the API level for Kubernetes 1.24 and higher so that people cannot create clusters with it when not using the UI, so I think we should change the existing nodes when doing the upgrade. But since we need to update that to change the k8s version to 1.24.0, we should roll that into one API request if we can, I think.

**Comment by cschieder** [comment]
how about this - remove `following` from the sentence so it's shorter, align the warning symbol with the first line and change text-size to 14px, also remove the [] around the MD names (I used the [] to show that it's a variable, sorry that it was unclear) 
![image](https://user-images.githubusercontent.com/49145827/171384903-ca6337c4-276f-4947-bf14-ba5246f031c7.png)
