### ISSUE TITLE
Fails to load API Documentation from Help Panel in Navigation bar

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4485]
### What happened
Trying to open "API Documentation" from help panel in navigation bar. It fails to load documentation.

API seems to work `/api/swagger` but SwaggerUI module is not loaded.

**core.mjs:6500 ERROR TypeError: swagger_ui__WEBPACK_IMPORTED_MODULE_1__ is not a function**

### Expected behavior
It Should open Swagger API docs

### How to reproduce

- Open dashboard
- Click on Help menu icon in navigation bar
- Click on "Api Documentation" button

You will see empty page and error in console

https://user-images.githubusercontent.com/17727069/168964584-99a70c1f-687c-4a90-ab09-d8772ccf5362.mp4

### Environment

-UI Version: [v2.20.0](https://github.com/kubermatic/dashboard/releases/tag/v2.20.0)

**Comment by embik** [comment]
#4470

**Comment by maciaszczykm** [comment]
Closing as duplicate.
