### ISSUE TITLE
Cannot identify CNI icons

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#4486]
**What is the problem, where is it and why is it an issue?**
![screenshot-2022-05-18-124402](https://user-images.githubusercontent.com/127499/169021310-2be9aaa7-fa74-496b-ad1c-7e8c1ee02de9.png)

Without looking at the markup, it was impossible for me to figure out that the 2nd icon is for Cilium. Probably doesn't affect daywalker mode.

**Suggest how to fix it, if possible**
* Maybe add a tooltip?

**Comment by maciaszczykm** [comment]
@cschieder Can we get the Cilium logo in the dark version?

**Comment by cschieder** [comment]
I have provided this is the slack thread when it first came up, I will ping you

**Comment by cschieder** [comment]
Btw please fix the KubeVirt logo (appears very small in dark mode) too 
![image](https://user-images.githubusercontent.com/49145827/169961310-55222628-1734-4305-a8c3-4c7161c0a928.png)
