### ISSUE TITLE
Disabled text unreadable in dark mode

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#4487]
**What is the problem, where is it and why is it an issue?**
![screenshot-2022-05-18-125318](https://user-images.githubusercontent.com/127499/169022861-fd9ab1b9-263b-4000-a3ce-559bc1eebdad.png)

I cannot read the labels for those two checkboxes.

**Suggest how to fix it, if possible**
* Use a different color?

**Comment by maciaszczykm** [comment]
Normally the text stays the same when the checkbox is disabled. I think we should do the same here.

**Comment by KhizerRehan** [comment]
Hi, @maciaszczykm is it already fixed in some PR? i can see correct colors on master branch. can we closed this ticket than?

**Comment by maciaszczykm** [comment]
@xrstf can you confirm that it works for you? I think you were using Firefox, true?

**Comment by KhizerRehan** [comment]
@maciaszczykm

firebox output:

https://user-images.githubusercontent.com/17727069/171163895-c88f85e8-cabc-4860-8e15-f0c5ee9321cf.mp4

**Comment by maciaszczykm** [comment]
Okay, looks fine. If it will not work in some use case then it can be reopened.
