### ISSUE TITLE
UI design for automating full cleanup of clusters

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/dashboard#4491]

**Comment by cschieder** [comment]
Please elaborate on what the UI should show, general points from epic:
- User cluster admin can schedule a deletion of a cluster on the UI
- Project admin can schedule a deletion of a seed cluster on the UI


Questions to get discussion started
- Where should the function be available? in the normal delete dialog? will it be merged with this dialog or will there be two separate delete dialogs?
- How does the scheduling work? What text fields/parameters should be available?
