### ISSUE TITLE
Include of `.nvmrc` file in dashboard project

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4505]
**What would you like to be added? / User Story**:

IMHO, include the `.nvmrc` file in order to restrict user to use specific version of `node` in their local machine this will help in following reasons:

- Auto switching to specific node version when working **kubermatic** dashboard
- Installing of **node_modules** with correct node version (update of lock file too)
- Liniting use node version 

e.g Angular use https://github.com/angular/angular/blob/main/.nvmrc

**Comment by maciaszczykm** [comment]
@Waseem826 see: https://github.com/kubermatic/dashboard/blob/master/package.json#L10.

**Comment by maciaszczykm** [comment]
>Auto switching to specific node version when working kubermatic dashboard

That's the use case that our setup does not cover, so feel free to add it if it makes your setup easier.

**Comment by maciaszczykm** [comment]
Closing as done.
