### ISSUE TITLE
Hide clear icon in combobox for required fields

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#4506]
Hide clear (x) icon in combobox for required fields (also marked with *), since its also not possible to submit the form without these values and it also shows an error.
For example:

![screenshot-localhost_8000-2022.05.23-17_40_21.png](https://images.zenhubusercontent.com/6282091b4319605afd2869d7/dcc7df03-9b84-4e77-a6b0-79f3a3b3988d)

![screenshot-localhost_8000-2022.05.23-17_43_15.png](https://images.zenhubusercontent.com/6282091b4319605afd2869d7/d9295c77-5813-417a-9491-287d26725245)

**Comment by KhizerRehan** [comment]
IMHO, only `x` should be remove as `*` indicates it is **required** (from user point view) so at-least any entry should be selected. `x` is something that should be removed

**Comment by Waseem826** [comment]
Yes, only `x` should be removed. `*` was mentioned just to indicate that required fields are marked with `*`

**Comment by cschieder** [comment]
The x is technically not a bad thing, as it simply allows to clear a previously entered input, much like ctrl+a then delete, so the user can reenter something new.

**Comment by Waseem826** [comment]
Yes, but this is only for combobox and user can only select values from dropdown.

**Comment by Waseem826** [comment]
There are some use cases where this `x` icon cannot be removed so I'm going to close this issue.
