### ISSUE TITLE
 Provide option to keep Cluster page as the default landing page (rather than project overview)

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4510]
**What would you like to be added? / User Story**:

- [x]  Provide option to keep Cluster page as the default landing page (rather than project overview)
- [x] Show said option on the first opening of the Project overview

https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=6976%3A71594
![Clustersproject](https://user-images.githubusercontent.com/49145827/173524095-e38454c0-0e0b-42be-b205-e0cc9032837f.png)

**Comment by maciaszczykm** [comment]
Backend issue: https://github.com/kubermatic/kubermatic/issues/9915

**Comment by ahmadhamzh** [comment]
is there an envision according how the option will appear in the user setting and how the first message will be shown to the user  @cschieder

**Comment by cschieder** [comment]
I imagine it like this
![image](https://user-images.githubusercontent.com/49145827/173524189-3d4b5149-2002-4096-aeeb-07cd57ae60e6.png)
![image](https://user-images.githubusercontent.com/49145827/173524613-5bdfac51-6e46-4271-8582-2b52991b0980.png)
