### ISSUE TITLE
Add Placeholder Section to guide user

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4530]
**What is the problem, where is it and why is it an issue?**

**Case-1:** 
When user first time visits to KKP dashboard there is not Helpful indication or tip that indicates that in order to play around cluster you need to create a project.

- Not only it will help to have better UI but a smooth experience too that will help user instead of trial and test simply guide or a 1 step click from a placeholder image.

**Case-2:**
- User deletes all existing project this should again be visible to guide user.

**Current View** 
<img width="1440" alt="i1" src="https://user-images.githubusercontent.com/17727069/171797675-14c58772-9d08-4761-a630-487da1b64479.png">

**Suggest how to fix it, if possible**

**Desired View:** 

e.g reference example K8s Dashboard
![i1-ref](https://user-images.githubusercontent.com/17727069/171797710-0efe86c8-883c-427c-87ed-9ae13d35f6da.png)

**Comment by cschieder** [comment]
Let me know if this is what you had in mind https://github.com/kubermatic/dashboard/issues/4415

**Comment by cschieder** [comment]
@KhizerRehan please respond so that we can close one of the issues for redundancy

**Comment by KhizerRehan** [comment]
@cschieder yes `Empty State Project Card View` sgtm!
