### ISSUE TITLE
Show all project switcher - Add Spinner and disable toggle while pending

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4531]
**What is the problem, where is it and why is it an issue?**

**Issue-1**
Fetching all projects took more time as it was an API call which fetches all records and since it was less than 20 projects which took more ~3s and the time while projects were fetching User is clueless is some action is happening or not and this loading time will directly proportional to **No of project** .  It will be great to add **spinner** while some async stuff is going on at the Background to notify user something is going on and be **PATIENT**.

**Issue-2**
- User can be evil and it can trigger multiple API calls based on FAST switching of toggle

- On/Off -> On/Off -> On/Off -> it may be bad from UI point + Backend point that so many request are sent to backend IF (it is not handled from FE) side to cancel previous request but Still we should **disable** until the request response has come back

https://user-images.githubusercontent.com/17727069/171803049-5756790f-1a74-4638-a5ee-154792883d87.mp4

**Suggest how to fix it, if possible**

- Add spinner
- Disable toggle  or some better suggestions by chiara

**Comment by cschieder** [comment]
Spinner is definitely a good idea, if we disable the toggle while it's fetching (which makes sense) we need to show that as a message or maybe as tooltip on the switcher, if we disable something we need to make it easily visible that it's a) disabled and b) why it's disabled - especially if the disablement was triggered by an action on the user side and is not static
