### ISSUE TITLE
User Settings Page

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4532]
**What is the problem, where is it and why is it an issue?**

IMHO,  i think we might need to upgrade "User Settings" due to following reasons:

- Page seems visually different when coming from Project page where sidebar nav is visible or Admin Panel.
- Avoid Abrupt visual change from side panel to just a simple card.

- We should have both Buttons 
  - (Go Back -> to move 1 step back where we come from (Working fine)) 
  - Back to projects (Similar like sidenav) if user wants to switch project when staying on User settings page we no way to do right now. Instead 
   - clicking either logo (which most of users don't know) devs do.
   - Visually to show some button.
   
**Current View:**

<img width="1436" alt="i4" src="https://user-images.githubusercontent.com/17727069/171814427-5173c129-9b8b-46f0-ad92-cbbb57fe5c1d.png">

**Suggest how to fix it, if possible**

UI suggestions:

<img width="444" alt="i4-ref6" src="https://user-images.githubusercontent.com/17727069/171814341-ae321ade-3b79-4b6d-8877-7cd1e3d814cd.png">

---

**References examples:**

<img width="566" alt="i4-ref5" src="https://user-images.githubusercontent.com/17727069/171814483-e3bebb25-1f6f-4bf9-96be-d82cc1fcd07c.png">
<img width="484" alt="i4-ref3" src="https://user-images.githubusercontent.com/17727069/171814501-533f8809-b294-44c5-9c8d-4004133d48c3.png">
<img width="252" alt="i4-ref2" src="https://user-images.githubusercontent.com/17727069/171814509-c5b3bec4-7add-4436-bb84-3a891d3cfa98.png">
<img width="222" alt="i4-ref1" src="https://user-images.githubusercontent.com/17727069/171814514-c9e444fe-f7bb-4268-a044-8b9ed097c57c.png">

**Comment by Waseem826** [comment]
I think we don't have enough settings to show a side nav here. Also, most of the time you just want to quickly change some setting and then close the pop so having just "Go Back" button is enough.

**Comment by Waseem826** [comment]
@cschieder @KhizerRehan is this issue still valid or should we close it?

**Comment by cschieder** [comment]
I agree with @Waseem826 that there are not enough options to show a side nav, however I wrote down that I want to take a look if we can align the design of User Settings more with other pages of the UI. I don't have it set as high priority however. From my side we can close this issue, I will create a new one if I have something
