### ISSUE TITLE
Support for VMware Cloud Director as cloud provider

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#4536]
**What would you like to be added? / User Story**:
As a user, I would like to manage my Kubernetes clusters in VMware vCloud Director setup using the KKP dashboard.

`ubuntu` is the only supported operating system at the moment. Supported for other operating systems will be added soon against https://github.com/kubermatic/machine-controller/issues/1327. For now, it's fine to just allow `ubuntu`. Frontend support for remaining operating systems can be added in a separate ticket.

## References
- Initial support in API: https://github.com/kubermatic/kubermatic/pull/9933
- Additional API Endpoints for ease of use: https://github.com/kubermatic/kubermatic/pull/9982

**Comment by floreks** [comment]
I guess initial input should contain info that will also allow @cschieder to prepare the design first, i.e.:
- the high-level workflow (how should it work and what kind of fields are needed?)
- use cases (basic user-based workflows describing what to do with it)
- a general description of what this vCloud Director is? What is it used for? What problem does it solve?
- where would it be added? Is it wizard/cluster/settings or something else?

**Comment by ahmedwaleedmalik** [comment]
@floreks it's a cloud provider so I guess it should cover all the required use cases for cloud providers i.e. Presets, credentials, cluster settings, initial nodes, etc. 

For the fields, anything that is not `optional` in code should be a required field. But I'll try to add more details here :)

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 Updated the ticket description PTAL.
