### ISSUE TITLE
Fix layout for input parameters in API documentation(Swagger UI)

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#4544]
### What happened
![Kapture 2022-06-07 at 13 06 27](https://user-images.githubusercontent.com/18264334/172329505-b3e7119a-2da1-4bba-ac4f-9293b04e52d4.gif)

### Expected behavior
- Value should either be fully redacted with asterisks or we should show plain text.
- Text box should not be empty if some value is specified

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by maciaszczykm** [comment]
What we can improve is the styling (white on white). The rest is coming from Swagger UI 3rd party module that would need to be adjusted.
