### ISSUE TITLE
Better error notifications

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4545]
**What is the problem, where is it and why is it an issue?**
Can we have better error notifications, current ones are not readable.
for ex:
![err_notification](https://user-images.githubusercontent.com/78943096/172335445-fb27d872-7bc8-40f3-a04a-835422c181ce.png)

**Suggest how to fix it, if possible**
Can we have the displayed something like this:
![error_msg](https://user-images.githubusercontent.com/78943096/172335941-125495f6-67fe-4f5c-b0de-a3020201ab48.png)

**Comment by imharshita** [comment]
> Looks pretty odd, @cschieder do you think this is fine?

i agree!

**Comment by maciaszczykm** [comment]
This error is coming from the backend and it would be better to improve it there.

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/172387703-81580f9a-a7e6-4651-a543-73af91c8cbcf.png)
The design had an ! before, maybe we should change it back to that?

**Comment by imharshita** [comment]
An expand button for long errors would be a great addon too

**Comment by KhizerRehan** [comment]
Here are few examples which might be taken as reference:

<img width="290" alt="76b86fb52ab9555a5b3ff407a0f32206" src="https://user-images.githubusercontent.com/17727069/173042268-b7529d8d-0406-48a0-b32d-c02c95ff3748.png">

<img width="898" alt="b4c5ec1fb369c155598b2566562bfd2b" src="https://user-images.githubusercontent.com/17727069/173042277-4b163c75-2383-4cf4-8edf-76b88f1ffff7.png">

Lastly related to KKP dashboard this can be taken as a suggestion but as far design is considered chiara can definitely would have better idea.


https://user-images.githubusercontent.com/17727069/173042778-424d91be-f6aa-4dee-ad28-7db21ace3fc7.mp4
