### ISSUE TITLE
Kubeone MD page 

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4549]
### What happened
Kubeone MD page deosnt show nodes and no spacing between components

### Expected behavior
![kubeone_error](https://user-images.githubusercontent.com/78943096/172367264-38ef913e-e4ff-4256-80da-6a78eed1db9d.png)

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by maciaszczykm** [comment]
The view is broken because of some error, can you share logs from the browser console?

The steps to reproduce are missing. 

I thought that KubeOne is not supported yet (see: https://github.com/kubermatic/dashboard/issues/4446).

**Comment by cschieder** [comment]
@imharshita please check if this issue should stay or be closed, thank you

**Comment by Waseem826** [comment]
Fixed as part of https://github.com/kubermatic/dashboard/issues/5379
