### ISSUE TITLE
"Go back" button defunct on external cluster list

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#4550]
### What happened

![screenshot-2022-06-07-163232](https://user-images.githubusercontent.com/127499/172412377-0ab175f6-e185-4ebe-a5d7-14f2fe28c40a.png)

I opened this page and then tried to click on the Back button.

### Expected behavior

I should have gone back one page (my browser history wasn't empty).

### How to reproduce

* Log in to dashboard
* Open a project
* List the external clusters
* Open an external cluster
* Try to use that specific button.

### Environment
- UI Version: dev
- API Version: dev
- Domain: dev
- Others: Firefox on Linux

### Current workaround

* Use my browser's navigation features.

**Comment by maciaszczykm** [comment]
Fixed by @ahmadhamzh in https://github.com/kubermatic/dashboard/pull/4552.
