### ISSUE TITLE
Refactor Table Sort Logic

### ISSUE THREAD

**Issue by Talha-Jamil-TJ** [kubermatic/dashboard#4636]
**What would you like to cleanup?**:

##### Move sorting function inside `onSortChange()` to a common function

`const compare = (a: number | string, b: number | string, isAsc: boolean) => (a < b ? -1 : 1) * (isAsc ? 1 : -1);`

**Comment by Waseem826** [comment]
It would be helpful if you can add a bit more detail like component name, where its used etc.

**Comment by Talha-Jamil-TJ** [comment]
Using `sortingDataAccessor` is a better approach, so we won't need custom sorting, hence I'm closing this issue.
