### ISSUE TITLE
Align Addon with new Application UI 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4663]
Dependant on #4914
once #4914 is completed, Addons should be adjusted to look like the new Application UI 

Note: all KKP managed Addons will get a quality pass and should fullfill the conditions (optically uniform sizing, mark+text, works in darkmode, ...)

**Comment by Waseem826** [comment]
We can adjust size of logos it we want. However, some addons don't have any logo so it might look a bit inconsistent.

**Comment by cschieder** [comment]
I thought the addons are added on customer size and we have no control over logo sizes?

**Comment by Waseem826** [comment]
I'm not sure about that but we've just added `Addons are extensions provided by Kubermatic to expand cluster capabilities` description which states otherwise.
