### ISSUE TITLE
Project groups UI

### ISSUE THREAD

**Issue by lsviben** [kubermatic/dashboard#4670]
In the Project->Members section we need to divide the current Users and the new Groups into tabs (check Backups for examples).

The Groups tab will consist of a table (similar to users) with the group name, and the group Role.

Add a button "Add Group", same form as the "Add User"

**Comment by embik** [comment]
We should keep in mind this is an EE feature and probably shouldn't be shown (or disabled) for CE users.

**Comment by KhizerRehan** [comment]
- [API support for GroupProjectBinding resources #10265](https://github.com/kubermatic/kubermatic/pull/10265)
- [API endpoints for GroupProjectBinding resources #10303](https://github.com/kubermatic/kubermatic/pull/10303/files)
