### ISSUE TITLE
Improve dual-stack usability of GCP in KKP UI

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/dashboard#4679]
Notes:
- API part should be done before: https://app.zenhub.com/workspaces/work-in-progress---team-b-5fb24df6da2f6a001f678bb1/issues/kubermatic/kubermatic/10342
- Current UI behavior should remain the same if the user selects single-stack (i.e. IPv4) for cluster

When the user selects dual-stack (IPv4 and IPv6) network configuration:
![image.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/63bd4308-df81-4abb-a6f6-c8a090670ac1)

and a preset is chosen:
![image.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/1269a5d6-8f0f-484e-83bb-ad57abe9fbd9)

frontend should fetch the network (`/providers/gcp/networks`) and subnetworks (e.g. route `/providers/gcp/gcp-westeurope/subnetworks`) passing the preset name in the header `credential`, instead of using the header `serviceaccount` (note: current behavior should remain if user is using the service account field instead of the preset, i.e. using the header `serviceaccount`)

Also, frontend should:
- filter out subnetworks that don't match ~~cluster region (e.g. europe-west1) and~~ IP stack (dual-stack in that case). Backend will start returning IP stack information in the subnetworks endpoint.
- require network and subnetwork to be selected (i.e. disable "next" button if user didn't select network and subnetwork, or if subnetwork list is empty after filtering, or if networks or subnetworks endpoints fails for any reason)

**Comment by Waseem826** [comment]
- `region` in subnetworks is returned as a URL (e.g. `https://www.googleapis.com/compute/v1/projects/kubermatic-dev/regions/europe-west3`) but datacenter contains just region name (e.g. `europe-west3`). So do we parse that URL on frontend or can backend return just region name instead of URL?

- Should we require the user to select Network/Subnetwork even when Preset is selected?

**Comment by hbernardo** [comment]
> * `region` in subnetworks is returned as a URL (e.g. `https://www.googleapis.com/compute/v1/projects/kubermatic-dev/regions/europe-west3`) but datacenter contains just region name (e.g. `europe-west3`). So do we parse that URL on frontend or can backend return just region name instead of URL?
> * Should we require the user to select Network/Subnetwork even when Preset is selected?

- This is an old field, I think it's not a good idea to change it now, as other clients could be using it. Btw, I think the UI is already using it to filter out the subnetworks that are not in the same region (please confirm it).
- Yes, we should only for dual-stack. Because sometimes only the network (not the subnetwork) is set in the preset, so the user still needs to select the subnetwork as it's required for dual-stack.
