### ISSUE TITLE
fix alignment for label in the external cluster list 

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#4707]
**What is the problem, where is it and why is it an issue?**
if you go to Clusters ==> External Cluster tab then the list of the external cluster will shown, there is an alignment problem in the labels for each external cluster 

![Screenshot from 2022-07-21 15-55-47](https://user-images.githubusercontent.com/85109141/180218675-a30aaa2b-3735-426d-b0f5-da7aa459e35c.png)
![Screenshot from 2022-07-21 15-55-58](https://user-images.githubusercontent.com/85109141/180218683-44ffd8de-d07b-43e9-9172-72292eadddaa.png)

**Comment by imharshita** [comment]
@ahmadhamzh we can close this, right?
not able to reproduce the issue

**Comment by Talha-Jamil-TJ** [comment]
Looking fine on my end too @ahmadhamzh 
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/56511988/187167141-ad74c9e1-0853-443f-88ea-74b09df340ac.png">

**Comment by Waseem826** [comment]
@Talha-Jamil-TJ I think the issue on smaller screens only.

**Comment by Talha-Jamil-TJ** [comment]
@Waseem826 I see it now
<img width="694" alt="image" src="https://user-images.githubusercontent.com/56511988/187173489-07cf2983-e983-4bc3-9ea9-e8f255f35a70.png">
There doesn't seem to be enough space to place them horizontally, what should be done here?

cc: @cschieder

**Comment by Waseem826** [comment]
Adding small top and bottom padding in rows should be enough I think.

**Comment by imharshita** [comment]
this change will not be needed as we are anyway planning to remove labels form the list page, and add Region and Kubernetes Version.
https://github.com/kubermatic/dashboard/issues/4819

**Comment by cschieder** [comment]
What @Waseem826 proposed, for the future I'm also considering removing labels from the cluster table in general see #4819 
Harshita has made strong points that we can show more relevant data there instead
