### ISSUE TITLE
KubeVirt UI/UX improvements

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/dashboard#4715]
As a user I want to  easily choose an operating system without typing the address all the time. Additionally I want to stop passing kubeconfig as base64 encoded, I expect that field is secured if needed.

From @ahmedwaleedmalik, proposing improvements from https://github.com/kubermatic/dashboard/issues/4833 testing.

1. Shouldn't we expand the `Advanced Disk Configurations` by default? From a UI perspective, I think it's fine to always expand it, or I mean not have them collapsable at all.

![Screenshot 2022-08-24 at 12 23 15 PM](https://user-images.githubusercontent.com/18264334/186361197-d6423c1a-e9b7-4203-91b2-ae68eef1978b.png)

2. We should still show this info text after the user clicks on `Add local Disk` and we expand this form.

![Screenshot 2022-08-24 at 12 24 32 PM](https://user-images.githubusercontent.com/18264334/186361529-a64933a7-5844-4e5c-aa0b-957b7cecbaf2.png)
 
3. There is no validation for Disk Name. It should comply with lowercase RFC 1123.
![Screenshot 2022-08-24 at 12 26 09 PM](https://user-images.githubusercontent.com/18264334/186361772-e905876f-d306-4686-bb54-d87451453785.png)
 
4. Same issue as mentioned in point 3 with labels

![Screenshot 2022-08-24 at 12 29 09 PM](https://user-images.githubusercontent.com/18264334/186362494-704581c3-3b30-43e7-abd3-73908d4aafde.png)

**Comment by KhizerRehan** [comment]
Hi, @mfranczy 


https://user-images.githubusercontent.com/17727069/199424511-1a06f370-faf4-46d8-a159-6f3b09ed1b7b.mp4

As per PR i few points needs to discuss

- **Point-2 as per ticket** IMHO, it should be always in top when 'n' number of local disks are attached.

**Secondly**
Should we do same to display text always for Secondary text too? Which IMO should be as it gives info to end user just like me.

thoughts?


https://user-images.githubusercontent.com/17727069/199424952-300d8dd4-1074-4177-9dac-a215efe10d62.mp4


lastly, can you provide some valid values "comply with lowercase RFC 1123." currently acccording to regex i can see following values as valid values e.g OS URL

![valid-url](https://user-images.githubusercontent.com/17727069/199425449-8437fe43-9e4f-4573-8927-c3c9e6b9dd3f.png)

**Comment by mfranczy** [comment]
> Point-2 as per ticket IMHO, it should be always in top when 'n' number of local disks are attached.

I agree with that.

> Should we do same to display text always for Secondary text too?

Please don't. Leave it as it is. There is already a lot of information on the cluster page. It has been discussed in the past.

> lastly, can you provide some valid values "comply with lowercase RFC 1123." currently acccording to regex i can see following values as valid values e.g OS URL

OS URL should not be validated against lowercase RFC 1123. You can validate URL over js URL constructor (I think that would be the easy choice). The issue mentioned only to validate disk name over lowercase RFC 1123.

The accepted values as k8s describes:
>  must consist of lower case alphanumeric characters, '-' or '.', and must start
and end with an alphanumeric character

so values like:
* disk
* disk-a
* disk.1
etc.
