### ISSUE TITLE
Show groups list on project overview 

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4730]
**What would you like to be added? / User Story**:

New [Groups](https://github.com/kubermatic/dashboard/pull/4712) feature has been added therefore we need to show groups similar to like `Cluster and External Cluster` tab are shown.

https://user-images.githubusercontent.com/17727069/181701346-f8ed146f-d173-41ed-abf1-ad1e977410bb.mp4

**Comment by cschieder** [comment]
Should we Rename the sidebar point to "Members and Groups" or do you think it's self evident? 
![image.png](https://images.zenhubusercontent.com/5d00e804f425650e637ab800/2c5f5354-1687-49fc-a1fd-8e093ce184e9)

**Comment by Waseem826** [comment]
>Should we Rename the sidebar point to "Members and Groups" or do you think it's self evident?

Groups are an enterprise only feature so we'll have `Members and Groups` for EE and `Members` for CE which IMO is fine.
