### ISSUE TITLE
Issues with Resource Quotas

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#4740]
**What is the problem, where is it and why is it an issue?**

1. Alignment issues (*isolated 😁)

![Screenshot 2022-07-30 at 9 55 01 AM](https://user-images.githubusercontent.com/18264334/181875697-273ef1be-6c8c-4257-951b-a4812672a42a.png)

2. We should use a typeahead here and project names should be sorted. It was very difficult for me to find my project.

![Screenshot 2022-07-30 at 9 45 57 AM (2)](https://user-images.githubusercontent.com/18264334/181875997-8d062786-2335-4344-9b73-f4da838ec67b.png)

3. We shouldn't send in patch requests when nothing changed. Check if the form/controls changed, `this.control(XYZ).pristine`. 

https://user-images.githubusercontent.com/18264334/181875746-a9ee16ca-e831-4e43-a604-2784a6643248.mov

4. There is something extremely wrong with these input fields. It just keeps flushing the input if it exceeds 3 characters in case of `Memory` and `Disk`. For CPU if I enter `e` then it just removes the whole input, which is wrong. In general either don't handle `e` or ignore it.

https://user-images.githubusercontent.com/18264334/181875853-8516801c-c9a5-4ff2-a6f0-58baeb7e3dc6.mov

5. Maybe I'm not quite understanding this but the quota limitations didn't seem to work for me. This has nothing to do with the front-end IMO. I set a resource quota for 1 CPU and chose a flavor on AWS that has 2 vCPUs. It didn't restrict me in any way and I got a working cluster.

![Screenshot 2022-07-30 at 10 05 18 AM](https://user-images.githubusercontent.com/18264334/181875920-54691051-29b4-4e80-9632-b92a92324187.png)
![Screenshot 2022-07-30 at 10 05 35 AM](https://user-images.githubusercontent.com/18264334/181875923-51d9edd7-a422-45c9-8d4c-a2006743b37b.png)
![Screenshot 2022-07-30 at 10 08 21 AM](https://user-images.githubusercontent.com/18264334/181875930-0c838b63-2474-46f0-8c58-144acb819fb0.png)

6. We should show units here in the widget.

![Screenshot 2022-08-02 at 5 18 36 PM](https://user-images.githubusercontent.com/18264334/182372916-b1ff3bc1-c4e7-4e73-9410-bffc777f6d6d.png)

7. Why are we polling for quotas so so often? This is from the cluster details view.

![Screenshot 2022-08-02 at 10 07 09 PM](https://user-images.githubusercontent.com/18264334/182433628-a885f4f1-6874-411d-b40e-eaa0801de6ae.png)
<img width="345" alt="Screenshot 2022-08-02 at 10 05 20 PM" src="https://user-images.githubusercontent.com/18264334/182433640-eb927d6c-84d2-4db9-aef2-fa7f9d761d2b.png">

**Comment by Talha-Jamil-TJ** [comment]
@ahmedwaleedmalik please share your screen resolution.

**Comment by ahmedwaleedmalik** [comment]
`3440 x 1440` and `3840x2160`

**Comment by ahmedwaleedmalik** [comment]
Updated the ticket and included one more point.

**Comment by ahmedwaleedmalik** [comment]
Added another issue. Did we create a testing ticket against this for UI/UX @Talha-Jamil-TJ? I think we really need one. Because I'm not even testing this issue properly yet and I can see a lot of loose ends.

**Comment by ahmedwaleedmalik** [comment]
Point 5 has a dedicated ticket now https://github.com/kubermatic/dashboard/issues/4773

**Comment by cschieder** [comment]
for point 1) 

we will remove the project name inside the dialog and instead add this under the headline
Edit quota of **projectname** project

that follows the pattern we use elsewhere
![image](https://user-images.githubusercontent.com/49145827/183019241-56e54cdd-1130-4f7b-9867-e3488ef6cc7d.png)

fyi @Talha-Jamil-TJ

**Comment by pkprzekwas** [comment]
Another issue I've noticed is that on the project's overview page we must have some leaking observable. `/quotas` requests multiply over time. It depends on the number of projects, for my two projects it started with two but after some time it was 12 and after even more time more.![Screenshot 2022-08-08 at 08.39.46.png](https://ima![Screenshot 2022-08-08 at 08.39.46.png](https://images.zenhubusercontent.com/61f8f8d1223cfa5c02e47c39/9910696f-6cf8-4c63-a874-ff26f73235f2)ges.zenhubusercontent.com/61f8f8d1223cfa5c02e47c39/dd70cbaf-e63e-4a93-80db-54de3cc24596)

**Comment by Talha-Jamil-TJ** [comment]
Point 9: Need to fix the background colour of the yellow progress bar
![image.png](https://images.zenhubusercontent.com/6290ac78d7d08439dad1b86f/6c8ddadb-87ac-4bc8-82f7-0dca15a5c479)
![image.png](https://images.zenhubusercontent.com/6290ac78d7d08439dad1b86f/f69bbf97-8c71-4957-9130-7825f89fa6f9)

**Comment by Talha-Jamil-TJ** [comment]
Point number 1 (b), 2, 3, 4, 6 and 8 are done.
I want point 7 taken out, into a separate ticket.

**Comment by Waseem826** [comment]
@Talha-Jamil-TJ can you please create separate issue for point 7?

**Comment by Talha-Jamil-TJ** [comment]
I've created it https://github.com/kubermatic/dashboard/issues/4839
