### ISSUE TITLE
Fix external cluster machine deployment health status icons and status

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4746]
**What is the problem, where is it and why is it an issue?**

Currently, when external cluster MD is different state show updated cluster icon and text

External Cluster MD states
"Provisioning" -> cluster machine deployment is being created.
"Running" -> cluster machine deployment is created and is fully usable
"Reconciling" -> some work is actively being done on the machine 
"Deleting" ->cluster md machine deployment is being deleted.
"Unknown" ->cluster md machine indicates undefined state.
"Error" -> last operation persformed on cluster  machine deployment failed (doesnt mean that md is unusable)
**Suggest how to fix it, if possible**

- [ ] used information from cluster response payload to to determine state of MD

**Comment by imharshita** [comment]
State should be fetched from Get MD Response
