### ISSUE TITLE
Hint Text for Apps and Addons

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/dashboard#4756]
From product mgmt feedback: Two small hints should be displayed to make it easier for users to understand the difference between applications and addons. The following Text should be used:

- Addons: Extensions provided by Kubermatic which make changes to the cluster itself and underlying functionality
- Applications: Mechanism to install third party Applications into a cluster

Generally the text should be close to the Addons and Applications Tabs:

![image](https://user-images.githubusercontent.com/20774623/182543995-2e7eecdb-e7a1-4a0d-a9df-586993451f36.png)

No strong preference if it is a tooltip or directly displayed or another way of showing it

**Comment by Waseem826** [comment]
@cschieder do you have any suggestions on how we can add these descriptions?

**Comment by cschieder** [comment]
I'd like to show it in a) empty state and b) under the headline in the create dialogs 

Ideally we also link the respective documentation to each 

For the wording
Addons: 
Addons are extensions provided by Kubermatic to expand cluster capabilities, **learn more about Addons >** 
https://docs.kubermatic.com/kubermatic/v2.20/architecture/concept/kkp-concepts/addons/


Applications:
Install third party Applications into a cluster, **learn more about Applications >**

**Comment by Waseem826** [comment]
I think when there are no applications we should show the headline on page (instead of create dialog).

**Comment by cschieder** [comment]
that's what I meant with empty state, i think :)

**Comment by SimonTheLeg** [comment]
@cschieder @Waseem826 

regarding

> Applications:
Install third party Applications into a cluster, learn more about Applications >
(documentation is currently being written)

The guide is now ready and available at https://docs.kubermatic.com/kubermatic/master/tutorials-howtos/applications/add-applications-to-cluster/

**Comment by Waseem826** [comment]
@SimonTheLeg I've added the link to main Applications page.
