### ISSUE TITLE
Test Applications UI - Test Release 2.21

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#4763]
Test applications UI in cluster wizard and cluster details page.

### Cluster Wizard
A new Applications step (Step 5) has been added in Cluster Wizard.
- Go to Applications Step
#### Add Application
- Add an application
- Make sure application is displayed on the page
- Make sure all values are reflected on application tile
#### Edit Application
- Edit the added application
- Make sure all values entered/selected in add application dialog are persisted.
- Update application
- Make sure changes are reflected on page
#### Delete Application
- Delete application
- Make sure confirmation dialog appears
- Make sure application is not listed on page after deletion

Now add some applications on this step and click "Next" 
#### Wizard Summary page
- Make sure all added applications are visible under "Applications" section of summary page

Create the cluster with these applications.

### Cluster Details Page
A new Applications tab has been added beside Addons tab on cluster details page.
- Make sure that all applications added in Cluster Wizard are visible here
- Switch to table view and make sure that all information displayed is same as the tiles view
#### Add Application
- Add an application
- Make sure a success notification appears
- Make sure status icon updates after a while
#### Edit Application
- Edit any application 
- Make sure a success notification appears
- Make sure updated values are reflected on page
#### Delete Application
- Delete any application
- Make sure success notification appears
- Make sure a spinner icon is displayed instead of action buttons
- Make sure application is removed from the list after a while

## Acceptance Criteria

- [x] Add/Edit/Delete applications work fine in cluster wizard
- [x] Cluster Summary page displays applications correctly
- [x] Applications are created successfully
- [x] All added applications are displayed on Cluster Details page
- [x] Add/Edit/Delete applications work fine on cluster details page
- [x] Cluster applications are persisted in cluster template
- [x] Cluster applications are displayed correctly inside cluster template
- [x] Application `values` are handled correctly in add/edit applications dialog

**Comment by cschieder** [comment]
Appending Generalized UI/UX Checks to keep in mind
1.	Does the user know what’s going on at any given time? Is it obvious if a task succeeded, failed or is still in progress?
2.	Does the user know what to do with no outside help? Are the terms and words we use familiar to our users and consistent? 
3.	Do we avoid having the user remember things and aid them with searches, filters. dropdowns, pre-fills, autocomplete and so on? 
4.	In case of an error or confusion, is it clear how to go back, how to find out more or how to fix the issue?

**Comment by Waseem826** [comment]
Regarding 4th point (In case of an error or confusion, is it clear how to go back, how to find out more or how to fix the issue?): In case of applications installation error, we just display a message (returned by backend) in the tooltip but that message is not very informative.


https://user-images.githubusercontent.com/13975988/182610645-38c7b2e6-2879-46bc-8187-2aff793e6c7b.mov

**Comment by cschieder** [comment]
@Waseem826 should the application even """install""" if that kind of error happens? I'd assume showing an error that it couldn't be created because of x on the bottom right would also work. Or we offer the option to try to "reconnect" or "restart download" or something? We need to make the error more human readable and understandable ideally and tell the user what the next step should be

**Comment by Waseem826** [comment]
I'm not sure if we can prevent the application from installing because some of these actions are performed asynchronously after the application has been added to the list. Perhaps @SimonTheLeg can add something here?

**Comment by SimonTheLeg** [comment]
> I'm not sure if we can prevent the application from installing because some of these actions are performed asynchronously after the application has been added to the list

Yes. We cannot prevent the installation of an App, as it is asynchronous and we find errors during install and there is no reliable way to check beforehand. In essence the FE makes a request for a desired state (which is also what is shown in the FE) and then the BE asynchronously tries to create that state and if it cannot, the error is displayed.

However what I can say, is that the Cluster Admin which added the Application often cannot fix it. Usually the KKP admin needs to make changes to the definition to solve issues like this. Maybe we could add the following sentence: `Please check your configuration or contact your KKP Administrator` to the message which is displayed above? (this could also be sent from BE)

cc @vgramer

**Comment by wurbanski** [comment]
potential enhancements regarding editing an application in cluster details view:
1. editing only allows the user to change values - I think this is a little unclear for the user (I was surprised I cannot change the version)
2. after changing the values, notification shows that there is a change, but the light stays green and it's easy to miss if the change has been applied or not

Other than that, all functionalities seem to work correctly.

**Comment by Waseem826** [comment]
> 1. editing only allows the user to change values - I think this is a little unclear for the user (I was surprised I cannot change the version)

I think version change is planned for future but @SimonTheLeg knows better I think.
