### ISSUE TITLE
Show fields as disabled in case of AKS/EKS external until value is selected

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4769]
- [ ] **EKS:**
Show subnets/security groups as disabled (not hidden) until VPC is selected

https://user-images.githubusercontent.com/17727069/182606795-53dc08d8-33f3-4d03-8cf7-2763921f1580.mp4

- [ ] **AKS:**
Show VMSize as disabled till Location is entered
![Screenshot](https://user-images.githubusercontent.com/17727069/182607159-18d8e7f2-6a7c-4eb0-b976-cb0e541a9526.png)

**Comment by imharshita** [comment]
also remove the `supported versions` link under `VM Sizes`
