### ISSUE TITLE
Bug: quota enforcement is not working

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/dashboard#4773]
Machine deployment validation is not blocking the creation of new replicas when the project resource quotas reaches its limits.

![151.25.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/3fbb4757-ffb8-4002-be45-7d755ab0da25)

**Following tests were attempted after the quotas were all used (100%)**:
- Creation of a new replica for the initial cluster machine deployment.
- Creation of a new cluster machine deployment.
- Creation of a new cluster.

For all of the attempts, new MD replicas were created, despite the quotas were already above 100%.

**Comment by rastislavs** [comment]
Fixed in https://github.com/kubermatic/kubermatic/pull/10718
