### ISSUE TITLE
Test External Cluster AKS UI - Test Release 2.21

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4778]
## Testing Procedure

**External Cluster Wizard**

**Note**: "Add External Cluster" was before but it was used to import external cluster from cloud provider which were already imported in cloud provider.

A new button under clusters tab "External Clusters" has been added to create external cluster.

### Add External AKS Cluster via Wizard
- [x] Check if AKS provider exists
- [x] Add new AKS cluster via wizard
     - [x] Check cluster creation via preset
     - [x] Check cluster creation via credentials
- [x] Check new cluster is created and redirected to details page
- [x] Check all info is displayed under details page under cluster info
     - [x] Location
     - [x] Resource Group
     - [x] Cluster Version  ~~ (Kubernetes Version) 
     - [x]  Is-Imported
- [x] Check new cluster entry should exists in list page.

### Import External via Import Dialog

**Note**: Much done from UI side but things which are effected is listed here:

- [x] Check imported cluster entry should exists in list page 
- [x] Delete button `icon` **shouldn't** be available for `imported` cluster on list page
- [x] Delete button `icon` **shouldn't** be available for `imported` cluster on details page
- [x] Disconnect button **should** exist for list and details page for Imported cluster

### Add External AKS Cluster Machine deployment
  - [x] Check cluster creation status
  - [x] Check initial machine deployment creation
  - [x] Check "Add Machine Deployment" button exists
  - [x] Dialog should show heading "Add Node Pool" for AKS as per cloud provider name for similarity with cloud provider naming conventions.
  - [x] Check dropdown
      - [x] Check Kubernetes Versions list is fetched
      - [x] Check VM Size lists list is fetched
  - [x] Check machine deployment Auto scaling
  - [x] Check operations like create/delete/edit operation exists

### Edit External AKS Cluster Machine deployment
  - [x] Check cluster creation status
  - [x] Check edit operation exists
  - [x] Update machine deployment
     - [x] Try to update "No of Replicas" OR "Kubelet version" only **1** option is allowed to update. The other field which is not updated must be `disabled`.

### Delete External AKS Cluster
  - [x] Check cluster creation status
  - [x] Delete option is only available if cluster is not `Imported"
  - [x] Check "Disconnect" functionality is available for both `Created/Imported` cluster
  - [x] Info icon : `Cluster has nodegroups attached <nodegroups> attached` info should be displayed

## Acceptance Criteria

- [x] Add/Edit/Delete external cluster in cluster wizard
- [x] Cluster details page must show details used in wizard
- [x] Cluster details allows to add/edit/delete machine deployment for cluster
- [x] External clusters must be listed under "External Clusters" tab
- [x] Only Allow to delete/disconnect for create via wizard
- [x] Only Allow to disconnect for imported cluster via "Import External Cluster" dialog

### Other Features
- [x] Check the API documentation

**Comment by hbernardo** [comment]
In general, everything worked fine, but I found some _**issues related to Machine Deployments**_:
1. I wasn’t able to create a new machine deployment:
![Machine Deployments.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/f76165c9-a15d-40f1-93d6-1efb0f41434f)
![Pasted Graphic 6.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/c19ec5ab-f203-41d7-bb7c-e78336399b5d)

2. I wasn’t able to increase number of replicas for MD (it keeps loading for a long time, then come back to 1/1 replicas)

3. I wasn’t able to update MD Kubelet version (status icon shows error without any feedback)
![image.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/e61906ec-8e35-426e-8b09-48b430e86433)

4. When adding a machine deployment, Kubelet version is always the same as the cluster version, there is no fetched list neither dropdown
![Add Node Pool.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/0e570d39-9b2d-4126-b9c7-6b28e72bedcc)

**Comment by imharshita** [comment]
regarding `When you use wrong Azure credentials in cluster creation wizard, cluster is created, but it doesn't become stable and it doesn't expose any errors` , we can create a enhancement issue, this can happen when credentials used have access to create a cluster but not to access the kubeconfig.

**Comment by hbernardo** [comment]
Created tasks:

Bugs:
- kubermatic/kubermatic#10852: AKS external cluster: new Machine Deployment isn't becoming stable
- kubermatic/kubermatic#10853: AKS external cluster: not possible to edit Machine Deployment (replicas neither Kubelet version)
- kubermatic/dashboard#4893: AKS external cluster: missing dropdown showing all possible Kubernetes versions in form for new MD

Enhancement:
- kubermatic/kubermatic#10854: AKS external cluster: expose errors when having credentials issues when creating the cluster

**Comment by rastislavs** [comment]
Closing as remaining enhancements are reported in mentioned issues.
