### ISSUE TITLE
Test External Cluster EKS UI - Test Release 2.21

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4779]
## Testing Procedure

**External Cluster Wizard**

**Note**: "Add External Cluster" was before but it was used to import external cluster from cloud provider which were already imported.

A new button under clusters tab "External Clusters" has been added to create external cluster.

### Create External EKS Cluster via Wizard
- [ ] Check if EKS provider exists
- [ ] Add new EKS cluster via wizard
     - [ ] Check cluster creation via preset
     - [ ] Check cluster creation via credentials
- [ ] Check new cluster is created and redirected to details page
- [ ] Check all info is displayed under details page
     - [ ] VpcID, Subnets, Security Groups, Kubernetes Version
- [ ] Check new cluster entry should exists in list page under external cluster details page.

### Create External EKS Cluster Machine deployment
  - [ ] Check cluster creation status
  - [ ] Check initial machine deployment creation
  - [ ] Check "Add Machine Deployment" button exists
  - [ ] Check cluster version upgrades
  - [ ] Check machine deployment Auto scaling
  - [ ] Check operations like create/delete/edit operation exists

### Import External via Import Dialog
**Note**: Much done from UI side but things which are effected is listed here:

- [ ] Check imported cluster entry should exists in list page 
- [ ] Delete button `icon` **shouldn't** be available for `imported` cluster on list page
- [ ] Delete button `icon` **shouldn't** be available for `imported` cluster on details page
- [ ] Disconnect button **should** exist for list and details page for Imported cluster

### Edit External EKS Cluster Machine deployment
  - [ ] Check cluster creation status
  - [ ] Check edit operation exists
  - [ ] Update machine deployment
     - [ ] Try to update "No of Replicas" OR "Kubelet version" only 1 at option is allowed.

### Delete External EKS Cluster
  - [ ] Check cluster creation status
  - [ ] Delete option is only available if cluster is not `Imported"
  - [ ] Check "Disconnect" functionality is available for both `Created/Imported` cluster

## Acceptance Criteria

- [ ] Add/Edit/Delete external cluster in cluster wizard
- [ ] Cluster details page must show details used in wizard
- [ ] Cluster details allows to add/edit/delete machine deployment for cluster
- [ ] External clusters must be listed under "External Clusters" tab
- [ ] Only Allow to delete/disconnect for create via wizard
- [ ] Only Allow to disconnect for imported cluster via "Import External Cluster" dialog

### Other Features
- [ ] Check the API documentation

**Comment by ahmedwaleedmalik** [comment]
@KhizerRehan do we have any pending tickets for bug fixes etc for EKS that I should be aware of before testing this?

**Comment by KhizerRehan** [comment]
> @KhizerRehan do we have any pending tickets for bug fixes etc for EKS that I should be aware of before testing this?

Hi, Sorry for late reply. We don't have ticket related to EKS but only 1 PR related to Custom External Cluster.

**Comment by ahmedwaleedmalik** [comment]
The feature in its current state works fine. There are a lot of improvements that can be done from the BE side but they are out of scope for this release.
