### ISSUE TITLE
Test External Cluster GKE UI - Test Release 2.21

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4780]

**Comment by ahmadhamzh** [comment]
- [ ] go to create external cluster wizard and chose google kubernetes engine 
- [ ] enter the Credentials settings (preset : external or service account ) and check that the `next` button is only valid when chose credentials
- [ ] fill all the required fields and check that the button `create external cluster` only valid when all requires field are filled 
- [ ] try to add some wrong values and check the errors messages and then click on `create external cluster` button 
- [ ] check if the cluster appear on the list for external clusters and the right data is been displayed for it 
- [ ] check if the cluster been created in the provider side successfully and it's initial node pool.
- [ ] go to the cluster page you just create and check that the `add machine deployment` button is not valid till the cluster health is running (green circle) 
- [ ] try to add machine deployment
- [ ] check if it been created in the provider side successfully 
- [ ] try to edit the MD and check if it's been updated in the provider side 
- [ ] delete the MD and check if it's been deleted in the provider side
- [ ] delete the cluster and check if it's been deleted from provider side successfully

**Comment by imharshita** [comment]
updated the above list
