### ISSUE TITLE
External cluster bug fix []string to []object

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4787]
**What would you like to be added? / User Story**:
[Backend PR:](https://github.com/kubermatic/kubermatic/pull/10704)
- [ ] rename `isImported` label to `is-imported`
- [ ] VM sizes returns object rather than strings[]
- [ ] add safety  `?.` checks on cluster details page for security groups and subnets

**Comment by KhizerRehan** [comment]
@imharshita can you add screenshot and we can discuss as design change if needed in this release.

**Comment by imharshita** [comment]
@KhizerRehan not priority: "Replace Labels on External Cluster list with more relevant and important information
`Kubernetes Version` and `Region`"
