### ISSUE TITLE
Change how the error message looks for missing required field

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4803]
**What is the problem, where is it and why is it an issue?**
Can we change the message if a missing field is required to somewhat look like this:

![required](https://user-images.githubusercontent.com/78943096/184039770-04dac7fd-3792-4462-b473-14bbe63c4f2f.png)

This looks a bit overwhelming to me:

![required-kkp](https://user-images.githubusercontent.com/78943096/184039960-1a03ea03-350c-4fcf-9cf3-e2bd30c610a8.png)

**Suggest how to fix it, if possible**

**Comment by imharshita** [comment]
@cschieder WDYT?

**Comment by cschieder** [comment]
@imharshita  What's shown in your screenshot should never happen unless the user clears every field after already having entered data, maybe. It's not intended to have errors show up before you as the user even had a chance to fill in a field. How did this happen?

**Comment by imharshita** [comment]
@cschieder, please update this issue if the changes are approved or not, whenever you can.

**Comment by cschieder** [comment]
Let's reduce the error message to "is required"
![image](https://user-images.githubusercontent.com/49145827/185071072-148b5224-233d-4f1b-bc17-82da394c9174.png)

**Comment by Waseem826** [comment]
I think we can just use `required` instead of `is required`.

**Comment by cschieder** [comment]
works too
