### ISSUE TITLE
Make it clear what proxy mode will be configured when creating a new cluster if user makes no choice

### ISSUE THREAD

**Issue by judge-red** [kubermatic/dashboard#4804]
With the addition of Cilium and "None" CNIs, it's become more confusing than ever which proxy mode will be used if the user doesn't pick one specifically. Please somehow indicate which one is the default, either by pre-filling the drop down (like you do for the CNI version) or by adding something like `[default]` to the according option in the dropdown (which should of course change when a different CNI plugin is chosen.

**Comment by Waseem826** [comment]
Isn't `ipvs` selected by default even if `None` option is selected?

![screenshot-localhost_8000-2022 08 11-14_27_42](https://user-images.githubusercontent.com/13975988/184104250-ee95abcc-4aff-48da-bff2-a9a4d450e7b5.png)

Please let me know if I missed something?

**Comment by rastislavs** [comment]
Hi @judge-red 
I think we have fixed this already in the master KKP version (to be released as KKP 2.21): all network defaults will be pre-filled in the UI - see https://github.com/kubermatic/dashboard/issues/4551

**Comment by judge-red** [comment]
@rastislavs #4451 sounds great and would indeed address this. We're still on 2.19 but hope to catch up to 2.21 soon after release. Thanks!
