### ISSUE TITLE
In a project's cluster list, please include "<# of ready nodes>/<total # of machines>" (and status?)

### ISSUE THREAD

**Issue by judge-red** [kubermatic/dashboard#4805]
Currently:
- in the cluster list, there's a green/yellow/red dot which I think indicated CP healthiness
- in the cluster overview / details page, there's also a green/yellow/red dot indicating MachineDeployment health as well as a "<# of ready nodes>/<total # of Machines in MD>" info

Desired:
- in the cluster list, it should also show the <total # of ready nodes>/<total # of Machines in cluster>" - so the sum of all MDs in the cluster
- in the cluster list, it should also show the lowest/worst status (green/yellow/red) of the nodes in the cluster - again, kind of a "sum" of all MDs in the cluster

Example:
- in the cluster overview, we see two MachineDeployments with the following:
🟡 2/3
🟢 1/1
- in the cluster list, I'd like to see:
🟡 3/4

**Comment by pkprzekwas** [comment]
While working on an implementation please take into account to split requests for clusters and machine deployments. Call for machine deployments data can take significantly longer and we should not block displaying cluster list. I suggest using some loaders.

Same for a project overview page. We should call for machine deployments separately (if at all) and use loaders. 

Also, it would be nice to have a loader in the cluster list component on project overview page. At the moment it presents misleading `No clusters available.` message until it fetches the data.
