### ISSUE TITLE
Cannot edit existing clusters due to unmarshal failure in v1.EventRateLimitConfigItem

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#4806]
### What happened
On dev, I cannot edit an existing cluster from the UI anymore because changing settings and hitting "Save Changes" produces an error:

> cannot decode patched cluster: json: cannot unmarshal string into Go struct field EventRateLimitConfig.spec.eventRateLimitConfig.namespace of type v1.EventRateLimitConfigItem

Note that I do not have EventRateLimit enabled or configured on this cluster. I suspect #4802 broke it, but just because it's a recent change to EventRateLimit configuration (haven't looked further into this).

### Expected behavior

Editing a cluster works.

### How to reproduce

- Create a cluster via the UI
- Wait for it to start up
- Attempt to edit it via the "Edit Cluster" menu

### Environment
- UI Version: master
- API Version: master
- Domain:
- Others:

### Current workaround

Edit the cluster via `kubectl edit`.

### Affected user persona

Cluster owners / administrators

**Comment by ahmedwaleedmalik** [comment]
This will be fixed with https://github.com/kubermatic/dashboard/pull/4808. We've investigated and #4442 was the one that broke this functionality. #4802 just exposed the issue :D
