### ISSUE TITLE
Not able to fetch old metering reports

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/dashboard#4807]
### What happened?

I was trying to download reports created before 2.21 migration. It is not possible from the dashboard.

### Expected behavior

Available list of reports to download or remove.

### How to reproduce the issue?

Go to `https://<dashboard_url>/settings/metering`.

### How is your environment configured?

- KKP version: 2.21

### Additional information

Old reports are stored in the root directory of S3 bucket and we don't download them from there while traversing schedule configurations. Old reports are available to fetch under GET `/api/v1/admin/metering/reports`.

**Comment by WeirdMachine** [comment]
For old reports we would still need this logic in place to filter the data csv files from the report files:

https://github.com/kubermatic/kubermatic/pull/10784
