### ISSUE TITLE
Modify External Cluster List Page 

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4819]
**What would you like to be added? / User Story**:
- Replace Labels on External Cluster list with more relevant and important information
`Kubernetes Version` and `Region`
![ext](https://user-images.githubusercontent.com/78943096/184595283-f130857f-6f97-4cb4-b1c3-6a889153655b.png)

Remove Labels and Add `Region` and `Kubernetes Version`

**Comment by KhizerRehan** [comment]
This change is currently applicable on Normal clusters as it requires Backend API change to return `Kubernetes Version and Region` in external cluster list so won't be manage in this `KKP 2.21` release hence removing milestone.

cc: @Waseem826

**Comment by KhizerRehan** [comment]
**External Clusters:**

This ticker is blocked by backend for `Stopped` clusters from provider side version is not returned so either it requires change at CRD level to store version from backend side.

It also handles edge case what if user tries to update existing version from Version Upgrade picker will it show updated version in list endpoint or old one till the time it is processing or in case of failure any update to notify user if upgrade failed to update.

cc: @imharshita
