### ISSUE TITLE
Test Network Configuration improvements and Dual-Stack support - Test Release 2.21

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#4823]
Test network configuration improvements and dual-stack support in cluster wizard and cluster details page.

#### Network Configuration Improvements
Network Configuration settings on Cluster Step (Step 2) of cluster wizard have been moved inside "Advanced Network Configuration" expansion panel. These values are also pre-filled based upon the selected datacenter.

- [x] All values are pre-filled.
- [x] Error messages are shown if value is invalid.

#### Dual-Stack Support
A new dual-stack option has been added on Cluster Step (Step 2) of cluster wizard. This option is visible when `ipv6Enabled` is `true` for the selected datacenter.

- [x] Options to switch between `IPv4` and dual-stack are shown.
- [x] `IPv6` settings are displayed (under Advanced Network Configuration) when dual-stack option is selected.
- [x] Error messages are shown for invalid values.
- [x] Dual-stack values are shown on cluster summary step.
- [x] Dual-stack values are shown on Cluster Details page.

**Comment by rastislavs** [comment]
All features worked as described & intended.
