### ISSUE TITLE
Get Imported Clusters show imported time

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4832]
### What happened
-  [x] For the cluster list page:
 - rename `Created` field to `Imported`: Imported means the time the cluster was imported
-   [x] For cluster details page:
 - have Imported field and Created field
 - for custom clusters Created field will be empty/ hidden `creationTimestamp`

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by ahmedwaleedmalik** [comment]
@imharshita @KhizerRehan why did we close this issue? Did it get resolved by itself? Was there some PR that fixed it. I don't see any PR being linked with this.

**Comment by KhizerRehan** [comment]
Only the first part is done. 
- https://github.com/kubermatic/dashboard/pull/4830/files

cc: @ahmadhamzh
