### ISSUE TITLE
Test KubeVirt Improvements - Test Release 2.21

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#4833]
Test KubeVirt improvements in cluster wizard.

#### Pre-Allocated Data Volumes
Pre-Allocated Data Volumes are labelled as "Custom Local Disks" (Under Advanced Disk Configuration) on Cluster Step (Step 3) of cluster wizard.

- [ ] Add/Edit/Delete custom local disks.
- [ ] Custom local disks are displayed on wizard summary step.
- [ ] Custom local disks are displayed in Edit Cluster dialog (on cluster details page).

#### Affinity Settings
Affinity settings are added under "Advanced Scheduling Settings" on Initial Nodes Step (Step 4) of cluster wizard.

- [ ] Configure affinity settings.
- [ ] Node affinity settings are displayed when node affinity preset is selected.
- [ ] Affinity settings are displayed on wizard summary step.
- [ ] Affinity settings are displayed under node details on Machine Deployment details page.

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 I've posted some improvements in https://github.com/kubermatic/dashboard/issues/4715 but we don't need them for KKP 2.21. Otherwise, everything is good.
