### ISSUE TITLE
Test External Cluster Custom - Test Release 2.21

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4870]
## Testing Procedure

**Import External Cluster**

**Note**: "Import External Cluster" was before but it was used to import external cluster from GKE,EKS, & AKS only now you can import External Cluster from other Providers using the kubeconfig but it only can be viewed not edit .

A new button under clusters tab "External Clusters" has been added to create external cluster.

### Import External Cluster 
- [x] Check if `Any provider` button exists in the add external cluster dialog at the left-bottom of the dialig
- [x] Add new External cluster using the kubeconfig for that cluster
- [x] Check new cluster is imported and redirected to details page
- [x] Check imported cluster entry should exists in list page 
- [x] Delete button `icon` **shouldn't** be available for cluster on list page and detail page 
- [x] Add/Edit/Delete Machine Deployment  **shouldn't** be available
- [x] Disconnect button **should** exist for list and details page
- [x] Get Kubeconfig button **should** exist in cluster details page
- [x] Check if you can disconnect the cluster successfully (can be done from cluster detail page and the external cluster list page)

**Comment by hbernardo** [comment]
LGTM

**Comment by hbernardo** [comment]
LGTM
