### ISSUE TITLE
Test Project Quota UI - Test Release 2.21

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4872]
Test project resource quotas.

## Testing procedure
**This feature is only available in Enterprise edition, any of the following features should not be visible on Community Edition**

### Admin Panel 
A new **Quotas** setting page has been added to the admin panel
- Go to Quotas admin setting page
#### Add Quota
- Add quota from dialog by clicking `Add Project Quota` button
- Make sure added quota is displayed in the quotas table
- Make sure added quota has correct values
#### Edit Quota
- Edit a quota by clicking the `Edit` icon from the actions column of the quotas table
- Make sure that the updated quota is reflected in the quotas table
#### Delete Quota
- Delete a quota by clicking the `Delete` icon from the actions column of the quotas table
- Make sure that the deleted quota is removed from the quotas table

### Projects view
Quota widget is added to projects page -> `/projects`

#####  No quotas added to any project
- Cards should fit to contents
- Quota widget or placeholder saying `No quotas configured` should not be visible
#####  Quotas added to some projects or all projects
- Project cards with quotas should show the quota widget at the bottom of the card
- All other cards should show placeholder saying `No quotas configured`
#### Table view
- added quotas should be visible in the quotas column

### Project overview page
Quota widget is added to the project overview page -> `/projects/<project-id>/overview`
- If quota is added to the project, quota widget should be visible in a card in the right column

### Project clusters page
Quota widget is added to the project overview page -> `/projects/<project-id>/clusters`
- If quota is added to the project, quota widget should be visible besides the top-right buttons
- hovering over the button should show it's detail panel

### Cluster creation
An extended version of quota widget is added to the 4th step of cluster creation wizard
- If quota is added to the project, quota widget should be visible above **Node Labels**

## Acceptance Criteria

- [x] All features are only available in the enterprise edition
- [x] Add/Edit/Delete quotas work fine
- [x] Proper validation should be visible on add/edit dialog
- [x] Quotas table on the admin setting page works correctly
- [x] Projects card view shows widgets correctly 
- [x] Projects table view show widgets correctly
- [x] Project overview page shows widgets correctly
- [x] Project clusters page shows widgets correctly
- [x] Widget shows details while hovering on project clusters page
- [x] Extended version of quota widget is shown on the 4th step of cluster wizard

**Comment by KhizerRehan** [comment]
@Talha-Jamil-TJ can you update description for testing

**Comment by ahmadhamzh** [comment]
it seems like if i add cluster or update the number of replica while i don't have enough quota is still working i got the error in the event that i don't have enough quota but after some time the node been created successfully 
![Screenshot from 2022-08-24 12-39-37.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/5a3b1cf4-d569-42a4-b0bf-14ed02d8d572)
