### ISSUE TITLE
Clicking on a disabled dropdown item works

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/dashboard#4882]
### What happened
Being a project's viewer and clicking on a disabled button opens selected item. 

### Expected behavior
If the button is greyed out it should not react to clicks.

### How to reproduce
1. Enter project where you have viewer permission.
2. On "Project Overview" page click on "Create Resource" dropdown.
3. Click on disabled "Create Cluster" item.
4. Watch how wizard opens.

### Environment
- UI Version: 2.21
- API Version: 2.21
- Domain: https://kkp.qa.lab.kubermatic.io/

![Screenshot 2022-08-24 at 09.28.10.png](https://images.zenhubusercontent.com/61f8f8d1223cfa5c02e47c39/5ddde0db-e402-4545-891a-249d1f9d42d6)

**Comment by Talha-Jamil-TJ** [comment]
According to @ahmedwaleedmalik, we should disable the `create cluster template` button as well when a user just has “view” access.

**Comment by ahmedwaleedmalik** [comment]
That's correct @Talha-Jamil-TJ 👍

**Comment by Talha-Jamil-TJ** [comment]
I'm also adding tooltip to buttons with message `You do not have permission to perform this action`, when buttons are disabled
cc: @cschieder @ahmedwaleedmalik

**Comment by Talha-Jamil-TJ** [comment]
@ahmadhamzh there is a typo in `View` enum which is not matching with the API response of `clusterTemplate` 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/56511988/186427370-fa248e45-0e26-42da-b2c8-3e37cd95e496.png">

Unfortunately changing it is making other areas fail too, so I'm skipping it for now as it will require more testing, we'll come back the next release.

cc: @Waseem826
