### ISSUE TITLE
Change dropdown fields to single select combobox

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/dashboard#4893]
When adding a Machine Deployment, Kubernetes version field is a text field and it shows only the default value.

![Add Node Pool.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/0e570d39-9b2d-4126-b9c7-6b28e72bedcc)

It only shows the other options when erasing the field, but it should be a dropdown with all possible values and the default one selected.

**Comment by imharshita** [comment]
this issue is on both create cluster and md wizard

**Comment by imharshita** [comment]
![image](https://user-images.githubusercontent.com/78943096/187385292-c720bb37-111a-413e-be90-b8d43e90f8c2.png)

**Comment by imharshita** [comment]
AKS cluster location:

![image](https://user-images.githubusercontent.com/78943096/187386225-7b8f60cb-8253-4d95-ac68-2941d05d905f.png)

**Comment by imharshita** [comment]
eks vpc cluster create:
![image](https://user-images.githubusercontent.com/78943096/187389285-f0197b26-a7f8-404e-a41e-beda9a8ac4fa.png)

**Comment by Waseem826** [comment]
> eks vpc cluster create

There's already a separate issue for this: https://github.com/kubermatic/dashboard/issues/4768
