### ISSUE TITLE
Fix layout for Event Rate Limit in edit/create cluster

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4896]
**What is the problem, where is it and why is it an issue?**
- Selection of "Event Rate Limit" disrupts the UI for dialog:

**steps to produce:**
- Navigate to Cluster Details page 
- Try to edit cluster
- Select `Event Rate Limit` value from "Admission plugin" dropdown

https://user-images.githubusercontent.com/17727069/186624278-cfc0b0d8-4d79-406a-b0b8-1fd61d89406f.mp4

**Suggest how to fix it, if possible**

**Comment by cschieder** [comment]
This also happens on the wizard, use smaller browser width and watch it push everything to the side. 
![image](https://user-images.githubusercontent.com/49145827/187171422-bec8b621-9f60-489f-a632-c889036c5870.png)
