### ISSUE TITLE
EKS Subnet Improvement

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4911]
**What would you like to be added? / User Story**:
EKS Subnet Improvement:
- [ ] Integrate default subnets with diff azs
- [ ] Custom validator: error when user chooses subnet with no 2 diff azs

![image](https://user-images.githubusercontent.com/78943096/187388159-6bd4525e-5da8-4ef5-ac62-facdd1978bec.png)

**Comment by imharshita** [comment]
@KhizerRehan please close this issue and mention the pr

**Comment by KhizerRehan** [comment]
/close 
- Already handled "default subnets with diff azs" in [PR#4964](https://github.com/kubermatic/dashboard/pull/4964/files#r969462551)
- currently, not supporting custom validator from UI side
