### ISSUE TITLE
Quota UI Follow Ups

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4913]
#### Project view
- [x] add "xxx/xxx unit" e. g. 10/10 GB tooltip hover over each project card/table quota
- [x] fix table view width of bars (CPU has less width than Memory and Disk) 
- [x] project card view: spacing from crown (owners) to quotas is larger than clusters to crown (Owners)
- [x] Make it possible for admins to edit quotas on project edit, we add this line to project cards, only visible for admins
![image](https://user-images.githubusercontent.com/49145827/187635596-7851f6e3-3e5d-4b9f-8481-640a01055503.png)

- [x] Fix spacing between owner, role row and quota row, it should be the same as the space between cluster and owner
![image](https://user-images.githubusercontent.com/49145827/205612537-79096d6c-6c90-47d0-98c3-c10dfc2680e8.png)

#### Global
- [x] fix width of bars on widget as well, they should be the same size (visible on Cluster page)
![image](https://user-images.githubusercontent.com/49145827/187635848-4e380ea4-e108-4b6f-9d23-6561334178a6.png)
- [x] Adjust bar color behavior: dark blue for the bars as it is right now, if a quota is hit exactly its yellow, only once a quota is overdrawn does it get red

#### Admin Panel
- [x] on Admin Panel -> Quotas right align CPU, Memory and Disk columns
- [x]  Replace simple table with bars
![image](https://user-images.githubusercontent.com/49145827/188877966-fd979cf3-85a8-4d01-9015-f5a46a746184.png)

#### Create

- [x] CPU, Memory, Disk bars should move into their own line to prevent stuff like screenshot below from occuring, either
A) break lines of bars automatically instead of linebreak of units B) break at a fixed width 

![image](https://user-images.githubusercontent.com/49145827/195334351-6075c425-022e-40ec-bd12-a78e00b3669c.png)

#### Cluster
- [x] on narrow browser width auto collapse Quota widget (above cluster table) to only icon, when collapsed hover card looks like shown in screenshot

![image](https://user-images.githubusercontent.com/49145827/195091027-37288f36-0974-4929-8e9e-e5073227820b.png)

**Comment by Waseem826** [comment]
Apart from these points (which are all valid), I noticed that the quota widget has a sudden appearance when API request finishes. Can we show some spinner or skeleton loader when API request is pending?


https://user-images.githubusercontent.com/13975988/187654011-9242bb58-26b3-4117-96bf-d74ff19202ef.mov
