### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4924]
- [x] Operating System Profile should have a dropdown arrow (Create Cluster, Step 4, left side)
- [x] Please add around 10px space between the lines, see image for where I mean
![image](https://user-images.githubusercontent.com/49145827/187890875-88e7051b-233a-4c9b-b720-a141842bff85.png)
- [x] Remove name field from edit machine deployment dialog (it can't be edited and the description says the MD name anyway) 
- [x] remove "show" and "hide" from unfoldable/additional information on cluster details change "additonal" to "more" or "advanced"
- [x] Remove line breaks from project overview ( External Clusters, Cluster Templates, Service Accounts, ...) 
![image](https://user-images.githubusercontent.com/49145827/187888153-da6067a9-9e63-4c34-9796-d6b6c5d903cc.png)

- [x] labels to value spacing not consistent, 
![image](https://user-images.githubusercontent.com/49145827/187911847-b535b7bc-d272-4add-82cf-365baa8842ab.png)
_note: there's 2 different styles of this, one with small margin (on project overview) and one with large margin (that it optically matches text fields and dropdowns, basically everywhere else)_

We will change it to 1 style only. The spacing should optically match with the dropdown fields next to it. (I achieved that with a margin-bottom of 3 px to the label, hope that helps)

![image](https://user-images.githubusercontent.com/49145827/187889999-5758c179-423d-4498-b1c0-9687a252f6ac.png)

- [x] Fix Summary page number alignments (number should be vertically and horizontally centered in the circle, the circle should be in the same line as the headline) 
![image](https://user-images.githubusercontent.com/49145827/188418902-607cd775-eefe-4ee8-bf28-9289d1a77185.png)

- [x]  Add Numbering to headline steps in "Create from Template" Dialog
![image](https://user-images.githubusercontent.com/49145827/188419228-a56c7761-1add-40fa-ad1a-67597bb748ee.png)

**Comment by Waseem826** [comment]
>We will change it to 1 style only. The spacing should optically match with the dropdown fields next to it. (I achieved that with a margin-bottom of 3 px to the label, hope that helps)

https://github.com/kubermatic/dashboard/issues/5024 will cover this.

**Comment by Waseem826** [comment]
>remove "show" and "hide" from unfoldable/additional information on cluster details change "additonal" to "more" or "advanced"

@cschieder I think "additional" is more accurate than "advanced" or "more" because these are not really advanced information and "more" doesn't quite sound right. WDYT?

**Comment by cschieder** [comment]
Okay then we keep it with "additonal"
