### ISSUE TITLE
Default values are not shown in external cluster wizard when preset/credentials are cleared and selected again

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4940]
### What happened
In external cluster wizard, when preset is cleared and then reselected (or credentials are cleared and entered again) then some default values in external cluster details step are not shown. This issue only happens for AKS and GKE since those 2 providers have default values in external cluster details step.
This issue is most problematic for AKS provider because `Mode` has pre-selected `System` value and since its disabled so when its not selected by default then it is not possible to create the cluster. 

https://user-images.githubusercontent.com/13975988/189621476-cdd149b1-612e-4bb4-9d27-4752c0f0efaf.mov

### Expected behavior
Default values are shown even if preset/credentials are cleared and then selected again.

### How to reproduce
In external cluster wizard:
- Select AKS or GKE provider
- Go to external cluster details step (Step 3)
- Navigate back to Step 2
- Clear preset (or credentials) and then select again
- Go to Step 3 again
- Default values (number fields and disabled fields) are empty

### Environment
- UI Version: 2.21
- API Version:
- Domain:
- Others:

**Comment by ahmedwaleedmalik** [comment]
@KhizerRehan I tried reproducing this and couldn't. The description is not clear enough and needs a lot of improvement. Also please don't add internal code-related details in the description especially in `What happened` and `Expected behavior` blocks.
