### ISSUE TITLE
Customizable cluster templates UI 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4948]
### Solution details
- When creating a cluster from a template there is a Customize button
- Customize button will open the wizard with every parameter prefilled from the template (except for credentials)
- Any prefilled parameter can be edited, if there is data that is dependant on the prefilled parameter, and the prefilled parameter gets changed, we clear the dependant data upon change of the prefilled data
- the modified template should be able to be saved
- the credentials are emptied for security reasons

Create from customized is limited to 1 cluster as of now

### UI 
![image](https://user-images.githubusercontent.com/49145827/189612372-74cf33a8-a354-46d6-af60-acf00994e24c.png)
Add 'Customize Template' button to *Step 1* (not Step 2), grey out the button pre-selection of template

Last Step wizard
![image](https://user-images.githubusercontent.com/49145827/189614143-b20c34a7-7c2a-4680-a5cd-6fddbb95198c.png)

Add "Customize Cluster" (like on External Cluster Create) above stepper
![image](https://user-images.githubusercontent.com/49145827/189618348-0992a99b-796f-4ac7-be7e-2c1a890a5ba8.png)

### Use cases
- If one user would like to create multiple clusters with almost the same parameters but with different credentials, when KKP is not being used in a self-service way, and the admin executes the requests for creating clusters for example

**Comment by ahmedwaleedmalik** [comment]
Closed with https://github.com/kubermatic/dashboard/pull/5295
