### ISSUE TITLE
Delete icon shown for deleted clusters

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#4959]
### What happened
Delete icon shown for deleted clusters:
- [x] KKP clusters
- [ ] External clusters:
 - deleting cluster: this can be done by checking if status == `Deleting`
 - once cluster is deleted:
   - aks: `"status":{"state":"Error","statusMessage":"{\"error\":{\"code\":\"ResourceNotFound\"}}`
   - eks: `"status":{"state":"Error","statusMessage":"ResourceNotFoundException: No cluster found for name: xxxx."}}`
   - gke: `"status":{"state":"Error","statusMessage":"Not found."}}`
 so maybe for deleted clusters, we can search for  Not found/ NotFound etc. in status.statusMessage

### Expected behavior
Delete icon should be hidden for deleted/not found clusters
### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by Waseem826** [comment]
How do we check if a cluster has been deleted from provider side?
