### ISSUE TITLE
Quota - Live Update

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4978]
Following the [Quota Discussion](https://docs.google.com/document/d/1IJR3mU2AJeOjJmXcHMXUuS1403FHpnM-tmIOam487NQ/edit?usp=sharing)
### Enhanced Functionality
Requires kubermatic/kubermatic#xx Endpoints

Add live update to quota depending on user action (e. g. on the cluster create dialog, the user increases disk size, the disk size of the quota updates live)
![image](https://user-images.githubusercontent.com/49145827/188849754-84729d33-6015-478f-8de1-d8de18c58292.png)
Live update draft, either diagonal line pattern or just lighter blue

#### Proposed behavior on Node Size and Disk Size fields (and others that behave the same...) 
grey out options in the dropdown that would go over quota, if possible add tooltip "Blocked by project quota" 

#### Expand feature to include external resources
add this as an option to each project quota (checkbox like) requires kubermatic/kubermatic#xx 

### Behavior Pass
Intended behavior: block creation of resources that would surpass the Quota
What happens if two resources are created at once? Both are created. The Quota gets overdrawn.

**Comment by KhizerRehan** [comment]
Backend PRs 
- [Kubevirt resource quota calculation #5478](https://github.com/kubermatic/dashboard/pull/5478/files)
- [Resource quota calculation #5315](https://github.com/kubermatic/dashboard/pull/5315/files
