### ISSUE TITLE
Request API endpoint to generate OIDC Kubeconfig secret

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/dashboard#5008]
Before being able to use the terminal, frontend should make a request to `/api/v2/kubeconfig/secret?cluster_id={cluster_id}&project_id={project_id}&user_id={user_id}`, so the user will be redirected to login page.

More details in the description of the PR: https://github.com/kubermatic/kubermatic/pull/10102

**Comment by KhizerRehan** [comment]
This ticket has already been catered in [PR: Integrate web terminal to user cluster #4492](https://github.com/kubermatic/dashboard/pull/4492/files#diff-9dfbe9b64b6dbc034af8927c1082a2af58fedd51e1b9d43810fc6859422b1704R233)
/close
