### ISSUE TITLE
Support New Limited Data From List Endpoint for Apps

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/dashboard#5012]
**What would you like to cleanup?**:

Currently when running a GET without any specifier for AppDefs/AppInstalls, the whole object is returned. Given that there can be a lot of objects for AppDefs (aka a large catalogue) or a large values field for AppInstalls, we made the decision to limit the data in the BE.

However currently the FE only calls GET without any specifier and stores all the data locally for further use. This will not work anymore as not all data is included in that call anymore. Instead a flow similar to this is required:

AppDefs: User wants to add a new App → "List" Request to display catalogue → User selects an App → Get Request the selected App to obtain all the data
AppInstalls: User visits the Applications Tab of their cluster → "List" Request to display list of Installations → User edits an existing App → Get Request the selected App to obtain all the data

A PR from the BE side is already open to test against
https://github.com/kubermatic/kubermatic/pull/11005

**Comment by ahmedwaleedmalik** [comment]
@SimonTheLeg Please add the new URLs(if any) here and maybe some sample data regarding what has changed.
