### ISSUE TITLE
Edit Dialogs Confirm Button Pass

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5084]
- [x] Change confirm button in edit dialogs to "Save Changes" or "Save [other applicable term]" of the following list
![image.png](https://images.zenhubusercontent.com/5d00e804f425650e637ab800/1e9c0318-0666-4c18-8106-3048c064d6a9)

**In Project**

Edit Addon
Edit Application
Edit Member 
Edit Service Account

**In Admin Panel**
Edit Datacenter
Edit Preset Provider
Edit Constraint Template, Edit Default Constraints, Edit Allowed Registry
(Not sure if Edit MLA Rule Group exists)
Edit Schedule Configuration
Edit Project Quota

**Comment by KhizerRehan** [comment]
@cschieder @ahmadhamzh 
what about these places?

- Configure Metering (https://dev.kubermatic.io/settings/metering)
- Edit Group Dialog (https://dev.kubermatic.io/projects/wzgqffwsnm/members)

**Comment by cschieder** [comment]
@KhizerRehan Metering can stay as is, and for group dialog and provider dialog we do the same change as described above
