### ISSUE TITLE
Edit MD Dialog UI/UX Enhancements

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5085]
- [x] remove name text field (it's not editable and we have it in the description of the modal anyway)
![image](https://user-images.githubusercontent.com/49145827/189060109-7067564a-6726-48c4-b794-98f70170b647.png)

- [x] put replica and kublet version, and disk type and disk size on one line if possible (see screenshot at the top) 
- [x] instead of a "Show Hide Advanced Settings" bottom left we should use the unfoldable element we use elsewhere
![image](https://user-images.githubusercontent.com/49145827/188420022-760f8a7b-7f40-4b93-8ceb-4764cae40517.png)

- [ ]  Add "cut off shadow" to indicate scrollable area 
![image](https://user-images.githubusercontent.com/49145827/189059005-86595a4f-3b28-4627-8731-0bffb598a850.png)

Note:
when hiding and unhiding advanced settings or the like the "changed node specification nodes will be recreated" message shouldn't appear, in other words, only make that message appear when it makes sense and when it actually happens

**Comment by ahmadhamzh** [comment]
third point `Add cut off shadow to indicate scrollable area` will be done in https://github.com/kubermatic/dashboard/issues/5202
