### ISSUE TITLE
Fix e2e tests for release branches

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#5104]
**Which jobs are failing?**:
`pre-dashboard-test-e2e` across all active release branches is flaky and for `release/v2.20` doesn't seem to pass at all.

**Which test(s) are failing?**:

```
1) DigitalOcean Provider
       should verify that there are no clusters:
     CypressError: Timed out retrying after 600000ms: `cy.wait()` timed out waiting `600000ms` for the 1st request to the route: `default-6`. No request ever occurred.
```

```
1) KubeVirt Provider
       should wait for the cluster to be ready:
     AssertionError: Timed out retrying after 600000ms: Expected to find element: `.cluster-name`, but never found it.
```

Among others. Check job history, it appears that various tests are failing: https://public-prow.loodse.com/job-history/gs/prow-dev-public-data/pr-logs/directory/pre-dashboard-test-e2e.

**Since when has it been failing?**:

Unclear, has been a problem for several releases.

**Prow link to failing test**:

https://public-prow.loodse.com/job-history/gs/prow-dev-public-data/pr-logs/directory/pre-dashboard-test-e2e

**Reason for failure**:

Failing test cases

**Anything else we need to know?**:

/

**Comment by Waseem826** [comment]
I've marked E2E tests optional in `release/v2.19` and `release/v2.20` branches to smooth the release process a bit. I'm not closing this issue in case we want to further investigate and fix flaky tests.
