### ISSUE TITLE
Implement expiration refresh functionality for the web terminal UI

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/dashboard#5146]
Websocket server will start to send expiration messages 5 minutes (1 minute interval) before the user web terminal pod expires (total expiration time: 30 minutes). The message will include the expiration time. Message example:
```
{"Op":"expiration","Data":"2022-10-26T19:47:17Z"}
```
At that time, UI should inform the user that the terminal is about to expire and ask if they want to extend the usage time.
If the user confirms the expiration extension, the websocket client should send a message to the server, like this:
```
{"Op":"refresh"}
```
To avoid permanent resources deployed in the backend, there is a limit in the number of refreshes (48). If the client sends a refresh message after the limit is reached, the server won't refresh the expiration anymore and will respond:
```
{"Op":"msg","Data":"REFRESHES_LIMIT_EXCEEDED"}
```

**Comment by KhizerRehan** [comment]
/close 
This ticket is already done as PR was not linked hence it didn't closed automatically.
