### ISSUE TITLE
Test Web Terminal - Release 2.22

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#5191]
## Testing Procedure user story

**Web Terminal for user cluster**

**Pre-Requisites:**
- Add interface option to enable/disable the web terminal. In order to access terminal following options need to be enabled.
	- Enable OIDC Kubeconfig (Used for OIDC authentication + Generation of KubeConfig secret in order to access the terminal). 
	-  Enable WebTerminal ( By default this feature is disabled in "Feature Gates" so if someone needs to access terminal it should be explicitly enabled from "Admin/Interface" page

**Note:**  
- Web Terminal feature for the **user** clusters  and this web terminal is only available for KKP managed clusters for all providers.
- Web terminal button is **not** available for External Clusters.
- In case Admin tries to **disable** "Enable OIDC Kubeconfig checkbox -> Enable Web Terminal feature will be disabled too.

### Web Terminal General Testing
- [x] Try to create user cluster e.g AWS provider
- [x] Check if OIDC and Web Terminal checkboxes are enabled in order to show "Web Terminal" button in User Cluster details page.
- [x] Make ensure Cluster is Healthy in order to access Web Terminal.
- [x] Try to connect to Web terminal
	- [x] On **First Time** access it will redirect to "dex" authentication user will try to authenticate. Meanwhile user is shown a placeholder image _"Please wait, authenticate in order to access web terminal..."_
	- [x] Once user is authenticated it backend will try to check few checks and will connect to user cluster POD in order to run shell command in a shell.
	- [x] Once user is authenticated it will display _"Please wait, provisioning your Web Terminal pod..."_ message.
	- [x] On Success of Web terminal with user cluster following message will be displayed.

```
Welcome to Web Terminal! Type "help" to get started.
Your KKP cluster in this session is set to <cluster-name>
```
### Web Terminal Extend Session Testing

- [ ] Default session timeout for a web terminal is 30mins but reaching on 25mins it should display warning to user that 
_"The web session will expire soon"_  and allows to extend session for next 30mins.

Note: Above feature will be very cumbersome to test and wait in order to test you can configure parameters locally to some lower values and then try and test by running api locally.

[PR#5353 Add refresh functionality for the web terminal U](https://github.com/kubermatic/dashboard/pull/5353)

```go
podLifetime 
maxNumberOfExpirationRefreshes, 
remainingExpirationTimeForWarning, 
expirationCheckInterval
```

## Acceptance Criteria
- [x] Web Terminal button should be visible on cluster details page
- [x] On Authentication success Web terminal should be connected to user cluster
- [x] User can run `kubectl` commands with in terminal to get information about cluster details e.g
    - Deployments, Replicaset, Namespaces, Pods information
- [x] Web Terminal is accessible in two option
    - [x] As Overlay with user cluster details page
    - [x] As Page terminal allows to open in new page with option "Option in new tab" from terminal toolbar.
    - There are **Two** Layout TypeS of User cluster Web Terminal 
        - Overlay -> Within cluster details page.
        - Page 	 -> Open in sep route or path as complete page for web terminal
- [x] Web Terminal allows to have "Reconnect" functionality to reconnect to user cluster when session is timeout. Following messages is displayed in status toolbar _"The connection to your Web Terminal was lost."_.
- [ ] Session extend should work as expected default session extension is 30mins.

### Other Features
- [] Check the API documentation

**Comment by ahmadhamzh** [comment]
the webterminal is not stick to the button is there a reason for that 

![Screenshot from 2023-01-23 13-27-58.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/c47cb1b9-4545-4991-9cf2-5cbbcbbb0221)

**Comment by ahmadhamzh** [comment]
the session seems to be lost connection in few minutes 

![Screenshot from 2023-01-23 13-34-03.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/8b3ad2ee-7a9d-43cb-9c08-8aac1ce6e68c)

**Comment by ahmadhamzh** [comment]
the open terminal in new window button actually don't open new window 
it's just open the `https://dev.kubermatic.io/projects/2bmv54j85g/clusters/whzbzkfqlc/terminal` path in the same window

**Comment by ahmedwaleedmalik** [comment]
@ahmadhamzh I have updated the image for web terminal with https://github.com/kubermatic/dashboard/pull/5699. So maybe we need to do some sanity testing again. Although the only thing that changed is `kubectl` version so I'm not expecting any issues etc.

**Comment by ahmadhamzh** [comment]
seems all good
