### ISSUE TITLE
Test Display groups on project overview page - Release 2.22

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#5192]
## Testing Procedure user story

**Display Group Project Bindings in Overview Page**

**Note**: In order to test this feature user needs to be part of any `groups`. So that any project listed under that group will be available to **user**  to be part of that group.

e.g:
-  Group -> `kubermatic:development`
- If Project binding is created and **Project B** is part of `kubermatic:development` then all projects under this group will be visible to User for which group project binding created.

### How to Create Group Project Bindings

- [x] Login if user is admin or **owner** of that project.
- [x] Navigate to `Groups` tab 
- [x] Try to Create Group Project binding by adding `Group Name` e.g  `kubermatic:development`
- [x] Try to login with github account e.g <name>@kubermatic.io. Any user who is part of kubermatic organizaiton will have ` kubermatic:development` this group listed and any project to which binding is added will have an access to this project when he/she logins.

**Note for Testing**: 

-  Kubermatic github org has **predefined** groups that will be returned in bearer token and use that group name
when creating binding. Once binding is created the project for group projects binding has been done will be shown.
-  Projects that will be part of that groups can be seem from UI.
- Copy **bearer** token and try to decode JWT token -> https://jwt.io/ you will see `groups` under payload data.
- Groups Should not be displayed for **Community Edition** 

### Group Project Bindings General
- [x] Navigate to User Settings `/account`
- [x] Check if Group project bindings exists under `OIDC Groups`
- [x] Check projects under that groups bindings are listed on projects list

### Group Project Bindings **(role: owners)**
- [x] Check if project card shows correct role 
- [x] Check logged in user is not an **Admin**
- [x] Members/Service Accounts/Groups tabs will be active for `role: owners`
- [x] User is allowed to Add `Group` bindings similar to User bindings from Groups Tab
- [x] User should see both `Owners & Members` and **Groups** on dashboard (Overview) page under "Access" heading

### Group Project Bindings **(role: viewers / role: editors)**
- [x] Check if project card shows correct role 
- [x] Check logged in user is not an **Admin**
- [x] Members/Service Accounts/Groups tabs should be `disabled` for `role: viewers/ editors`
- [x] User should see `Owners` on dashboard (Overview) page under "Access" heading

## Acceptance Criteria
- [x] Add/Edit/Delete group bindings should work
- [x] User under selected group must display project if any binding exists.
- [x] Members and Groups are displayed for `Owners` and if User is Admin
- [x] Members and Groups under dashboard overview page shouldn't be visible for role other than `owners/admin`.
- [x] Members/Groups/Service Accounts should be **disabled** for **role: viewers/editors**
- [x] Following API calls shouldn't be triggered to fetch details for Members, Groups and SA **role: viewers/editors** 
      - /groupbindings
      - /users
      - /serviceaccounts
- [x] Feature is ONLY available for Enterprise edition
     - [x] Groups tab should only be visible on EE 
     - [x] Group Bindings should not exist on Dashboard (Overview) page for ANY role (owners/editors/viewers)

### Other Features
- [] Check the API documentation

**Comment by ahmedwaleedmalik** [comment]
We need to test this again on the testing environment, instead of our dev environment.

**Comment by ahmadhamzh** [comment]
all work fine
