### ISSUE TITLE
Add "cut off shadow" to indicate scrollable area

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#5202]
this issue is extended to Dialogs UI/UX Enhancements to add a shadow line in the dialogs that have a scrollbar.

reference https://github.com/kubermatic/dashboard/issues/5085

https://user-images.githubusercontent.com/49145827/189059005-86595a4f-3b28-4627-8731-0bffb598a850.png

**Comment by cschieder** [comment]
![image](https://user-images.githubusercontent.com/49145827/200305387-734bd803-48fc-4978-aaae-07269615b844.png)
alternatively to the shadow we can add a thin line like this

**Comment by ahmadhamzh** [comment]
> ![image](https://user-images.githubusercontent.com/49145827/200305387-734bd803-48fc-4978-aaae-07269615b844.png) alternatively to the shadow we can add a thin line like this

which one you think is better ?

**Comment by Waseem826** [comment]
IMO adding a border line is better and easy to implement.

**Comment by ahmadhamzh** [comment]
the line should be shown in case there is a scroll able content in the dialog or in all cases ?

**Comment by Waseem826** [comment]
IMO it should be shown in all cases.
