### ISSUE TITLE
Allow Cluster Template Editing

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5241]
NICE TO HAVE

Add "edit" icon in between "create from template" and "delete" icon on the table
on click of table open wizard, functionality is very very similar to #4948 

Behavior: 
will open the wizard with every parameter prefilled from the template (except for credentials)
Any prefilled parameter can be edited, if there is data that is dependant on the prefilled parameter, and the prefilled parameter gets changed, we clear the dependant data upon change of the prefilled data

On last step show buttons like this
![image](https://user-images.githubusercontent.com/49145827/200826627-a720a13e-ad91-4312-a7ee-39923467b59d.png)

**Comment by ahmedwaleedmalik** [comment]
I already had this in my TODO list when I evaluated the Epic :D

**Comment by cschieder** [comment]
perfect :D
