### ISSUE TITLE
Option to enforce custom disk for OpenStack machines

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#5243]
**What would you like to be added? / User Story**:
As a user, I'd like the ability to enforce the usage of custom disks for OpenStack machines. 

Currently, when the custom disk option is not checked ephemeral storage is used for the machines and the chosen flavor decides the size of the machine. Although, when this field is checked, volumes are used for storage.

Reference: https://github.com/kubermatic/machine-controller/blob/release/v1.54/examples/openstack-machinedeployment.yaml#L147

It would be nice having the ability to force the root disk to always be created as a volume(cinder volume).

NOTE: This change is required solely for the dashboard.

**Comment by csengerszabo** [comment]
@ahmedwaleedmalik just one question would we be able to override the enforcement somehow in some special cases even?

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik just one question would we be able to override the enforcement somehow in some special cases even?

There will be an option in the admin settings to toggle this.
