### ISSUE TITLE
Editing Version for Applications

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/dashboard#5251]
**What would you like to be added? / User Story**:
We want to allow users to be able to update the version of an already deployed Application. Both Downgrading and Upgrading should be possible.

The backend for this is already in place. For the FE the flow could look like this:
* fetch the ApplicationDefinition that belongs to the selected ApplicationInstallation
* grab all available versions out of the ApplicationDefinition
* display the user a list of all available versions
* _user selects a version_
* Run a PUT request against `{{URL}}/v2/projects/{{PROJECT_ID}}/clusters/{{CLUSTER_ID}}/applicationinstallations/{{NAMESPACE}}/{{APPINSTALL_NAME}}`
 The request's body contains the full ApplicationInstallation object with the `spec.applicationRef.version` set to what the user selected

**Comment by cschieder** [comment]
Let's make it look like what we have in the add dialogue, so like this 
![image](https://user-images.githubusercontent.com/49145827/201365365-b9286dd9-553a-4e9a-9ad3-96d4641ed363.png)
