### ISSUE TITLE
Unlikely Error Message

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#5281]
### What happened
A user with the rights `Editor`, get an error message, if an service account (with rights editor) is attached.

```
users.kubermatic.k8c.io "serviceaccount-ldnjj7mhhd" is forbidden: User "customer-admin@k8.intra" cannot get resource "users" in API group "kubermatic.k8c.io" at the cluster scope
```
![Overview in Project 'RKI DEV' 2022-11-16 08-45-16](https://user-images.githubusercontent.com/4659261/202119270-1855c63d-0b7d-4bd3-813a-e1d87689a032.png)

### Expected behavior
No Error, he could download the service account token / or create a token

### How to reproduce
- Create project with user Editor
- Create Service Account for Editor
- Login with editor User

### Environment
- UI Version:  v2.21.3
- API Version: v2.21.3
- Domain: customer
- Others:

**Comment by KhizerRehan** [comment]
@pkprzekwas if i remembered correctly, it was decided user with only `owners` permission is allowed to access 

Following tabs + API calls to do will be restricted.

Secondly, was the permission changed directly from CLI? if it is then due to polling the previous API kicked in and it resulted into failure But if it is continuously getting error then probably it is an issue.

**Comment by toschneck** [comment]
@KhizerRehan 

> if i remembered correctly, it was decided user with only owners permission is allowed to access
> Following tabs + API calls to do will be restricted.
ok, this would be fine I guess, but then other users shouldn't get errors


> Secondly, was the permission changed directly from CLI? if it is then due to polling the previous API kicked in and it resulted into failure But if it is continuously getting error then probably it is an issue.
No it was created about the UI as Owner. After a Owner creates a Service Account EVERY other role get the error thrown in consistent loop, this is no a good UX

**Comment by toschneck** [comment]
@KhizerRehan  any news for this?
