### ISSUE TITLE
Test Admin Panel Seed Configurations - Release 2.22

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#5286]
## Testing Procedure user story

**Display Seeds Configurations**

**Note:**  
- Add new section in admin settings to view seed configurations. 
- User can only **View** seed configuration **ONLY**.
- [Admin Panel Seed UI implementation to display table #5285](https://github.com/kubermatic/dashboard/pull/5285)

#### List Page
- [ ] Navigate to list page and check all seeds general details are shown:
   - Available seeds
   - Available clusters per seed
   - Available providers per seed
   - Available datacenters per seed
   
#### Details Page
- [ ] Navigate to any seed details page by clicking any seed.
- [ ] Validate Seed Panel should display
    - Total Providers
    - Total Datacenters
    - Total Clusters
    - Location
    - Creation Time
- [ ] Display All providers associated to seed and it should display:
    - Total Datacenters associated to each provider.
    - Total Clusters sum for all datacenters.
- [ ] Expanding each provider panel should display:
    - Datacenter name and associated cluster on that datacenter

## Acceptance Criteria
- [ ] List page should display all available seeds.
- [ ] Details page should display seed overview details (providers, datacenters, clusters associated / seed)

**Comment by ahmedwaleedmalik** [comment]
<img width="1517" alt="Screenshot 2023-01-31 at 02 14 57" src="https://user-images.githubusercontent.com/18264334/215596671-46878185-2031-4e0a-8aba-3c35f81c6b76.png">

Sorting doesn't work.

**Comment by ahmedwaleedmalik** [comment]
I have already tested this with https://github.com/kubermatic/dashboard/issues/5711 and it looks good.
