### ISSUE TITLE
Autocomplete Fixes

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5299]
### To Do
- [x] make the filter work based on input that happens **in the field** and not in the dropdown below the field 
- [x] fix what makes the horizontal scrollbar appear
- [x] fix alignmet (should left align with the field) 

### Intended Behavior
![image](https://user-images.githubusercontent.com/49145827/203059769-e1c869e6-0d45-48a7-8079-54db1b2bd151.png)
https://material.angular.io/components/autocomplete/overview

### In UI (Cluster Templates, Cluster Create Kubevirt Step 4)
![image](https://user-images.githubusercontent.com/49145827/203059927-622d77ed-420a-400e-81b7-9056fb39f43b.png)
![image](https://user-images.githubusercontent.com/49145827/203060065-ad9be682-de5a-487c-b031-eca7bf627e71.png)

**Comment by Waseem826** [comment]
> make the filter work based on input that happens in the field and not in the dropdown below the field
I think this wouldn't work with normal dropdowns because user would think that the field is editable and they can input any value. This behaviour is only correct when we want to accept custom value in the field (with some helper values in the dropdown).
