### ISSUE TITLE
Customizable cluster templates - Release 2.22

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#5343]
## Instructions
**_TBD_**

## References
Ticket: https://github.com/kubermatic/kubermatic/issues/10549
PR: https://github.com/kubermatic/dashboard/pull/5295

**Comment by ahmedwaleedmalik** [comment]
One issue to reproduce, evaluate, and probably fix

https://github.com/kubermatic/dashboard/pull/5631#discussion_r1092948700

**Comment by Waseem826** [comment]
I've noticed that for some providers, dropdown values (whose options are fetched on the basis of credentials) on Initial Nodes step are reset to default values after API call finishes. But I guess that's fine because those values depend on the credentials which are not saved in the template. WDYT?

**Comment by Waseem826** [comment]
Found some small issues which are already fixed or in progress.
