### ISSUE TITLE
Initial Node step is broken for editing Cluster Templates

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#5364]
### What happened
https://github.com/kubermatic/dashboard/pull/5258 broke the edit cluster template workflow. There are errors in the `Initial Node` step in the wizard. 

### How to reproduce
1. Create a cluster template
2. Edit Cluster Template
3. On the `Initial Nodes` step, the `next` button will be disabled since the form state is not valid.

**Comment by ahmadhamzh** [comment]
@ahmedwaleedmalik can you check that again but make sure the preset you chose is valid (make sure there is no error notification when chose a preset), because it work fine with me, but maybe we need to make sure that `next` button is not valid in case of preset error

**Comment by ahmadhamzh** [comment]
ok it seems like it's not working on aws i try DO and GCP and alibaba they all work but aws is not working

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik can you check that again but make sure the preset you chose is valid (make sure there is no error notification when chose a preset), because it work fine with me, but maybe we need to make sure that `next` button is not valid in the preset step in case of preset error

The issue is reproducible, just create a cluster template, `edit` the cluster template and it won't let you move forward from the `Initial Nodes` step. You can try it with the ClusterTemplate `m8xc7w84pw`.

With https://github.com/kubermatic/dashboard/pull/5258, we modified it in a way that now restricted system labels are being returned for the Machine Deployments. Which is something we don't allow setting from the front-end. For example, 
`kubernetes.io/cluster/<cluster-template-id>` on the machine deployment.

**Comment by ahmedwaleedmalik** [comment]
![Screenshot 2022-11-30 at 10 15 20 PM](https://user-images.githubusercontent.com/18264334/204864857-93e92de9-3303-4179-b341-5ad0e77e5c26.png)

These values should never be there. Even if it lets you go forward from here.
