### ISSUE TITLE
Viewer UX

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5406]
- [x] add tooltips on every disabled button and action `This action is not available for viewer role users.`
- [x] remove hover from dropdown options that aren't available
![image](https://user-images.githubusercontent.com/49145827/206420287-3c9ce789-6a5f-4d5d-a427-f17d71c4b17e.png)

- [ ] I get this error on the project page and I don't know what it wants me to do 
![image](https://user-images.githubusercontent.com/49145827/206420553-3e75bc88-6319-414c-bf72-b7a99ecb84f0.png)

- [ ] this error when I go to the groups page, and it pops up several times rather than once, even after switching back to another page the error still appears ~2 times
![image](https://user-images.githubusercontent.com/49145827/206460510-945647b5-aa8e-4eb9-953f-eb0c24d90fbd.png)

- [ ] when creating a cluster template the last step shows the button as functional dark blue, only once you click create cluster you run into the permission error  the user gets stuck with a loading spinner on a cluster that won't create. This task would become irrelevant if #5026 is implemented,
![image](https://user-images.githubusercontent.com/49145827/206421442-fbb8b9c6-d69c-462a-9095-f6e13de1edeb.png)

**Comment by ahmadhamzh** [comment]
so i think in this ticket the remaining issue is the first two 
cause the last one been changed as mention above `This task would become irrelevant if #5026 is implemented,`
and the other tow issue regarding group is been fix here #5563
