### ISSUE TITLE
Hide KKP-managed / CNI Applications in Applications dialog / list

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/dashboard#5440]
**What would you like to be added? / User Story**:

Recently, we added a new class of Applications, which are considered to be not third-party, but internal & managed by KKP ([more details in the proposal](https://github.com/kubermatic/kubermatic/blob/main/docs/proposals/cni-mgmt-via-applications.md#kkp-managed--kkp-internal-applications)). The only one such Application ATM is the Cilium CNI, which is automatically deployed when Cilium is chosen as the CNI for the user cluster.

- KKP-managed Applications can be distinguished by the presence of the `apps.kubermatic.k8c.io/managed-by` label which equals to `kkp` in the ApplicationDefinition resource (`/api/v2/applicationdefinitions/{appdef_name}`) ([see API reference](https://github.com/kubermatic/kubermatic/blob/main/pkg/apis/apps.kubermatic/v1/types.go#L27-L32))

As this Application is fully managed by KKP behind the scenes, it should not be shown in the list of applications available to install in the `Add Application` dialog (during cluster creation as well as during the cluster operation):

![Screenshot 2022-12-16 at 11 11 35](https://user-images.githubusercontent.com/15926980/208158746-80df98e5-84c5-49ad-91bd-36792da81924.png)

However, we still want to show it (and make the values editable) in the list of installed Applications in an existing cluster, just hide it by default and show it only when some "show internal" checkbox / toggle switch is selected (please clarify the exact design with @cschieder ). Also, it should not be possible to delete the internal Application from the UI (only editing should be possible).

![Screenshot 2022-12-16 at 19 11 57](https://user-images.githubusercontent.com/15926980/208163364-f1d50fd6-9be3-4236-9b4a-94ddf75ff33c.png)

**Comment by Waseem826** [comment]
When we fetch list of Application Definitions we only get `name` and `description` so in order to get `labels` we'll need to fetch details of all application definitions which is not a good approach IMO.
```
{
  "name": "cilium",
  "spec": {
    "description": "Cilium CNI - eBPF-based Networking, Security, and Observability"
  }
}
```

I propose we include labels as well in this data (`GET /api/v2/applicationdefinitions`). @SimonTheLeg wdyt?

**Comment by Waseem826** [comment]
Also, we're not getting `labels` inside ApplicationInstallation (`GET /api/v2/projects/{project_id}/clusters/{cluster_id}/applicationinstallations` as well as `
/api/v2/projects/{project_id}/clusters/{cluster_id}/applicationinstallations/{namespace}/{appinstall_name}`). 
I propose we add `labels` in response of both requests.

On a side note, `/api/v2/projects/{project_id}/clusters/{cluster_id}/applicationinstallations/cilium/cilium` is giving `404`:

```
{
  "code": 404,
  "message": "applicationinstallations.apps.kubermatic.k8c.io \"cilium\" not found"
}
```

**Comment by rastislavs** [comment]
Thanks for looking at this @Waseem826 , the proposed changes to the endpoints were added in https://github.com/kubermatic/dashboard/pull/5491

> On a side note, `/api/v2/projects/{project_id}/clusters/{cluster_id}/applicationinstallations/cilium/cilium` is giving 404

The app is deployed in the `kube-system` namespace, not `cilium`, so it should be: `/api/v2/projects/{project_id}/clusters/{cluster_id}/applicationinstallations/kube-system/cilium`

**Comment by cschieder** [comment]
Hi, for the design side of things could you let me know how prominent this feature should be? Let me share some thoughts so you know what I mean: 

1. Allow toggle directly where you indicated for all users (easy to access, relatively prominent) 
2. Allow toggle where you indicated only to project owners or admin (normal users don't see it, but for relevant people it's still easily accessible and visible) 
3. Allow toggle in the Admin or User Settings, it's more hidden in general, something we do not intend users to see or use much. Additionally maybe the Admin can decide if the toggle should be visible to all, visible only to admins or completely hidden. 

Of course other solutions are also possible, that was just the first options that came to mind :)

**Comment by rastislavs** [comment]
@cschieder great question, this should be visible only for Admin users, not regular cluster users. To me, the option 2 looks best:

> 2. Allow toggle where you indicated only to project owners or admin (normal users don't see it, but for relevant people it's still easily accessible and visible)

**Comment by cschieder** [comment]
Design, toggle only available to admins, add "system" tag to the respective applications:
![image](https://user-images.githubusercontent.com/49145827/210355840-2bc541cb-a46b-4fd5-9345-4003ea15205a.png)

Tooltip: 
> System Applications are managed by KKP. 

Instead of "System" we can also say "Internal" or perhaps even "KKP" input welcome

**Comment by rastislavs** [comment]
@cschieder "System Applications" sounds good to me, after all, they are usually running in the `kube-system` namespace.

**Comment by Waseem826** [comment]
@rastislavs should we also hide system applications from API response? With some query parameter
