### ISSUE TITLE
Scale to 0 Machine Deployment should be allowed

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#5463]
**What is the problem, where is it and why is it an issue?**
Scale 0 has an use case, to keep config and scale down e.g. overnight to delete all machines. As it is possible via kubectl cli it should be also possible via UI!

![Machine Deployment 'tobi-canal' in Cluster 'tobi-test-canal' in Project 'KKP Playground' 2022-12-22 14-25-31](https://user-images.githubusercontent.com/4659261/209144133-2abcc812-5808-4f3b-a26e-e61d511f44b5.png)

**Suggest how to fix it, if possible**

Allow scale to 0. If wanted show hint message "this could make all workload inaccessible".

**Comment by csengerszabo** [comment]
Question is whether this is only a validation issue or some modifications have to be done in the API as well to work with the 0 value

**Comment by Waseem826** [comment]
@csengerszabo this minimum value (of `1`) check was recently added on UI so it might be that it always allowed 0 value.

**Comment by csengerszabo** [comment]
Okay so I guess we just need to modify the interval of this new validation to [0-x] from the current [1-x]
