### ISSUE TITLE
Test Cluster Service Account UI changes  - Release 2.22

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#5486]
## Testing Procedure user story

**Notes for tester:**:
Someone with backend knowledge should test this ticket as it checks permission once binding has set at cluster/namespace level based on kubeconfig which can be donwloaded after SA can be created at Cluster level

Following payload is just decoded from https://jwt.io/ site:
- Steps to check SA payload
- Download kubeconfig from SA table
- Copy token from `kubeconfig`

```yml
contexts:
- context:
...
users:
- name: sa-XXXX
  user:
    token: XXXXYYYYZZZZ

```

Following Payload represents service account based for user cluster based on KUBECONFIG.

```json
 "kubernetes.io/serviceaccount/namespace": "xxx,
  "kubernetes.io/serviceaccount/secret.name": "xxx",
  "kubernetes.io/serviceaccount/service-account.name": "xxx",
  "kubernetes.io/serviceaccount/service-account.uid": "xxx,
  "sub": "xxx
```

### Context
This Feature covers UI for service account based **Kubeconfig** for user cluster and updates UI for User/Group binding in order to view User or Group binding user needs to select from dropdown to view specific type of binding in tables.

There are similar to KKP service accounts but purely Kubernetes objects.

The workflow is:
- Create the service account in the desired namespace in the user- cluster
- Give permission to the service account
- Download the Kubeconfig associated the service account.

**Pre-Requisites:**

- Create a running cluster and navigate to cluster details page
- Click on **RBAC** tab and you will find following options to add
	-  Add Service Account 	
	-  Add Binding (User/Group) (This feature existed before and should work as before only UI changes are reflected)

Adding a binding at the namespace  level for a service account will require these fields:

**Note:** New feature

###  Configure SA for any cluster
- [x] Make sure when no SA existed dummy placeholder text for user must be shown "No service accounts available.'
- [x] Create Service account by adding name and **Namespace** 
- [x] Newly created SA should be listed table

### Adding a binding at the cluster level for a service account 
- [x] Select Service account Namespace,  e.g. kube-system
- [x] Select Role, e.g. view
- [x] check permissions
  - [x] download the kubeconfig
  - [x] check view permission: `kubectl --kubeconfig <path_to_kubeconfig> get po -A` should return list of pods
  - [x] check can not edit `kubectl --kubeconfig run test--image ubuntu` should return an error

### Adding a binding at the namespace  level for a service account
- [x] Select Service account Namespace  e.g. kube-system
- [x] Select Role : e.g. namespace-admin
- [x] Select Namespace (on which we give permission), e.g. namspace-xyz
- [x] check permissions
  - [x] check can edit in namespace: `kubectl --kubeconfig -n <namespace-with-permission> run test--image ubuntu`  should work
  - [x] check can not edit in other namespaces: `kubectl --kubeconfig -n <another-namespace> run test--image ubuntu`  should work

### Removing a binding at the namespace  level for a service account
- [x] Expend the service account in UI and remove the permission with namespace scope
- [x] check permission has been removed `kubectl --kubeconfig -n <namespace-with-permission> run test--image ubuntu`  should return an error

### Removing a binding at the cluster level for a service account 
- [x] Expend the service account in UI and remove the permission with cluster scope
- [x] check permission has been removed `kubectl --kubeconfig get po -A`  should return an error

## Acceptance Criteria
- [x] Allow user to Add SA
   - [x] Allow to add binding at cluster/namespace level from table row with SA preselected in in SA Dropdown field
   - [x] Allow to download Kubeconfig specific to SA
   - [x] Allow to delete SA from table row.
	   - [x] Once you delete SA make alll bindings are removed (cluster/namespace) from table which is basically hidden under expansion panel.
- [x] Allow user to Add bindings at cluster/namespace level
	- [x] Make sure cluster/namespace level binding must appear on SA table 
	- [x] Allow to delete binding for specific to SA

### Other Features
- [] Check the API documentation

**Comment by KhizerRehan** [comment]
Hi, @vgramer I would like to review this ticker description and let me know if something needs to add .Along with this as far UI is concerned things looks it's working both creating + adding bindings but as far actual testing from backend point of view will require to some description or steps if this needs to be tested by UI folks to check if certain permission is not allowed than user shouldn't be allowed to do so,

**Comment by vgramer** [comment]
@KhizerRehan  i have updated the story to test the permission from a backend point of view.

**Comment by Waseem826** [comment]
Works as expected
