### ISSUE TITLE
Project Overview Follow Up

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5506]
- [ ] When expanding labels, the label icon shouldn't jump but remain at the same place. Show/hide labels should be available at the end of the line and move with the labels [Prototype](https://www.figma.com/proto/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?page-id=6391%3A42436&node-id=7928%3A108448&viewport=-19523%2C-575%2C1&scaling=min-zoom&starting-point-node-id=7928%3A108448)

![image](https://user-images.githubusercontent.com/49145827/210555853-d28f4864-ae61-4265-a9e6-655e73b88227.png)

- [x] Add edit project button

![image](https://user-images.githubusercontent.com/49145827/210555318-331497b8-1331-4713-93b0-e5858471cbfb.png)

- [x] Is it possible to change item spacing? right now the width is fixed, what I'd prefer is this: 

![image](https://user-images.githubusercontent.com/49145827/210229557-128b4aa6-ac3a-4a8d-94da-38b4a3ff3150.png)

- [x] Change dropdown from this:

![image](https://user-images.githubusercontent.com/49145827/210229030-4d28375e-27c0-4f14-850e-9cce4984c949.png)

- Remove Imports 
- Change Order
- Remove "Create" from some of the points

To this dropdown:
![image](https://user-images.githubusercontent.com/49145827/210554851-772661ec-b602-4431-a2de-847fe0af68af.png)

**Comment by Waseem826** [comment]
Regarding last point (about dropdown changes), I think we should also add `KubeOne Cluster` below `External Cluster` because its also a wizard.

**Comment by ahmadhamzh** [comment]
@Waseem826 regarding your comment kubeOne Cluster wizard is only for import kubeone cluster

**Comment by Waseem826** [comment]
ah, you're right because button label says "Create" so adding KubeOne would be incorrect.
