### ISSUE TITLE
Minor Layout improvements for the welcome screen

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#5511]
**What is the problem, where is it and why is it an issue?**
![2023-01-09 10_08_40-Projects — Mozilla Firefox](https://user-images.githubusercontent.com/127499/211274114-b142adfe-2e82-4aa3-9cc0-fb6fb8910f53.png)

**Suggest how to fix it, if possible**
* ~IMHO the button is too close to the link above it, it looks squished.~ (Fixed in https://github.com/kubermatic/dashboard/pull/5912)
* Maybe we can use the standard "link opens in new tab" icon instead of a plain `>`
* Also is the link replaceable? Do we know if all customers want to send their customers to _our_ not-whitelabelled documentation?

(Firefox on Windows 10)

**Comment by KhizerRehan** [comment]
Hmm, i am not sure what screen resolution it you have but as far i have tested on multiple screen it looks fine but may be edge case exist/

- **1400*900**
![1400*900](https://user-images.githubusercontent.com/17727069/211295263-56d12d39-09bf-439f-931e-bd733181f591.png)

- **1500 * 900**
<img width="1509" alt="1500 * 900" src="https://user-images.githubusercontent.com/17727069/211295280-cfc2b3fe-9afc-4f51-a727-766a19bbe84e.png">

**Comment by cschieder** [comment]
> IMHO the button is too close to the link above it, it looks squished.

Couldn't replicate it, for me it looks like it does for Khizer

> Maybe we can use the standard "link opens in new tab" icon instead of a plain >

We can do that, if we do, that change should be universal so we'd need to check other locations as well, like modals. 
![image](https://user-images.githubusercontent.com/49145827/211300223-dfddd0c9-470f-43cc-8860-f64838e3efe4.png)

> Also is the link replaceable? Do we know if all customers want to send their customers to our not-whitelabelled documentation?

Interesting question, again implies global effect as the same is true for other links as well and then it becomes a general product management question. @csengerszabo Do you have any input here?

**Comment by csengerszabo** [comment]
My opinion is: for this use case (linking to custom documentation) we have the custom link generation feature, and here we should link them to our documentation (as it currently works).

**Comment by cschieder** [comment]
### State of issue
Not Replicable: `IMHO the button is too close to the link above it, it looks squished.`
Possible, but global rework, maybe we should open another issue for it? low prio: `Maybe we can use the standard "link opens in new tab" icon instead of a plain >`
Largely stays as is, it is possible for us to change the wording from "our" to "KKP" documentation, maybe, would also be a global change: `Also is the link replaceable? Do we know if all customers want to send their customers to our not-whitelabelled documentation?`

**Comment by xrstf** [comment]
![Screenshot_20230110_133711](https://user-images.githubusercontent.com/127499/211553778-fcc54f87-7d9d-4e4c-ae91-7babd109c9c1.png)


Firefox 94.0.2 on Kubuntu, using dev.kubermatic.io
