### ISSUE TITLE
GCP Preset showing misguided/wrong error

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#5542]
### What happened
Creating GCP cluster and selecting Preset which throws an error regarding GKE cluster which is misguiding 

![image](https://user-images.githubusercontent.com/78943096/212565934-2ce67c24-03d5-4ff9-ba06-4a091b9a2467.png)

### Expected behavior
- If no GCP credentials exist in Preset error should be regarding GCP, not GKE.
- If GCP credentials exist then should not throw any error if the credentials are valid.

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by Waseem826** [comment]
As discussed with @imharshita , this error comes from backend in response to `/api/v2/projects/{project_id}/providers/gcp/{dc}/zones`.

```
{
  "code": 500,
  "message": "gke credentials not present in the preset loodse"
}
