### ISSUE TITLE
OPA integration: update UI to be able to specify enforcementAction on Constraint and default Constraint

### ISSUE THREAD

**Issue by vgramer** [kubermatic/dashboard#5578]
**What would you like to be added? / User Story**:
In kubermatic/kubermatic#1723  allows the user to define the enforcementAction on k8c constraint CR. The user should be able to do the same through the UI.

**Comment by Waseem826** [comment]
Looks like this has already been done in https://github.com/kubermatic/dashboard/pull/5626.
