### ISSUE TITLE
Test Import KubeOne Cluster Wizard - Test Release 2.22

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5585]
Test Import KubeOne Cluster wizard.

#### Wizard Steps

- [ ] AWS, Google Cloud and Azure providers are displayed.
- [ ] YAML editor accepts valid YAML value and displays error for invalid value.
- [ ] SSH Private is accepted in both plain text and base64 encoded format.
- [ ] Presets are displayed in Credentials Step.
- [ ] Preset field is disabled when credentials are entered and similarly credentials fields are disabled when a preset is selected.
- [ ] Cluster summary step displays all necessary information.

#### Import KubeOne Cluster

- [ ] Import AWS cluster using valid config and credentials.
- [ ] Import Google Cloud cluster using valid config and credentials.
- [ ] Import Azure cluster using valid config and credentials.
- [ ] After cluster import is successful, KubeOne cluster details page is opened.

#### KubeOne Cluster Details Page

- [ ] Correct status and all necessary information is displayed.
- [ ] List of Machine Deployments is displayed if any MD exists, otherwise list of Nodes is displayed.

#### KubeOne Machine Deployment Details Page

- [ ] All necessary information is displayed along with and Edit button to update MD.
- [ ] List of nodes are displayed.
- [ ] Basic cluster information is displayed along with back button on top of the page.

#### KubeOne Clusters List Page

- [ ] All imported KubeOne clusters are displayed in table and all columns are filled with details.

**Comment by ahmedwaleedmalik** [comment]
Doesn't seem to work:

```
invalid KubeOne manifest yaml
```

**Comment by imharshita** [comment]
> Doesn't seem to work:
> 
> ```
> invalid KubeOne manifest yaml
> ```

can you please share the manifest and other configuration used

**Comment by ahmedwaleedmalik** [comment]
> > Doesn't seem to work:
> > ```
> > invalid KubeOne manifest yaml
> > ```
> 
> can you please share the manifest and other configurations used to import the cluster

It was a vanilla manifest for AWS, nothing special.

This PR might fix that issue https://github.com/kubermatic/dashboard/pull/5742

**Comment by imharshita** [comment]
cc @ahmedwaleedmalik AWS and Azure import works,
but for GCE there is config error:

**Comment by imharshita** [comment]
> cc @ahmedwaleedmalik AWS and Azure import works, but for GCE there is config error: kubeone git:(main) ✗ kubeone kubeconfig --manifest ./k Error: configuration decoding kubeone.k8c.io/v1beta2, Kind=KubeOneCluster strict decoding error: unknown field "clusterNetwork.ipFamily", unknown field "clusterNetwork.nodeCIDRMaskSizeIPv4", unknown field "controlPlane.hosts[0].ipv6Addresses", unknown field "controlPlane.hosts[1].ipv6Addresses", unknown field "controlPlane.hosts[2].ipv6Addresses"

This should be resolved by this: https://github.com/kubermatic/kubermatic/pull/11914

**Comment by imharshita** [comment]
This should be resolved by this: https://github.com/kubermatic/kubermatic/pull/11914
