### ISSUE TITLE
Test KubeOne cluster upgrade and migration - Test Release 2.22

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5586]
Test KubeOne cluster version upgrade and container runtime migration.

#### Version Warnings

- [ ] If cluster container runtime is `docker` then a warning icon is displayed with tooltip message alongside the container runtime.
- [ ] If any Machine Deployment minor/major version is less than cluster version then a warning message with tooltip message is displayed alongside MD version (in MD list table and MD details page).

#### Cluster Version Upgrade

- [ ] When KubeOne cluster is in `Running` state and there are version upgrades available then an option to upgrade version is displayed similar to how its displayed for KKP Cluster and External Cluster.
- [ ] If all MD versions are up to date (with cluster version), then its possible to upgrade cluster version.
- [ ] When cluster version is upgrading, cluster status is updated accordingly.

#### Machine Deployment Version Upgrade

- [ ] Update Machine Deployment option is available in MD list.
- [ ] List of supported version upgrades is displayed in Update Machine Deployment dialog.
- [ ] When Machine Deployment status is being upgraded, MD status is updated accordingly.

#### Cluster Container Runtime Migration

- [ ] A `Migrate Container Runtime` option is available in menu on KubeOne cluster details page.
- [ ] When cluster container runtime is not `docker`, `Migrate Container Runtime` option is disabled and a tooltip is displayed.
- [ ] `containerd` option is available in Migrate Container Runtime dialog.
- [ ] Cluster status is updated accordingly when container runtime is being updated.

**Comment by Waseem826** [comment]
KubeOne cluster container runtime migration has been removed in https://github.com/kubermatic/dashboard/pull/5749.

**Comment by ahmedwaleedmalik** [comment]
So is this ticket complete now @imharshita? Since we already need to test update?

**Comment by imharshita** [comment]
> So is this ticket complete now @imharshita? Since we already need to test update?

close this as upgrade tested on AWS cluster
