### ISSUE TITLE
Test Applications API changes - Test Release 2.22

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5587]
Test Applications API changes on the UI.

**Note:** There are 2 known issues related to these changes:
- https://github.com/kubermatic/dashboard/issues/5223
- https://github.com/kubermatic/dashboard/issues/5598

## Testing Procedure

- [x] Application version and values are loaded in Add Application dialog.
- [x] Application details are loaded in Edit Application dialog.
- [x] Applications on cluster details page display all information in card/table view.

**Comment by ahmadhamzh** [comment]
one thing regarding show system applications
even when it's checked i still can't see the applications that are managed by kkp
is that a bug or i misunderstand something
@Waseem826 
![image.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/d21c6cc3-c9e1-461b-a231-6494545006b4)

![image.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/0114f265-a6b6-40ee-96b8-209f206c0438)

**Comment by Waseem826** [comment]
@ahmadhamzh  Currently we only have `cilium` system application which is added automatically when you select `Cilium` plugin on 2nd step of create cluster wizard.

**Comment by Waseem826** [comment]
Also, I think your attached screenshot is list of `applicationdefinitions` and we hide `cilium` from Add Application dialog because we don't want this application to be added manually.

**Comment by ahmedwaleedmalik** [comment]
We need to test this again on the testing environment, instead of our dev environment.

**Comment by ahmadhamzh** [comment]
seems all good
