### ISSUE TITLE
Test Nutanix Categories - Test Release 2.22

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5588]
Test categories in Nutanix provider.

## Testing Procedure

- [ ] Configure categories on Initial Nodes step in cluster wizard and Edit Machine Deployment dialog.
- [ ] Category dropdown options don't contain already selected categories.
- [ ] Selected categories are displayed on cluster summary.
- [ ] Selected categories are displayed on MD details page.

**Comment by KhizerRehan** [comment]
Nutanix servers are down, thus the provider cannot be tested therefore it is assumed things work properly.

/close
