### ISSUE TITLE
Test KubeVirt Changes - Test Release 2.22

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5589]
Test KubeVirt changes in cluster wizard.

#### Instance Type and Preference

- [ ] Instance Type dropdown displays options in 2 categories, `Standard` and `Custom`. If there are no options available in either of these categories then that category is not displayed.
- [ ] Preference is disabled until Instance Type value is selected.
- [ ] View button displays Instance Type and Preference (if selected) spec in a dialog.
- [ ] CPUs and Memory fields are disabled when Instance Type is selected.
- [ ] CPUs and Memory fields display values taken from `spec` of selected Instance Type.
- [ ] Instance Type and Preference values are displayed along with category on cluster summary step.
- [ ] Instance Type and Preference values are displayed along with category inside Node details on cluster MD details page.

#### Topology Spread Constraints

- [ ] Configure 1 or more topology spread constraints on Initial Nodes step in cluster wizard and Edit Machine Deployment dialog.
- [ ] When a value in first topology spread constraint is added, another empty row is added below.
- [ ] Duplicate `Topology Key` values are not allowed.
- [ ] Topology Spread Constraints are displayed on cluster summary step.
- [ ] Topology Spread Constraints are displayed in Node details on cluster Machine Deployment details page.

#### Operating System Image

- [ ] Custom Images are removed from the Settings step in cluster wizard.
- [ ] Operating System Image text field on Initial Nodes step is converted to a combobox.
- [ ] The word `Operating` in Operating System Image dropdown label is replaced by the selected Operating System.
- [ ] Dropdown options are filtered to only display values specific to the selected OS.
- [ ] Dropdown options and displayed selected value have `{version} - {link}` format.

**Comment by ahmedwaleedmalik** [comment]
Works as expected 🥳
