### ISSUE TITLE
Test Default Project Quota - Test Release 2.22

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5591]
Test support for default project resource quota.

## Testing Procedure

- [x] Configure default project quota on Admin Panel -> Manage Resources -> Project Quotas page.
- [x] CPU, Memory and Storage fields are all optional so it should be possible to configure either all, some or none of them.
- [x] When default project quota is configured, all projects which don't have any quota should have default quota applied to them automatically.
- [x] Projects with default quota should be visible in Project Quotas table and have `Default` label in front of project name.
- [x] If quota of any project is updated manually then `Default` label should be removed and updating default project quota should not effect that project's quota.
- [x] When default project quota is cleared, quota from projects with `Default` quota should be removed automatically.
- [x] If default project quota is configured, new projects created should have default quota applied to them.

**Comment by KhizerRehan** [comment]
**Issue-2:**
_When default project quota is cleared, quota from projects with Default quota should be removed automatically._

Removing of default quota doesn't removes default quota values from "default" project

https://user-images.githubusercontent.com/17727069/214861067-af97ea4b-b23f-44ac-80ca-a29c17eafd91.mp4

**Comment by lsviben** [comment]
> **Issue-1**
> 
> _When default project quota is configured, all projects which don't have any quota should have default quota applied to them automatically._
> 
> Default Quotas are applied by changing memory/storage it didn't reflected to project when defaulting is applied:
> 
> **Memory:**
> 
>  1cee1ef2a70397f4338eb5efa76d208b.mp4 
> **Storage:**
> 
>  99c3506d4e848410e27d8f259acf2c4d.mp4

this one should be fixed by: https://github.com/kubermatic/dashboard/pull/5609

the issue was that we were setting resource.Quantity directly in the default quota without setting the scale. Thats why values like 10 came up like 0 in the end. The fix makes the default quota use the same mechanism as when creating/editing resource quotas

**Comment by KhizerRehan** [comment]
**Issue-3**
Setting value like 1000, 2000, 3000 -> backend returns 1k, 2k, 3k as GB and UI fails to transform that value

https://user-images.githubusercontent.com/17727069/214895112-9e878cd6-ce2e-4af2-8e79-18b862066b60.mp4

**Comment by KhizerRehan** [comment]
**Issue-4:**
 _If default project quota is configured, new projects created should have default quota applied to them._

Steps i followed
- Set default quotas -> default applies to all projects which doesn't have any quotas configured
- Created new project to check if new project has default project quota but it is not applied as per what i apprehend this task.

https://user-images.githubusercontent.com/17727069/214896223-f5d59eb8-20f6-4f1e-8953-649c3efa97c5.mp4

**Comment by lsviben** [comment]
> #5609

the source of this issue is the same as for issue 1 and should be fixed by: https://github.com/kubermatic/dashboard/pull/5609

**Comment by lsviben** [comment]
> **Issue-4:** _If default project quota is configured, new projects created should have default quota applied to them._
> 
> Steps i followed
> 
> * Set default quotas -> default applies to all projects which doesn't have any quotas configured
> * Created new project to check if new project has default project quota but it is not applied as per what i apprehend this task.
> 
>  cc6d25c35331967bf5abe7c20c5c3ccb.mp4 
> However once again i changed value of default quota e.g I changed Memory -> **10 -> 12** this was the output.
> 
> <img alt="force-defaulting" width="1257" src="https://user-images.githubusercontent.com/17727069/214896596-9ef73e18-203a-4079-9f8d-e030aae5beeb.png">

@pkprzekwas or @hbernardo . I checked, and the default quota controller is missing a watch for newly created projects. So that should be added.


And for issue 2, the default quotas not being removed when the setting is removed I am not sure. But probably some bug in the cleanup code.

**Comment by ahmedwaleedmalik** [comment]
We need to test this ticket from the start again since there have been a lot of bug fixes for resource quota in the past few days. @KhizerRehan will that be okay for you?

**Comment by KhizerRehan** [comment]
**Issue-1:** fixed ✅ 

**Issue-2** 🐛 
https://github.com/kubermatic/dashboard/issues/5591#issuecomment-1405082610
<img width="1243" alt="not-cleared" src="https://user-images.githubusercontent.com/17727069/218948502-6ee8c6c9-3668-4e15-94b4-f04d0c129239.png">

OR
Removing memory from default project quotas

Expected to remove -> Memory default quota from all **default** projects
Actual:
- Applied default to project for which default project was not configured
- Existing **default** projects were not fixed

https://user-images.githubusercontent.com/17727069/218948935-302eaf1b-7aa5-48e9-a182-9dff066e60d6.mp4

**Issue-3** fixed ✅ 

**Issue-4** (Needs clarification)
- Case-1: When defaulting is applied and meanwhile new project is created as per description of ticket (defaulting should be applied auto) and should be listed in table which is not 🐛 
- Case-2: If some default value is `updated` than defaulting is applied to **not-default** projects which works fine.

Depending upon case it can be considered as fixed or not fixed. cc: @Waseem826

**Comment by KhizerRehan** [comment]
Works as expected
Last 2 points are also fixed 🚀 
/close
