### ISSUE TITLE
Test Cluster Template Creation, Edit and Customize - Test Release 2.22

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#5607]
TBD

**Comment by KhizerRehan** [comment]
@ahmadhamzh

**Comment by Waseem826** [comment]
I think these cases can be handled inside https://github.com/kubermatic/dashboard/issues/5343 so we should close either one of these issues and update description of the other.

**Comment by ahmadhamzh** [comment]
@Waseem826 yes i discuss it with @ahmedwaleedmalik and we should close this one
