### ISSUE TITLE
Quota UI Adjustment (Proposal) 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5608]
**Note: This issue is partially done already**

- [x] Too much spacing to bottom edge of card

![image](https://user-images.githubusercontent.com/49145827/214268678-7ee2f925-57f6-4274-ab9e-7512b54a01c6.png)

- [x] In Admin Panel -> Project Quotas table, hide all projects that do not have a quota configured/only show projects that have a quota configured
![image](https://user-images.githubusercontent.com/49145827/214852292-968ffc5b-b2c9-49c5-ae76-b535c8f8ea72.png)

- [x] Remove empty state quota text and icon and widgets, I think it would be cleaner if when there's no quota, there's no quota
![image](https://user-images.githubusercontent.com/49145827/214852626-8545f7ee-b189-4d7c-b307-5a841328f022.png)
That includes
- Project table/cards
- widget over cluster/md table
- edit MD, add MD
- create from cluster template
- create cluster wizard
- just in general, everywhere in the project, I'm not sure if I'm forgetting something

**Comment by Waseem826** [comment]
> Fix spacing on right side, add 5-10px

@cschieder this has been fixed.

![screenshot-dev kubermatic io-2023 01 26-22_14_15](https://user-images.githubusercontent.com/13975988/214903658-1ebca5ea-2c08-4582-9827-9c487ae53bdc.png)
