### ISSUE TITLE
VMware vSphere tag categories - Test Release 2.22

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#5637]
## Instructions
For vSphere, tags are used in the following components:
- Settings and initial nodes step in the wizard
- Add and Edit machine deployment dialog

### Checklist

- [x] Tags are optional
- [x] Tags and tag categories are fetched properly
- [x] Tags should be propagated from Settings to the Initial nodes step
- [x] In case we delete a tag in the Initial node step and update the tags in the Settings step, it should add the state back from the settings step
- [x] Tag and tag category, in combination, should be unique in the tag list.

## References
Ticket: https://github.com/kubermatic/dashboard/issues/5582

PR(s): 
- https://github.com/kubermatic/dashboard/pull/5636
- https://github.com/kubermatic/dashboard/pull/5629

**Comment by KhizerRehan** [comment]
Works as expected
/close
