### ISSUE TITLE
Test restrict preset to projects - Test Release 2.22

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#5639]
## the test scenario
* Go to Admin Panel >> Provider Preset.
* Open Create new Preset Dialog.
* on the First Step (Preset Step) Under Optional Settings Select the Projects you want the Preset to be Restrict to them.
* Create the Preset.
* Go to any of the Projects that the Preset is restricted to.
* try to Create a Cluster in that Project.
* on the Settings Step Check if the Preset is Displayed on the List of Presets.
* after that Go to a Project that the Preset is not restricted to and try to Check the Presets List, the Preset should not Displayed in the List 

## Acceptance Criteria 
- [x] Create a new Preset and bind it to several projects via UI
- [x] Verify you can use the Preset from projects that are on the allowlist.
- [x] Verify you cannot use the Preset from projects that are NOT on the allowlist.
- [x] Update the project allowlist and repeat verification for changed project allowlist.

**Comment by embik** [comment]
I've also opened https://github.com/kubermatic/kubermatic/issues/11807, FYI.

**Comment by ahmadhamzh** [comment]
that one would be for kubectl ? we still can't update the projects via UI

**Comment by embik** [comment]
Good point, I've updated the other ticket to clarify that. We can leave both open though, so someone looks at this from a UI perspective (in this ticket) and someone looks more at the underlying functionality (in the other ticket), if you want.

**Comment by KhizerRehan** [comment]
PUT request fails to update provider as projects property is empty IMO, in the case of "Edit Preset Provider" project is not required because preset bindings are done at the time of "Preset" creation.

How to produce:
- Create preset
- Add AWS provider in preset
- Bind to project
- Edit Provider Provider preset
- Try to (Update like Optional Restrictions Datacenter just for test) patch payload on backend fails 
payload
```json
{
    "metadata": {
        "name": "testing-project-binding"
    },
    "spec": {
        "projects": "", // <Causing the issue>
        "enabled": true,
        "aws": {
           // Credentials
        }
    }
}
```

Response:
```go
{
    "code": 500,
    "message": "json: cannot unmarshal string into Go struct field PresetSpec.spec.projects of type []string"
}
```

**Comment by KhizerRehan** [comment]
Works as expected 

> **POST** request fails to **create** preset as **projects property** is empty IMO, in the case of "Create Preset"
> 
> **How to produce:**
> 
> * Create preset
> * Add AWS provider in preset
> * **Don't** Bind to project since initial value is. "" which should. [] as payload accepts `[]`
> * Try to (Update like Optional Restrictions Datacenter just for test) patch payload on backend fails
>   payload
> 
> ```json
> {
>     "metadata": {
>         "name": "testing-project-binding"
>     },
>     "spec": {
>         "projects": "", // <Causing the issue>
>         "enabled": true,
>         "aws": {
>            // Credentials
>         }
>     }
> }
> ```
> 
> Response:
> 
> ```go
> {
>     "code": 500,
>     "message": "json: cannot unmarshal string into Go struct field PresetSpec.spec.projects of type []string"
> }
> ```
> 
> @ahmadhamzh apart from other above issue preset binding to projects seems to work fine.
> 
> Tested:
> 
> * Binding same preset to multiple projects
> * Binding different preset to make sure one preset is not available to another
> * Binding specific to Datacenter + Project (At time time of creation) to test if preset binding works for both
> * Disabling complete preset to make sure NONE is available
> * Disabling preset **specific** provider to make sure that preset is not available to provider in restricted project.
> 
> // Apart from this rest is fine.
> 
> * But In case of Add new preset without any **projects** binding resulted into error ❌ which i have **mentioned** above

Fixed and Tested:

**Comment by KhizerRehan** [comment]
Works as expected

/close
