### ISSUE TITLE
Test External Cluster AKS UI - Test Release 2.22

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#5665]
**What would you like to be added? / User Story**:
Test External Cluster AKS UI - Test Release 2.22

## Testing Procedure

**External Cluster Wizard**

A new button under clusters tab "External Clusters" has been added to create external cluster.

### Add External AKS Cluster via Wizard
- [x] Check if AKS provider exists
- [x] Add new AKS cluster via wizard
     - [x] Check cluster creation via preset
     - [x] Check cluster creation via credentials
- [x] Check new cluster is created and redirected to details page
- [x] Check all info is displayed under details page under cluster info
     - [x] Location
     - [x] Resource Group
     - [x] Cluster Version  ~~ (Kubernetes Version) 
     - [x]  Is-Imported
- [x] Check new cluster entry should exists in list page.

### Import External via Import Dialog

**Note**: Much done from UI side but things which are effected is listed here:

- [x] Check imported cluster entry should exists in list page 
- [x] Delete button `icon` **shouldn't** be available for `imported` cluster on list page
- [x] Delete button `icon` **shouldn't** be available for `imported` cluster on details page
- [x] Disconnect button **should** exist for list and details page for Imported cluster

### Add External AKS Cluster Machine deployment
  - [x] Check cluster creation status
  - [x] Check initial machine deployment creation
  - [x] Check "Add Machine Deployment" button exists
  - [x] Dialog should show heading "Add Node Pool" for AKS as per cloud provider name for similarity with cloud provider naming conventions.
  - [x] Check dropdown
      - [x] Check Kubernetes Versions list is fetched
      - [x] Check VM Size lists list is fetched
  - [x] Check machine deployment Auto scaling
  - [x] Check operations like create/delete/edit operation exists

### Edit External AKS Cluster Machine deployment
  - [x] Check cluster creation status
  - [x] Check edit operation exists
  - [x] Update machine deployment
     - [x] Try to update "No of Replicas" OR "Kubelet version" only **1** option is allowed to update. The other field which is not updated must be `disabled`.

### Delete External AKS Cluster
  - [x] Check cluster creation status
  - [x] Delete option is only available if cluster is not `Imported"
  - [x] Check "Disconnect" functionality is available for both `Created/Imported` cluster
  - [x] Info icon : `Cluster has nodegroups attached <nodegroups> attached` info should be displayed

## Acceptance Criteria

- [x] Add/Edit/Delete external cluster in cluster wizard
- [x] Cluster details page must show details used in wizard
- [x] Cluster details allows to add/edit/delete machine deployment for cluster
- [x] External clusters must be listed under "External Clusters" tab
- [x] Only Allow to delete/disconnect for create via wizard
- [x] Only Allow to disconnect for imported cluster via "Import External Cluster" dialog

### Other Features
- [ ] Check the API documentation

**Comment by imharshita** [comment]
found some issues: https://github.com/kubermatic/dashboard/issues/5734
https://github.com/kubermatic/dashboard/issues/5731

**Comment by imharshita** [comment]
another UI issue https://github.com/kubermatic/dashboard/issues/5740

**Comment by KhizerRehan** [comment]
https://user-images.githubusercontent.com/17727069/219066162-46d3ddbf-5a20-443a-b432-8b41f3e04f68.mp4



lgtm

**Comment by imharshita** [comment]
Works as expected
