### ISSUE TITLE
Add automatic backup: correct cron expressions are not accepted, incorrect ones are accepted - or: wrong cron docs linked

### ISSUE THREAD

**Issue by judge-red** [kubermatic/dashboard#5674]
### What happened

When trying to add an automatic (etcd) backup job with a custom interval, this doc page is linked to explain the required cron syntax:
https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc

As you can see, it requires 6 mandatory values for a cron expression - or alternatively a shorthand such as `@daily`.

When I try to enter such a cron expression in the UI, it will turn blue (and enable the "add" button) after 5 values and red (and disable the "add" button) again after 6 values. Shorthands are not accepted either.

So either KKP does not actually expect the linked format or the UI is broken.

### Expected behavior

Expect/allow for 6 values as well as shorthands (the default job even uses one: `@every 20m`!) or link to correct docs.

### How to reproduce

- add automatic backup
- choose cluster
- provide name
- choose custom intervals
- enter 6 valid values (e.g. `1 1 1 1 1 1`) or a predefined schedule (e.g. `@daily`)

### Environment
- UI Version: KKP EE 2.21.5
- API Version: KKP EE 2.21.5
- Domain: ?
- Others: ?

### Current workaround

I think the value that is not expected is the first one - seconds. So I guess we can just fill in the rest of the values, and ignore the seconds.

### Affected user persona

user cluster admins

**Comment by ahmedwaleedmalik** [comment]
@judge-red thank you for opening this ticket. 

The validators seem to be incorrect at the frontend. Although we don't support `seconds` in the cron expressions.
