### ISSUE TITLE
Add option to update existing preset

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#5677]
**What is the problem, where is it and why is it an issue?**
IMHO, while editing preset there should be options same as what we have defined while creating a `Preset`. At some point if any administrator has restrict particular preset to
- Preset Group to Domains
- Update Project List for preset bindings

**What happened**
What if user want to **restrict** preset to particular project? 

**How to reproduce**
* Go to admin `/settings/presets` path 
* Edit any **existing** preset

You have only option to hide **provider** via eye icon but nothing to update.

**Create Dialog**
<img width="652" alt="binding" src="https://user-images.githubusercontent.com/17727069/217468973-f62b5a58-10c6-4bd3-86c8-12ad2a4cd7ab.png">

**Update Preset Option**
<img width="898" alt="update-preset" src="https://user-images.githubusercontent.com/17727069/217469188-52b4f525-445b-4894-b378-831c521fe8d5.png">

### Environment
- UI Version: v2.22.0
- API Version: v2.22.0
- Domain: QA Env

**Current workaround**
currently user has to create new preset and bind **newly** created preset to restrict projects only at the time of creation.

**Suggest how to fix it, if possible**

Add DDN functionality same in "Create Preset" dialog to have Optional Restrictions.

**Comment by KhizerRehan** [comment]
Thoughts? Will be catered in next release based on feedback :)
cc: @cschieder

**Comment by cschieder** [comment]
Agreed, it would be good to have the options on edit :)

**Comment by cschieder** [comment]
blocked by #5638 I think
