### ISSUE TITLE
KubeVirt wizard allows to create node affinity preset without key

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#5684]
### What happened

When going through the KubeVirt wizard, the "advanced scheduling settings" can be configured with node affinity preset values but without node affinity preset key land the wizard allows to continue:

<img width="550" alt="Screenshot 2023-02-08 at 14 20 39" src="https://user-images.githubusercontent.com/10295525/217541587-c5dbbaef-fdae-4708-a2d3-aa7efed94519.png">

This is not a valid configuration and should be rejected by both frontend and API. We need a key to check for any values.

machine-controller logs the following errors:

```
E0208 13:23:50.075372       1 machine_controller.go:382] Failed to reconcile machine "w4bnkt75sw-worker-qddstk-85bd77bc47-xnt65": failed to create machine at cloudprovider, due to failed to create vmi: admission webhook "virtualmachine-validator.kubevirt.io" denied the request: spec.template.spec.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: Invalid value: "": name part must be non-empty, spec.template.spec.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

### Expected behavior

Invalid configuration is rejected and user cannot proceed to creating the cluster.

### Environment
- UI Version: v2.22.0-alpha.0
- API Version: v2.22.0-alpha.0
- Domain: n/a
- Others: n/a

### Current workaround

Don't configure it with invalid settings.

### Affected user persona

KubeVirt users

**Comment by Waseem826** [comment]
This has been fixed in https://github.com/kubermatic/dashboard/pull/5662. And also cherrypicked to 2.21

**Comment by embik** [comment]
Duplicate of #5650, closing. Sorry for the noise.
