### ISSUE TITLE
AKS resources endpoints not requested when credentials entered manually

### ISSUE THREAD

**Issue by imharshita** [kubermatic/dashboard#5740]
### What happened
AKS required resources endpoints are not requested when credentials are entered manually
### Expected behavior
AKS required resources endpoints are requested when credentials are entered manually
### How to reproduce
Go to Create AKS cluster wizard and enter the credentials manually 
### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by Waseem826** [comment]
Looks like none of `locations`, `versions`, `resourcegroups` and `vmsizes` are loaded when credentials are entered manually.
cc @KhizerRehan
