### ISSUE TITLE
OIDC Group Mapping is not user friendly

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#5771]
KKP 2.21.5

**What is the problem, where is it and why is it an issue?**
Currently with integrated keycloak as ID provider (I guess the same happens for DEX), it's needed to set everytime the `oidc:` prefix at the group name of the binding. The user page, doesn't show the prefix, so an user intend to not use the `oidc:` prefix. 

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/4659261/220652259-339633cf-b067-440a-bf32-045cb053d934.png)
![Cluster 'rki-fra-qs' in Project 'RKI DEVQS' 2023-02-22 10-54-19](https://user-images.githubusercontent.com/4659261/220652998-462b8ada-097f-4b66-89f9-ab3c7f3854e1.png)

**Suggest how to fix it, if possible**

The user page should also show the prefix. As this is really hard to debug

**Comment by toschneck** [comment]
Currently the prefix for K8s API  server is hardcoded https://github.com/kubermatic/kubermatic/blob/8c7e54a31a40bbcdee88c62c33ed84b78ecbada1/pkg/resources/apiserver/deployment.go#L428

Questions is how we could improve the UX as it is hard to debug

**Comment by cschieder** [comment]
I suppose generally no validation is suboptimal? We can add the prefix to each item on the User Settings page no problem although it will be very repetitive there, maybe we can find another solution?

**Comment by embik** [comment]
> I suppose generally no validation is suboptimal? We can add the prefix to each item on the User Settings page no problem although it will be very repetitive there, maybe we can find another solution?

Validation for groups isn't really possible, since group information is only included in the token passed from OIDC provider (dex) to backend. But our backend doesn't really have a way to validate if a group exists / is valid.

We could maybe offer a way to automatically add the prefix with a checkbox "OIDC group" or something while creating the binding from the UI.

**Comment by cschieder** [comment]
Okay makes sense thanks. 

The checkbox would work too. Which version do you think is more intuitive from the dev perspective? Adding the prefix on the User Settings or adding the checkbox option? 

Another possibility could be displaying it like this? 
![image](https://user-images.githubusercontent.com/49145827/225313170-4d4ab839-b77b-4d32-ad67-22292d72f21b.png)
