### ISSUE TITLE
Cannot clear vSphere "Provider Tags" on machine wizard step

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#5815]
### What happened

When trying to create a vSphere user cluster, the "Initial Nodes" step offers to select "Provider Tags" to be associated with the machines. However, selecting a category cannot be reverted / the field cannot be set to "empty" again. This is particularly problematic when you don't get offered any tags when selecting categories, so you cannot complete the setting to delete it afterwards again.

### Expected behavior

It should be possible to clear an incomplete "Provider Tags" selection.

### Environment
- UI Version: dev
- API Version: dev
- Domain: dev.kubermatic.io
- Others:

### Current workaround

Start creating the cluster from scratch.

**Comment by ahmedwaleedmalik** [comment]
If you provide a `category` and no `tag` then that provider tag is ignored so this doesn't break anything. But yeah this could be a UX improvement where we have a clear button for the category.
