### ISSUE TITLE
Machine Deployments information takes several seconds to load if no machines exist

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#5833]
### What happened

_This was reported by a customer originally._

When you use the dashboard to access a user cluster information page for a cluster that has no machines because its MachineDeployment has been scaled to zero, loading the "Machine Deployments" section takes several seconds (in my test it was 4-6 seconds):

https://user-images.githubusercontent.com/10295525/225015041-2ac1769f-1e3e-4779-be0c-9638e5958555.mov

It's much quicker with a single replica (same cluster, same environment):

https://user-images.githubusercontent.com/10295525/225015159-7e1a99fc-0958-42ea-b47f-6a1a3f4d884c.mov

This behaviour seems consistent and can be observed both on v2.21 and v2.22. I haven't checked v2.20.

I assume _something_ is running into some timeout, but I hope this can be improved in some way. It would be great to backport a fix to this to v2.22 and v2.21 since this is a customer-reported issue.

### Expected behavior

Loading times should be equal, no matter the replica count for machines. Or at least, zero replicas should not take longer than one or more.

### How to reproduce

Log into a v2.22 or v2.21 KKP installation (e.g. snapshot envs), create a user cluster with one replica in the MachineDeployment. Check loading times on the cluster information page. Scale down MachineDeployment to zero and reload cluster information page to observe increase in loading time.

### Environment
- UI Version: v2.22.0 and v2.21.6
- API Version: v2.22.0 and v2.21.6
- Domain:
- Others:

### Current workaround

No workaround apart from waiting.

### Affected user persona

cluster owners

### Metric to be improved

UI responsiveness

**Comment by pkprzekwas** [comment]
While reproducing, I noticed a significant lag between backend response and reloading component in UI.

**Comment by Waseem826** [comment]
This issue was caused because for some reason when there are 0 MD replicas, `metrics` API request takes extra time to finish and since we group all API calls together so that API call caused delay to MD list initialization. I have resolved this delay by initializing MD list without waiting for other API calls to finish. However, if you think its important to investigate why `metrics` API request takes extra time I would suggest we create a separate issue for it.
