### ISSUE TITLE
Show warning if Seed Cluster is not reachable, but don't block cluster loading

### ISSUE THREAD

**Issue by toschneck** [kubermatic/dashboard#5913]
**What is the problem, where is it and why is it an issue?**
Currently if a seed cluster is not available from the master, we have
- `2.21`: cluster searching is hanging and dashboard is blocked, see #5108 
- `2.22`:  cluster don't show up

**Suggest how to fix it, if possible**
<img width="751" alt="PROD' 2023-04-24 15-01-21" src="https://user-images.githubusercontent.com/4659261/234004097-7f992485-a622-4549-8e57-02065a0d1ad0.png">

In the above example we manage in one Project multiple cluster on different regions, so a UI user want to get a warning if some of them are not reachable (via the seed)

**Comment by pkprzekwas** [comment]
Once #5919 is finished, api will return following format of messages:
```json
# for admin users
{
  "clusters": [...],
  "errorMsg": "Failed to fetch data for following seeds: asia, europe"
}
# for non admin users
{
  "clusters": [...],
  "errorMsg": "Failed to fetch data for one or more seeds. Please contact an administrator."
}
# if there are no errors
```
