### ISSUE TITLE
Project page lags and occasionally errors on click

### ISSUE THREAD

**Issue by wozniakjan** [kubermatic/dashboard#5935]
### What happened
Error when clicking on a new project, nothing in the details field, however.

![dashboard-err](https://user-images.githubusercontent.com/1529535/236177101-38b83c9f-16a8-47f8-98ed-1446519503fa.png)

there is a matching error line in `kubermatic-api` pod
```
$ k logs deployments/kubermatic-api
...
{"level":"error","time":"2023-05-04T10:17:59.813Z","caller":"handler/routing.go:153","msg":"failed to get some projects, please examine details field for more info","request":"/api/v1/projects?displayAll=false"}
```

### Expected behavior
Clicking on projects should not throw vague errors

### How to reproduce
Create a project in the dashboard and click on it, sometimes it displays this error

### Environment
- UI Version: v2.22.2
- API Version: v2.22.2
- Domain: local deployment
- Others:

**Comment by ahmedwaleedmalik** [comment]
Couldn't reproduce
