### ISSUE TITLE
Allow removing cluster label when PodNodeSelector admission plugin and clusterDefaultNodeSelector are set

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/dashboard#5979]
### What happened

After enabling PodNodeSelector admission plugin and adding `clusterDefaultNodeSelector`, UI automatically adds label to the cluster object and this label later is synced to all nodes.

### Expected behaviour

As user, I would like to have an option to remove this label to enable creating machine deployment with nodes that don't have label specified in  `clusterDefaultNodeSelector`.

### How to reproduce

Go to cluster creation wizard, enable PodNodeSelector in admission plugins and add `clusterDefaultNodeSelector` with some value.

### Environment
- UI Version: 2.22
- API Version: 2.22

### Current workaround

-

### Affected user persona

User creating a cluster.

### Others

This issue was introduced with: https://github.com/kubermatic/dashboard/issues/4985

**Comment by Waseem826** [comment]
> It is not working in KKP v2.22.5 as intended. The delete node label button in Edit Cluster is unblocked and it is possible to delete the node label. 
> But
> 1) After deleting a node label added automatically due to clusterDefaultNodeSelector and saving, it reappears if I open Edit Cluster dialog again.
> 2) The labels are not removed from the nodes automatically. This might be due to that the kubeadm provider was not considered in this scenario (again).
>
> failed to update the controlplane: failed to list MachineDeployments: Get "https://apiserver-external.cluster-xxx.svc.cluster.local/./apis/cluster.k8s.io/v1alpha1/namespaces/kube-system/machinedeployments": dial tcp x.x.x.x:443: connect: connection refused

**Comment by Waseem826** [comment]
I have created https://github.com/kubermatic/dashboard/issues/6364 to track the 2nd issue since it doesn't relate to the original issue.
