### ISSUE TITLE
Test import kubeone clusters - Test Release 2.23

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#5990]
* create a kubeone cluster for each provider (OS, Hetzner, DO, VSphere) .
* go to the import kubeone cluster wizard
* in the Provider step chose the right provider
* in the cluster step you need to provide the kubeone manifest file and the ssh key that been used to connect to the cluster
* in the Credentials step you need to provide the credentials or the preset and make sure that you can't add both
* in the Summary step make sure that all the information are right and that any critical inputs appear as `XXXX`
```[tasklist]
### Tasks
- [x] OpenStack
- [x] Hetzner
- [x] DigitalOcean
- [x] vSphere
```

**Comment by ahmedwaleedmalik** [comment]
We need https://github.com/kubermatic/kubermatic/pull/12364 to test this.

**Comment by ahmedwaleedmalik** [comment]
Works as expected. Great job @ahmadhamzh 🚀

**Comment by ahmedwaleedmalik** [comment]
> We need [kubermatic/kubermatic#12364](https://github.com/kubermatic/kubermatic/pull/12364) before we test this.

We never got this PR merged in time so this was tested with the existing KubeOne version. I'm not sure anymore which version of KubeOne will be used for KKP 2.23 since we haven't started working on next KubeOne release yet.
