### ISSUE TITLE
Test enable accelerated networking on Azure - Test Release 2.23

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#5992]
* go to the create kkp cluster wizard and chose azure as provider 
* in the initial node step under azure settings pane, enable accelerated networking 
* check that on enable/disable accelerated networking, the list of node size is updated and the unsupported node size been hidden/shown
* after create the cluster wait till the initial node been created
* check from the provider side that the VM have the accelerated networking enabled 
* do the same for add new MD in the cluster 
* try to edit a MD by disable the accelerated networking and try to enable it again and check the provider side

**Comment by Waseem826** [comment]
One thing I noticed while testing is that even if `enableAcceleratedNetworking` is `true` for a machine deployment, edit MD dialog displays "Accelerated Networking" as not enabled.

![screenshot-kkp qa lab kubermatic io-2023 06 07-14_20_49](https://github.com/kubermatic/dashboard/assets/13975988/f1f68750-6232-4ac6-b4f5-c5180b0e249d)

<img width="757" alt="Screenshot 2023-06-07 at 2 21 52 PM" src="https://github.com/kubermatic/dashboard/assets/13975988/d0aa0239-fdf3-4ced-83e8-762f28dc1741">

**Comment by ahmedwaleedmalik** [comment]
Works fine
