### ISSUE TITLE
Can't manage clusters if Seed is down

### ISSUE THREAD

**Issue by mate4st** [kubermatic/dashboard#6056]
### What happened

If a Seed is down its not possible to manage Clusters in a second healthy Seed.

This error is constantly thrown: 

```
failed to list clusters: Get "https://******:6443/apis/kubermatic.k8c.io/v1/clusters?labelSelector=project-id%3Dpjn44v4k26": dial tcp: lookup ****** on 169.254.20.10:53: server misbehaving
```

### Expected behavior

Be able to use the Dashboard to manage Clusters in a Healthy Seed, although another Seed is down. 

### How to reproduce

Break the dedicated dev seed.

### Environment

KKP 2.22

**Comment by ahmedwaleedmalik** [comment]
Couldn't reproduce this issue. It was fixed via https://github.com/kubermatic/dashboard/pull/5944 in KKP 2.23.

**Comment by moelsayed** [comment]
I am able to reproduce this issue with KKP 2.23.4.

**Comment by moelsayed** [comment]
Additionally, login to the user cluster Kubernetes Dashboard fails in this case.
