### ISSUE TITLE
Cannot scroll the Install Addon popup in the User Cluster pane

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/dashboard#6093]
### What happened
I tried to install an addon to a user cluster, but I could not see the whole list of them, because the content of the popup flows out of the screen and it is unscrollable.

![image](https://github.com/kubermatic/dashboard/assets/18055937/c6fcd223-1bc7-4f44-a44d-c7ec86aaf346)

### Expected behavior
Install Addon popup should not flow out from the screen, and its content should be scrollable.

### How to reproduce

1. Create a user cluster
2. Go to Addons tab
3. Click on the button called + Install Addon
4. Try to scroll down

### Environment
- UI Version: 2.23.0
- API Version: 
- Domain: latest.snapshots
- Others: macOS Monterey 12.6, Chrome Version 114.0.5735.133 (Official Build) (arm64)

### Current workaround
N/A

### Affected user persona
User Cluster Admin

### Business goal to be improved
UX improvement

### Metric to be improved
Install Addon Feature Success

**Comment by ahmedwaleedmalik** [comment]
Will most likely need a backport for KKP 2.23 as well.
