### ISSUE TITLE
Test base folder path configuration in vSphere cluster - Test Release 2.24

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6301]
Test base folder path configuration in vSphere cluster and preset.

Reference PRs: https://github.com/kubermatic/dashboard/pull/6281, https://github.com/kubermatic/dashboard/pull/6282

# Testing Procedure

```[tasklist]
### Tasks
- [ ] Base folder path is configurable in vSphere preset.
- [ ] Base folder path is configurable in vSphere cluster (using both preset and credentials in the cluster wizard).
```

**Comment by ahmedwaleedmalik** [comment]
Looks fine from a frontend perspective.
