### ISSUE TITLE
Test import kubeone clusters - Test Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6306]
* create a kubeone cluster for each provider (OS, Hetzner, DO, VSphere) .
* go to the import kubeone cluster wizard
* in the Provider step chose the right provider
* in the cluster step you need to provide the kubeone manifest file and the ssh key that been used to connect to the cluster
* in the Credentials step you need to provide the credentials or the preset and make sure that you can't add both
* in the Summary step make sure that all the information are right and that any critical inputs appear as `XXXX`
```[tasklist]
### Tasks
- [x] OpenStack
- [x] Hetzner
- [x] DigitalOcean
- [x] vSphere
```

**Comment by ahmadhamzh** [comment]
## Openstack

 * node list return empty array, though the cluster have nodes 
 * Error `unable to list: default because of unknown namespace for the cache` keep coming. 
 * 
![image](https://github.com/kubermatic/dashboard/assets/85109141/01b1b404-1102-496d-9e37-dffb33d0badf)

**Comment by ahmadhamzh** [comment]
the issue mentioned above is the only problem and it is tracked by this ticket it look like it's not ui/api related 
https://github.com/kubermatic/dashboard/issues/6344
