### ISSUE TITLE
Test Admin Panel - Test Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6307]
Test Admin Panel

```[tasklist]
### Tasks
- [x] Test Interface section.
- [x] Test Manage Resources section.
- [x] Test Monitoring section.
- [x] Test Users section.
```

**Comment by Waseem826** [comment]
Seems like `Enable Share Cluster` admin setting cannot be disabled because API always return `true` value. Am I missing something or is this a bug?

**Comment by Waseem826** [comment]
> Seems like `Enable Share Cluster` admin setting cannot be disabled because API always return `true` value. Am I missing something or is this a bug?

I tried to investigate this on API side but can't find anything which might cause this. It seems like a simple boolean field. Do we create a separate issue to track this?

**Comment by pkprzekwas** [comment]
Looks like for some reason each settings page refresh sends an empty patch request to the backend `{}` resulting in overwriting everything with defaults.

**Comment by Waseem826** [comment]
> Looks like for some reason each settings page refresh sends an empty patch request to the backend `{}` resulting in overwriting `enableShareCluster` with default value. I have no idea why that happens only for this field.

If you update value of `enableShareCluster`, you'll see that the response of `PATCH` request still contains `enableShareCluster: true`.

**Comment by pkprzekwas** [comment]
I've created an issue for that - https://github.com/kubermatic/dashboard/issues/6329

**Comment by ahmedwaleedmalik** [comment]
Last remaining issue was resolved via https://github.com/kubermatic/dashboard/issues/6329
