### ISSUE TITLE
Cluster Template CRUD - Test Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6309]

**Comment by Waseem826** [comment]
Found a small issue in edit/customize cluster template where default OSP is always selected even though cluster template has annotation with custom OSP value.

**Comment by Waseem826** [comment]
Found another issue but it has been fixed in https://github.com/kubermatic/dashboard/pull/6315

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 https://github.com/kubermatic/dashboard/issues/6316 needs to be fixed for us to close this.
