### ISSUE TITLE
`enableShareCluster` button in Kubermatic settings doesn't work

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/dashboard#6329]
### What happened
Clicking on `enableShareCluster` checkmark doesn't update the value in KubermaticSettings.

### Expected behavior
Value is persisted in etcd after request is processed by API.

### How to reproduce
Go to Admin Settings and try clicking on `enableShareCluster` checkmark.

### Environment
- UI Version: 2.24.beta
- API Version: 2.24.beta
- Domain: https://kkp.qa.lab.kubermatic.io

**Comment by embik** [comment]
Stupid question, but is sharing clusters still a thing? Isn't that OIDC kubeconfigs?

**Comment by Waseem826** [comment]
> Stupid question, but is sharing clusters still a thing? Isn't that OIDC kubeconfigs?

Yes, you can use Share Cluster to just share a link to your cluster's kubeconfig. However, it still requires Kubeconfig OIDC to be enabled.
