### ISSUE TITLE
GKE field validation and cluster Version not updated 

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#6333]
### What happened

* the service account credentials have a note that it have to be base64 but actually even if add the service account as base64 the field validation shows an error but if i create a preset and i add the service account ( not in base64) it worked 

![image](https://github.com/kubermatic/dashboard/assets/85109141/3ae49e40-564f-47f3-ad2f-dd96d24b811b)

* cluster version and control plan version are not the same after update.

![image](https://github.com/kubermatic/dashboard/assets/85109141/c4cfc1a5-995d-4e45-aa53-3e6615ea4e48)

### Expected behavior
* the service account credentials should accept the service account object
* on update control plan version cluster version should show the same version
### How to reproduce
* try to create external cluster on GKE  on second step (settings) 
* create an external Cluster on GKE don't chose the latest k8s version then after the cluster been created update the control plan version cluster version should show the same value

**Comment by xrstf** [comment]
> create an external Cluster on GKE don't chose the latest k8s version then after the cluster been created update the control plan version cluster version should show the same value

The dashboard explicitly choses to show the initial version:

![2023-10-26T11-19-43](https://github.com/kubermatic/dashboard/assets/127499/05abf670-d00a-4b1e-a7ff-cd5e7e48c71b)

Not sure why, though, but fixing it should be trivial.
