### ISSUE TITLE
Backup fail with `Job has reached the specified backoff limit`

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#6336]
### What happened
it seems that all the backups and snapshot are failed due to a `Job has reached the specified backoff limit`
is that expected ? 

![image](https://github.com/kubermatic/dashboard/assets/85109141/3fd92e21-782d-4606-ac4d-b9e2c52dae13)

on the QA Environment

test issue : https://github.com/kubermatic/dashboard/issues/6311

**Comment by xrstf** [comment]
Etcd backups are misconfigured on QA (the target S3 bucket does not exist), so it's kind of expected in this case that the CronJobs will get stuck at some point. Not really something the dashboard can influence.

**Comment by ahmadhamzh** [comment]
what about the the `multiple-dest-test` is it there ? or otherwise how should we test this ?

**Comment by embik** [comment]
https://github.com/kubermatic/infra/pull/2474 should create the buckets so this no longer happens.
