### ISSUE TITLE
Display the selected value of VM Template in edit MD dialog 

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6400]
In edit MD dialog of vSphere, the default VM Template value is always selected instead of the value in MD spec.

<img width="1023" alt="Screenshot 2023-11-30 at 3 29 50 PM" src="https://github.com/kubermatic/dashboard/assets/13975988/a3637663-b499-4cc6-af26-14cba95e84ce">

This should be fixed by selecting the value from MD spec instead of always using default value.

**Comment by ahmadhamzh** [comment]
i can't reproduce the issue 
is there a special case ?
![Screenshot from 2023-12-18 14-04-44](https://github.com/kubermatic/dashboard/assets/85109141/0852b948-ffb5-47cc-aa2f-d7828b835f25)

**Comment by Waseem826** [comment]
This is reproducible if you enter a custom value for `VM Template`. The default value is set inside `_setDefaultTemplate` method which is called when OS changes or DC changes.
I couldn't find a way to fix it without breaking either the wizard or edit MD dialog.
