### ISSUE TITLE
Display the ApplicationValues with comments and send them as a string to the Backend

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/dashboard#6445]
Dependent on:

- [x] https://github.com/kubermatic/kubermatic/issues/12941

**Comment by Waseem826** [comment]
Is this something different from what's already happening in the UI? We already load `defaultValues` from application and display them in the YAML editor when adding an application.
cc @SimonTheLeg

**Comment by SimonTheLeg** [comment]
@Waseem826 From my current understanding there is a small change. My current understanding is that in the API we are sending a nested json for the values, which is then converted to yaml and displayed in the FE. With the new change in the API for 2.25 (which I am currently working on), the api would not return a nested json for the values anymore, but a long string containing a valid yaml. And then this yaml would need to be displayed in the frontend (including comments). Additionally all create/update requests, would also send the values as a long string containing the yaml.
