### ISSUE TITLE
Wrong cloud provider icons in dark mode

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#6595]
**What is the problem, where is it and why is it an issue?**
![2024-03-08T10-52-29](https://github.com/kubermatic/dashboard/assets/127499/66c04800-45af-4ef7-9c83-a6396708108f)

DO and AWS are not monochrome like all the other icons. Is this intended? It feels like we're highlighting these two providers.

**Comment by Waseem826** [comment]
Is this Firefox?
