### ISSUE TITLE
Incorrect VM template selected when limited OS allowed

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6643]
By default Ubuntu OS is selected in the wizard so the VM template for vSphere is set to the one available for Ubuntu. However, if you disallow Ubuntu from the Admin Settings then VM template is still selected for Ubuntu.

![screenshot-latest snapshots k8c io-2024 04 05-15_03_37](https://github.com/kubermatic/dashboard/assets/13975988/3daeb26e-28ac-4f83-a350-974c56e6ce6a)

This should be fixed and VM template for the current OS should be selected.

**Comment by ahmedwaleedmalik** [comment]
This is reproducible also if you are using a different template for your machine deployment than the one specified in the seed defaults.

**Comment by Waseem826** [comment]
> This is reproducible also if you are using a different template for your machine deployment than the one specified in the seed defaults.

Yes, there is another ticket for this: https://github.com/kubermatic/dashboard/issues/6400
