### ISSUE TITLE
Preset .spec.requiredEmails is not working with full email address 

### ISSUE THREAD

**Issue by archups** [kubermatic/dashboard#6686]
### What happened

When a preset is configured to use `.spec.requiredEmails` with full email address, it is not working as expected. The preset is visible during the cluster creation to other end users too instead of just to the user whose email address was configured.

### Expected behavior

Preset configured with `.spec.requiredEmails` with full email address should be visible to only those end user whose email address is part of the email address list. 

Also documented in the [presetSpec](https://docs.kubermatic.com/kubermatic/v2.25/references/crds/#presetspec) for `requiredEmails` field as follows: 
> RequiredEmails is a list of e-mail addresses that this presets should be restricted to. Each item in the list can be either a full e-mail address or just a domain name. This restriction is only enforced in the KKP API.

### How to reproduce

Configure the preset with `.spec.requiredEmails`  providing some full email address instead of email domain.  
Login to KKP dashboard using another account/email address which is not part of `.spec.requiredEmails` and from Clusters screen the user can see and select that  preset during the cluster creation from the settings tab. 

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by archups** [comment]
It had customer impact.

**Comment by ahmadhamzh** [comment]
actually i just try to restrict a preset to an email and sign in from another one and the preset is not in the list (so it's working as expected), i can't see that preset but from the user that have the email that i add in the `requiredEmails`, but what we have right now is that the **admin can see it even if his email is not in the `requiredEmails` list** (maybe this is what happened with the customer :thinking: ), also from the ui you can't add emails, just domains

**Comment by archups** [comment]
> actually i just try to restrict a preset to an email and sign in from another one and the preset is not in the list (so it's working as expected), i can't see that preset but from the user that have the email that i add in the `requiredEmails`, but what we have right now is that the **admin can see it even if his email is not in the `requiredEmails` list** (maybe this is what happened with the customer 🤔 ), also from the ui you can't add emails, just domains

Thanks @ahmadhamzh  for quick check. 
Yes this is what had happened at the customer end. Admin is able to see the preset even when his/her email address is not in `requiredEmails` list. Also there need to fix at UI to allow email address list, not jus the domain list.

**Comment by ahmadhamzh** [comment]
The PR fixes the issue where users can only restrict presets to domains in the create preset dialog. The issue where the admin can list all presets regardless of the restrict options is the expected behavior.
