### ISSUE TITLE
Get all machine types for all providers with GPU machines included

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/dashboard#6750]
### What happened
We do not support all GPU machine types at AWS probably because of an API filter
No GPU Machine Type at Azure is accessible

### Expected behavior
List all the machine types in all providers, included GPU ones.

### How to reproduce
All providers machine list needs to be validated that they have all machine types including GPUs, if not the API calls need to be refined.

### Environment
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by csengerszabo** [comment]
Needs to be investigated for all the cloud providers

**Comment by ahmadhamzh** [comment]
Is there a specific machine type that can't be found?
note that the machines list depend on datacenter
@toschneck

**Comment by toschneck** [comment]
@ahmadhamzh I didn't checked all. The Task is to exactly check that we can use all possible GPU types (most important NVIDIA) at the public clouds:
- AWS
- Azure

For google cloud there will be more todo's as GPU is other configured. @csengerszabo did you create for GCP a dedicated issue?

**Comment by csengerszabo** [comment]
> @ahmadhamzh I didn't checked all. The Task is to exactly check that we can use all possible GPU types (most important NVIDIA) at the public clouds:
> 
> - AWS
> 
> - Azure
> 
> 
> 
> For google cloud there will be more todo's as GPU is other configured. @csengerszabo did you create for GCP a dedicated issue?

I did not create another issue for GCP.

@toschneck Ahmad could not find any reason in the API until now for the phenomenon that you stated.

Can you please give use some hint or example about what machine types should be there in the list that are not presented currently?

**Comment by toschneck** [comment]
Note: all GPU Machines working in Azure and AWS, but some filters was active what filtered out GPU machines because of their CPU / Mem
