### ISSUE TITLE
Web Terminal cursor never starts new line and jumps back in the beginning

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/dashboard#6773]
### What happened
When I type certain amount of characters into one line of the Web Terminal, when it reached about half of the screen, the cursor jumps back in the beginning of the same line.
<img width="1295" alt="Screenshot 2024-08-23 at 13 12 38" src="https://github.com/user-attachments/assets/15fcd72a-b9ef-4a18-bf82-8f31ef50cfdf">

### Expected behavior
The cursos should be able to type a full line of characters, and when we reach the end of line, it should jump into the next line.

### How to reproduce

- Open Web Terminal
- Start typing something longer
- See the phenomenon

### Environment
- KKP version: v2.25.8
- Domain: https://latest.snapshots.k8c.io/

### Current workaround
Don't type in too long lines.

### Affected user persona
Web Terminal User - User Cluster Admin

### Business goal to be improved
UX for Cluster admins

**Comment by Waseem826** [comment]
According to my investigation this appears to be an API issue because on every 20th character API returns `\r` in response due to which the cursor goes to beginning of current line:
```
{"Op":"stdout","Data":"1 \r","Rows":0,"Cols":0}
