### ISSUE TITLE
Static labels for clusters - Test Release 2.26

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/dashboard#6776]
#6724

**Comment by ahmedwaleedmalik** [comment]
Few issues that I found:

## 1. If I refresh the admin panel, the static labels are not displayed

<img width="1484" alt="Screenshot 2024-09-18 at 11 38 16" src="https://github.com/user-attachments/assets/d498077a-2079-4e1a-8201-f1ccdc68d117">

## 2. When we add multiple values against a key. There is no dropdown displayed indicating that there are multiple options available for this field, the UI needs to be improved here

<img width="1484" alt="Screenshot 2024-09-18 at 11 39 13" src="https://github.com/user-attachments/assets/b255eb61-977d-4145-8e4c-46612d90c733">

## 3. The tooltip needs to be more descriptive in explaining what default and protected labels are

<img width="247" alt="Screenshot 2024-09-18 at 11 43 24" src="https://github.com/user-attachments/assets/71de16cc-8e83-4fc4-8a85-5dddc91a76e7">


cc @ahmadhamzh

**Comment by ahmedwaleedmalik** [comment]
The enhancements by @ahmadhamzh have fixed most of the issues https://github.com/kubermatic/dashboard/pull/6891. I already tested this at my end.
