### ISSUE TITLE
Default applications - Test Release 2.26

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6788]
Admin settings: https://github.com/kubermatic/dashboard/pull/6787
Cluster creation/edit wizard: https://github.com/kubermatic/dashboard/pull/6794

**Comment by Waseem826** [comment]
Works as expected but we can enhance the UX a bit.
- Add some visual feedback when changes are saved. A notification or spinner/check icon combination that we use for other settings.
- Toggle on and disable the "Default" toggle when an application is Enforced.
- Vertically center align the datacenter dropdown.

![screenshot-kkp_qa_lab_kubermatic_io-2024_09_18-13_44_13](https://github.com/user-attachments/assets/9b382e12-69c4-4578-9834-62a5a0bcf345)

**Comment by Waseem826** [comment]
This UX issue should be fixed in https://github.com/kubermatic/dashboard/issues/6762
