### ISSUE TITLE
Admin Panel - Test Release 2.26

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6823]
Test Admin Panel

```[tasklist]
### Tasks
- [x] Test Interface section.
- [x] Test Manage Resources section.
- [x] Test Monitoring section.
- [x] Test Users section.
```

**Comment by ahmadhamzh** [comment]
## 1- Interface ## 
*  **The tooltip for the "Enable Kubernetes Dashboard" option says it controls whether the "Open Dashboard" button is shown or hidden. However, if this option is disabled, we can't see the option to enable the Kubernetes dashboard in the "Create User Cluster" wizard, and the Kubernetes Dashboard namespace won't be created.**

![image](https://github.com/user-attachments/assets/906227eb-3941-44b2-bfec-311cdc0af664)


* **alignment issue**

![image](https://github.com/user-attachments/assets/ea146a0a-d0d2-4da7-898d-cf46642f4c42)

## 2- Manage Resources ## 
* **in the seed configuration page add some space between the number of datacenters and the number of non-displayed providers.**

![image](https://github.com/user-attachments/assets/8419e06e-9b86-408d-aa32-c5775eff7a40)

* **In case of email and domain restrictions, I can still see these presets if I'm an admin.**

* **The datacenter selection needs to be vertically centered, and we could consider adding a search field for selecting a datacenter.**

* **search bar is too wide in Application page and in Accounts page**

![image](https://github.com/user-attachments/assets/50a027a0-02cd-4c97-85bd-dcdfc0814279)

* **The "Add Destination" button needs some spacing.**

![image](https://github.com/user-attachments/assets/29523036-c63f-41b7-a6b3-9ed3afb76753)

**Comment by Waseem826** [comment]
> In case of email and domain restrictions, I can still see these presets if I'm an admin.

This should be fixed if its a bug because this feature is newly added in 2.26.

**Comment by ahmedwaleedmalik** [comment]
Works as expected
