### ISSUE TITLE
Annotations - Test release 2.26

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6827]
## Areas to test

1. Cluster annotations: users can add, edit, delete, and view cluster annotations in the wizard and cluster summary page
2. Machine Deployment annotations: users can add, edit, delete, and view machine deployment annotations in the wizard and machine deployment summary page.
3. Nodes: users can add, edit, delete, and view nodes annotations in the wizard and machine deployment summary page. Please be aware that we are not showing annotations in the node details view.
4. Cluster template: users can add, edit, delete, and view cluster template annotations. Clusters created using cluster template with annotations inherit the annotations from cluster templates.
5. Admin settings: annotation settings are working and properly propagated.

## References

- https://github.com/kubermatic/dashboard/pull/6809
- https://github.com/kubermatic/kubermatic/issues/11569

**Comment by Waseem826** [comment]
Works as expected.
