### ISSUE TITLE
Baremetal Provider - Test Release 2.26

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6831]
Ref: https://github.com/kubermatic/dashboard/pull/6765

```[tasklist]
### Testing Procedure
- [ ] Test creating/updating preset works
- [ ] Test CRUD datacenter works
- [ ] Test Cluster creation works
- [ ] Test creating/updating MD works
```

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 how do we test this? Do we have preset for this, what about machine deployments? Would they just work like other providers or do we need something special?

**Comment by ahmedwaleedmalik** [comment]
@mohamed-rafraf can we close this?

**Comment by mohamed-rafraf** [comment]
@ahmedwaleedmalik Yes, we can close it!
