### ISSUE TITLE
Some spacing in the advanced network configuration of the cluster creation wizard is misleading

### ISSUE THREAD

**Issue by judge-red** [kubermatic/dashboard#6860]
**What is the problem, where is it and why is it an issue?**

In step 2 (Cluster) of the cluster creation wizard: The `Ingress` checkbox has nothing to do with the textbox just below it, and the `Edit CNI Values` button has nothing to do with the checkboxes underneath it. But imho the UI suggests such a connection because it groups these things closer than other items.

<img width="654" alt="image" src="https://github.com/user-attachments/assets/c3f99eb6-e023-47b5-9ddd-bc49dbfa9318">
<img width="637" alt="image" src="https://github.com/user-attachments/assets/5a5b757f-b8b4-4840-b46e-5694be88ea30">

Also, enabling the `Ingress` checkbox actually does change the CNI values, so it should probably be relocated to the `Edit CNI Values` button (and in this case, the smaller gap between the two would make sense, imho).

**Suggest how to fix it, if possible**

I get that most checkboxes have less margin/padding than textboxes, and e.g. here I think that's good:
<img width="524" alt="image" src="https://github.com/user-attachments/assets/aea17a94-eced-4272-9420-7d7cc325ed60">

But the checkboxes mentioned above should rather use this spacing (found in step 3, Settings, probably only shown with the OpenStack provider):
<img width="631" alt="image" src="https://github.com/user-attachments/assets/239c0a72-407b-41ba-abbe-b4abe6391076">

**Comment by ahmedwaleedmalik** [comment]
Tentatively adding this to KKP 2.26 milestone since these are UI/UX issues; it'd be nice if we can fix them in 2.26 but since we are in code freeze this might not make it to 2.26.

/milestone KKP 2.26

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 has worked on these enhancements and we'll ship them in KKP 2.26 🚀
