### ISSUE TITLE
Customise Openstack provider preset - Test Release 2.26

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6861]
Ref: https://github.com/kubermatic/dashboard/pull/6807

**Comment by ahmedwaleedmalik** [comment]
1. I filled in all the required values but the `Create` button is still disabled
2. "Customizable Preset" is not an Optional restriction, it's been miscategorized here.

![Screenshot 2024-09-20 at 12 24 16](https://github.com/user-attachments/assets/6293895b-e15d-4af3-b3c2-143c280a1eb2)

Can't really continue with the testing since I can't create the preset.

**Comment by ahmedwaleedmalik** [comment]
https://github.com/user-attachments/assets/3719c035-0b20-406e-81a6-199124c33a64

**Comment by ahmedwaleedmalik** [comment]
Unable to get the floating IP pools and it won't let us move forward from there

![Screenshot 2024-09-25 at 11 41 25](https://github.com/user-attachments/assets/1609c4b2-a359-4469-949b-c568aec66645)

**Comment by Waseem826** [comment]
> Unable to get the floating IP pools and it won't let us move forward from there
> 
> ![Screenshot 2024-09-25 at 11 41 25](https://private-user-images.githubusercontent.com/18264334/370592856-1609c4b2-a359-4469-949b-c568aec66645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTAxMzQsIm5iZiI6MTcyNzI0OTgzNCwicGF0aCI6Ii8xODI2NDMzNC8zNzA1OTI4NTYtMTYwOWM0YjItYTM1OS00NDY5LTk0OWItYzU2OGFlYzY2NjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA3MzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OGFlYTYyNmU0ZGZkYWI3MWIzY2M0YTQzZmZiMzk2NjEzZGNhOTIyYTMyMjc4Yjk5ZDYyNWNjN2QzNzhkOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cmNEmgeIrbqSLY-G-V4tI3ZqjelkEXpb7QpRD4B7Y_c)

Yea, this is one of the downsides. I tested this with a different set of credentials where floating IP Pools were available and it worked as expected. 
What do you suggest we do in this particular scenario?

**Comment by ahmedwaleedmalik** [comment]
> Yea, this is one of the downsides. I tested this with a different set of credentials where floating IP Pools were available and it worked as expected.
What do you suggest we do in this particular scenario?

The problem here is that if the preset had a floating IP pool configured, even then this is displayed as empty and the cluster creation gets stuck on this page.

**Comment by Waseem826** [comment]
> > Yea, this is one of the downsides. I tested this with a different set of credentials where floating IP Pools were available and it worked as expected.
> > What do you suggest we do in this particular scenario?
> 
> The problem here is that if the preset had a floating IP pool configured, even then this is displayed as empty and the cluster creation gets stuck on this page.

Fixed in https://github.com/kubermatic/dashboard/pull/6886

**Comment by ahmedwaleedmalik** [comment]
Works as expected
