### ISSUE TITLE
Support eBPF - Test Release 2.26

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#6867]
This ticket is about testing #6757.

**Comment by ahmedwaleedmalik** [comment]
Works as expected from UI prospective

<img width="587" alt="Screenshot 2024-09-24 at 10 30 25" src="https://github.com/user-attachments/assets/dbe15301-ed69-45ea-ad18-76ffdcccc5a4">

<img width="322" alt="Screenshot 2024-09-24 at 10 31 27" src="https://github.com/user-attachments/assets/fe8e3921-c103-4bae-8a60-ecea28a21b2d">
