### ISSUE TITLE
Cannot enter custom values for ClusterBackupStorageLocation

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#6901]
### What happened
I am trying to enable the new cluster backup feature in my project. In the overlay for configuring a BackupStorageLocation, I can click on the "Use custom values" checkbox. But when I do, no code editor shows up:

![2024-10-01_12-37-32](https://github.com/user-attachments/assets/4ff76f1d-6a15-42c8-b959-b9af3ea68b5a)

### Expected behavior
A code editor should have appeared, like when editing the values for a KKP Application-

### How to reproduce
1. Go to (new) dev.
2. Create a new project if you don't have any yet.
3. Enter the project
4. Go to cluster backups > Storage Locations
5. Try to add a new one
6. In the popup, enable the checkbox for custom values.

### Environment
- UI Version: 3886d35730298528ccd8e221203b7b3f68bfc84c
- API Version: 3886d35730298528ccd8e221203b7b3f68bfc84c
- Domain: dev.kubermatic.io
- Others: tested in Firefox and Chrome

**Comment by ahmedwaleedmalik** [comment]
You have to wait for a few a seconds before it shows up, first time there is usually a delay.

**Comment by xrstf** [comment]
Oh you're right. Is that something we can improve? Is it simply loading JS/CSS? Cause at the moment I am doubly f*ed because my internet is pretty bad and so it seems to have taken 2 minutes for the editor to appear.

**Comment by ahmedwaleedmalik** [comment]
![Screenshot 2024-10-01 at 15 42 27](https://github.com/user-attachments/assets/e5eb472f-142c-420b-9a0d-58926f36fca7)

Usually doesn't take more than 2-3 seconds.

**Comment by xrstf** [comment]
![2024-10-01_12-43-33](https://github.com/user-attachments/assets/08978344-fa99-4755-bc90-842efc75902e)

2nd attempt went better. If we could have a loading indicator of some sorts that would be amazing, but yeah I'm maybe just a Vodafone victim today.

**Comment by xrstf** [comment]
In either case, there is no bug here.

**Comment by xrstf** [comment]
![2024-10-01_12-45-21](https://github.com/user-attachments/assets/c7d37b13-3802-4745-9e0d-ce0917f0abc0)

Also, I really don't know why, but man, Firefox hates numbers in this editor for me :-D Doesn't happen in Chrome and I'm not sure if it's related to some extension.
