### ISSUE TITLE
Project owners can allow/disallow operating systems that are actually disallowed globally, resulting in confusion

### ISSUE THREAD

**Issue by judge-red** [kubermatic/dashboard#6952]
**What is the problem, where is it and why is it an issue?**

Project owners can choose which OSes to allow, but OSes that are not allowed globally (admin settings) are shown. Allowing an OS on the project level doesn't overwrite the global settings, but it's confusing to project owners why allowed OSes aren't available.

**Suggest how to fix it, if possible**

Only globally-allowed OSes should be shown in project settings

**Screenshots**
Project settings:
![Image](https://github.com/user-attachments/assets/a7b935a4-da9e-4889-ab05-0f41a738958f)

Admins settings:
![Image](https://github.com/user-attachments/assets/70a03d44-0ef9-4d3a-bc06-a04d00fd2930)

**Comment by ahmedwaleedmalik** [comment]
@judge-red Thanks for opening the ticket. We understand your point, and will work on it for the next minor release.
