### ISSUE TITLE
Add an option to manage presets

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#860]
Users are often creating the clusters using the same credentials (for example same token for DigitalOcean) and each time they have to provide it inside cluster creation wizard. Perhaps it would be a good idea to create a new view that will store credentials/configurations for all providers where users would be able to create new entities and use them later during cluster creation (this time just by selecting one of the available entities).

It is just an idea to discuss if it would be possible and have any benefits for the users. It has impact on the API as most probably it would need some changes (moving credentials to secret or a new CRD?).

**Comment by cschieder** [comment]
@maciaszczykm don't we practically have this by now? Can we close this issue?

**Comment by floreks** [comment]
I guess this issue is about allowing preset creation from the UI, not only using predefined presets. This is not done yet.

**Comment by cschieder** [comment]
I think at this point it's worth recreating the issue with new fresh information rather than dragging outdated information with us but if you want to keep this issue or open a new one is up to you guys

**Comment by floreks** [comment]
You are welcome to recreate it in a new issue with a better description.

**Comment by floreks** [comment]
@cschieder do you have any mockups or ideas how it could look like? We only know that it should be added to the admin panel.

**Comment by floreks** [comment]
Closed in favor of #2798
