### ISSUE TITLE
Use consistent naming convention for structures and fields

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#945]
There are some places where inconsistent naming conventions are used for structure fields (camelCase vs underscore). We should try to follow one convention at all times.

In example, exported json fields naming in [here](https://github.com/kubermatic/kubermatic/blob/62b04a3e4508e4ca26f67abef80f102f46e59ac6/api/pkg/provider/datacenter.go#L36-L44) is dictated by `datacenters.yaml` file format.

Then in the frontend it is mapped directly to underscore notation.
https://github.com/kubermatic/dashboard-v2/blob/24b43ebd9e6ce397aa035b12f95f030b497d3520/src/app/shared/entity/datacenter/OpenStackDatacenterSpec.ts#L3-L8

We would need to add some kind of mapping or refactor whole `datacenters.yaml` file. 

@maciaszczykm @kgroschoff @p0lyn0mial

**Comment by cschieder** [comment]
@kubermatic/ui-team this issue is over a year old, is it still relevant?

**Comment by maciaszczykm** [comment]
I'd like to change it in the future but it is not that important and has an impact on the project setup.
